mit-plv/fiat-crypto

- src/Spec/EdDSA.v
I submit this as a pull request, because we seem to have been avoiding `Import`s in this file up until this point, and I'm not sure what policy we want to take here.
> Make fiat-crypto compile with both 8.4 and 8.5

- AUTHORS
- CONTRIBUTORS
- LICENSE
Closes #5.
I added licensing information according to the same pattern that I previously used for `dename` at MIT, G and Y. Old commits were incorporated such that everybody is listed in `CONTRIBUTORS` and individuals were assumed hold copyright for the contributions they submitted while not employed at the relevant institutions.
> update licensing information for #5

- src/BaseSystem.v
- src/BaseSystemProofs.v
- src/Encoding/ModularWordEncodingTheorems.v
- src/ModularArithmetic/ModularBaseSystemOpt.v
- src/ModularArithmetic/ModularBaseSystemProofs.v
- src/ModularArithmetic/PrimeFieldTheorems.v
- src/ModularArithmetic/PseudoMersenneBaseParamProofs.v
- src/Testbit.v
- src/Util/NumTheoryUtil.v
- src/Util/ZUtil.v
The standard library uses `Z.*`, and `Z*` and `Z_*` are compatibility
notations, I believe.  We follow suit.
Also, eliminate a few lemmas that are duplicates of ones in the standard
library.
The first commit does the renaming; the second is purely an indentation change.
@andres-erbsen @jadephilipoom any objections?  Does this interfere with anything you're working on?
> Rename lemmas about Z in ZUtil

- _CoqProject
- src/ModularArithmetic/BarrettReduction/Z.v
This will serve as the high-level algorithm for modular reduction.
We follow Wikipedia very closely, except where we can do better (I
believe @jadep is updating Wikipedia).
Questions:
Any other comments? (@agl @mschilder123)
> Implement and prove Barrett reduction on Z

- _CoqProject
- src/Algebra.v
- src/CompleteEdwardsCurve/CompleteEdwardsCurveTheorems.v
- src/CompleteEdwardsCurve/ExtendedCoordinates.v
- src/CompleteEdwardsCurve/Pre.v
- src/Encoding/PointEncodingPre.v
- src/Spec/CompleteEdwardsCurve.v
- src/Tactics/Algebra_syntax/Nsatz.v
- src/Util/Tactics.v
- src/WeierstrassCurve/Pre.v
Supersedes #16; closes #10; closes #15.
Several replacements were made in separate commits:
- `nsatz` was redefined in `Algebra.v` as `nsatz; dropRingSyntax`, other files were changed to import that instead
- uses of `field_algebra` were replaced with `super_nsatz`, `nsatz` and `conservative_common_denominator` as appropriate.
- `common_denominator` family tactics were replaced with `conservative_common_denominator` family tactics
- `common_denominator` tactics were renamed to `field_simplify_if_div`
- `conservative_common_denominator` tactics were renamed to `common_denominator`
In some cases, `super_nsatz` is a too big hammer: when the goal contains many hypotheses of the form `?x <> 0` then `super_nsatz` takes a long time, but `intro; apply; rewrite; ring` wins quickly. This speedup …
> stop using raw nsatz, field_algebra, common_denominator

- src/ModularArithmetic/ExtendedBaseVector.v
- src/ModularArithmetic/ModularBaseSystem.v
- src/ModularArithmetic/ModularBaseSystemInterface.v
- src/ModularArithmetic/ModularBaseSystemOpt.v
- src/ModularArithmetic/ModularBaseSystemProofs.v
- src/ModularArithmetic/Pow2Base.v
- src/ModularArithmetic/PseudoMersenneBaseParamProofs.v
Also use [ZUtil.Z.pow2_mod].  Making `base` a notation lets us remove the dependency of
ModularBaseSystem on ModularArithmetic.PseudoMersenneBaseParamProofs.
This is a small part of reorganizing and factoring ModularBaseSystem for
use with Barrett reduction.
> Make [base] and [log_cap] notations

- src/ModularArithmetic/ModularBaseSystem.v
- src/ModularArithmetic/ModularBaseSystemOpt.v
- src/ModularArithmetic/ModularBaseSystemProofs.v
- src/ModularArithmetic/Pow2Base.v
- src/ModularArithmetic/Pow2BaseProofs.v
- src/Util/ZUtil.v
These definitions don't depend on PseudoMersenneBaseParams, only on
limb_widths, and we'll want them for BarrettReduction / P256.
@jadephilipoom, does this conflict with anything you want to do?
@jadephilipoom @andres-erbsen is there any reason to prefer defining `add_to_nth` as `set_nth n (x + nth_default 0 xs n) xs` vs `update_nth n (fun y => x + y) xs`, or vice versa?
> Move some definitions to Pow2Base

- src/ModularArithmetic/Pow2Base.v
It leads to a slightly more transparent and clearer definition.
If I got everything right, nothing should depend on the judgmental
definition of [add_to_nth] anymore.
@andres-erbsen does this break any of your plans for optimized Gallina code?
> Use update_nth in add_to_nth

- _CoqProject
- src/Algebra.v
- src/Assembly/Pseudize.v
- src/Assembly/Pseudo.v
- src/Assembly/QhasmEvalCommon.v
- src/Assembly/QhasmUtil.v
- src/Assembly/State.v
- src/Assembly/Vectorize.v
- src/Assembly/Wordize.v
- src/BaseSystem.v
- src/CompleteEdwardsCurve/CompleteEdwardsCurveTheorems.v
- src/CompleteEdwardsCurve/ExtendedCoordinates.v
- src/Encoding/PointEncodingPre.v
- src/Experiments/DerivationsOptionRectLetInEncoding.v
- src/Experiments/GenericFieldPow.v
- src/ModularArithmetic/ModularArithmeticTheorems.v
- src/ModularArithmetic/ModularBaseSystemOpt.v
- src/ModularArithmetic/ModularBaseSystemProofs.v
- src/ModularArithmetic/Pow2BaseProofs.v
- src/ModularArithmetic/Pre.v
- src/ModularArithmetic/PrimeFieldTheorems.v
- src/Util/FixCoqMistakes.v
- src/Util/ListUtil.v
- src/Util/Notations.v
- src/Util/NumTheoryUtil.v
- src/Util/Tactics.v
- src/Util/Tuple.v
- src/Util/ZUtil.v
This PR makes the library 20% faster: `auto with *` is evil
I do hereby revoke the privilege of `intuition` to grab random hints from random databases.  This privilege is reserved for `debug_intuition`, which comes with a warning about not being used in production code.  This tactic is useful in conjunction with `Print Hint *`, to discover what hint databases the hints were grabbed from.
(Suggestions for renaming `debug_intuition` welcome.)
Any file using `intuition` must `Require Export Crypto.Util.FixCoqMistakes.`.  It's possible we could lift this
restriction by compiling `FixCoqMistakes` separately, and passing along `-require FixCoqMistakes` to Coq.  Should we do this?
I've also absolutized some imports in the process of making this change.
I plan to merge this in about an hour; …
> Redesign intuition, speeding up overall compilation by 20%

- Makefile
- README.md
This allows most users to not need to type COQPATH=... on make.
@andres-erbsen , do you think this is fine, or do you object to doing this in the `Makefile`.  (Here it really just is to eliminate typing characters.)
> Convenience settings: If COQPATH is not set, set it by default

- src/Util/Equality.v
- src/Util/HProp.v
- src/Util/Isomorphism.v
- src/Util/Sigma.v
As rightly requested by @andres-erbsen
> Add documentation: Equality, HProp, Isomorphism, Sigma

- _CoqProject
- src/ModularArithmetic/BarrettReduction/ZGeneralized.v
In this version, we split up the integer division so that we are less
likely to overflow in intermediate computations.
This is still not the version in HAC 14.42; that version also does early
reduction modulo b^(k+1).
This is work towards #43
> Add a generalized version of Barrett Reduction

- .travis.yml
Each version of 8.4 takes around 17 minutes to complete.  I've yet to see anything that behaves differently among 8.4{,pl1,pl2,pl3,pl4}, or among 8.4pl{5,6}.  So if we keep 8.4pl3 (the version of Coq distributed in debian trusty), and 8.4pl6, we should capture the range of behaviors, and save about an hour-and-a-quarter per test.
> Test fewer Coq versions on Travis

- _CoqProject
- src/ModularArithmetic/Montgomery/Z.v
- src/ModularArithmetic/Montgomery/ZProofs.v
This is partly done for my own benefit, to internalize how Montgomery
multiplication works, and partly done as a template for word-based
Montgomery multiplication when the carrying does not take advantage of
the fact that we are using a pseudomersenne prime.
(@agl @mschilder123 @andres-erbsen @jadephilipoom) I'm looking for feedback on style, as well as correctness of transcription for ECC.
> Define Montgomery reduction / multiplication on Z

- src/Algebra.v
- src/CompleteEdwardsCurve/CompleteEdwardsCurveTheorems.v
- src/CompleteEdwardsCurve/Pre.v
- src/Encoding/ModularWordEncodingPre.v
- src/Encoding/ModularWordEncodingTheorems.v
- src/Experiments/DerivationsOptionRectLetInEncoding.v
- src/Experiments/SpecEd25519.v
- src/ModularArithmetic/ModularArithmeticTheorems.v
- src/ModularArithmetic/ModularBaseSystem.v
- src/ModularArithmetic/ModularBaseSystemField.v
- src/ModularArithmetic/ModularBaseSystemList.v
- src/ModularArithmetic/ModularBaseSystemProofs.v
- src/ModularArithmetic/Pre.v
- src/ModularArithmetic/PrimeFieldTheorems.v
- src/ModularArithmetic/Tutorial.v
- src/Spec/ModularArithmetic.v
- src/Spec/ModularWordEncoding.v
- src/Spec/WeierstrassCurve.v
- src/Specific/GF1305.v
- src/Specific/GF25519.v
- src/Util/AdditionChainExponentiation.v
- src/Util/Decidable.v
- src/Util/Equality.v
- src/Util/NumTheoryUtil.v
- src/WeierstrassCurve/Pre.v
ModularArithmetic now uses Algebra lemmas in various places instead of
custom manual proofs. Similarly, Util.Decidable is used to state and
prove the relevant decidability results.
Backwards-incompatible changes:
F_some_lemma -> Zmod.some_lemma
Arguments ZToField _%Z _%Z : clear implicits.
inv_spec says inv x * x = 1, not x * inv x = 1
> Refactor ModularArithmetic into Zmod, expand Decidable

- _CoqProject
- src/ModularArithmetic/BarrettReduction/ZBounded.v
- src/ModularArithmetic/Montgomery/ZBounded.v
- src/ModularArithmetic/ZBounded.v
Also use it to implement Montgomery reduction and Barrett reduction.
The `ZLikeOps` type is a collection of the operations needed for Montgomery and Barrett in (roughly) the machine code I'm targeting.  It's probable there's a better specification for the base language here.  Feedback on this point welcome.
Note that, once the initial bounds are established, if the algorithm is in the right form (does modular reduction in all the right places to make it obvious that nothing goes out of bounds), then it's very simple to convert from operations on `Z` to operations on this type.
Next up is instantiating this type with digits / a `limb_width`-based representation.
> Specify a type of bounded integers for modular arithmetic

- src/Util/LetIn.v
- src/Util/Notations.v
For "definition".  This fixes #65; [Let] conflicts with the vernacular
[Let] in Coq 8.4.
@andres-erbsen Feel free to pick some other notation if you'd prefer.  I'm pushing this now so that 8.4 builds again.
> Change [Let ... in ...] to [dlet ... in ...]

- _CoqProject
- src/BoundedArithmetic/ArchitectureToZLike.v
- src/BoundedArithmetic/ArchitectureToZLikeProofs.v
- src/BoundedArithmetic/DoubleBounded.v
- src/BoundedArithmetic/DoubleBoundedProofs.v
- src/ModularArithmetic/Montgomery/ZBounded.v
- src/Reflection/Named/Compile.v
- src/Reflection/Named/ContextOn.v
- src/Reflection/Named/DeadCodeElimination.v
- src/Reflection/Named/EstablishLiveness.v
- src/Reflection/Named/RegisterAssign.v
- src/Reflection/Named/Syntax.v
- src/Reflection/TestCase.v
- src/Specific/FancyMachine256/Barrett.v
- src/Specific/FancyMachine256/Core.v
- src/Specific/FancyMachine256/Montgomery.v
This is on top of #66, and replaces #68.
Barrett and Montgomery no longer need CSE.
Still no proofs, but there's working dead code elimination and register assignment.  The interface is that you provide a list of names, and these names are used, in order, after dead code is dropped.  (You can also skip dead code elimination when compiling.)  If you try to reuse a register that still alive when you overwrite it, the compilation returns `None`.  This integrates well with the carry bit; as long as all operations that set/clear the carry bit bind a carry value in the syntax tree, you can use the same "register" for all of the carry bits, and you'll be informed if you're trying to use a clobbered carry bit.
The fancy machine assembly is now checked and interpreted (rather than there being a …
> Scalable Scalars, Dead Code Removal, Register Assignment

- _CoqProject
- src/Experiments/MontgomeryCurve.v
Unsuccessful attempt at formalizing Montgomery coordinates for elliptic curves. Unsuccessful, because I ran out of steam before I managed to establish isomorphism to weierstrass. It would be kinda nice if this kept building, so that it is not that bad to pick it up later.
> montgomery-curve

- _CoqProject
- src/Reflection/Conversion.v
- src/Reflection/TestCase.v
This might properly belong in Experiments rather than TestCase.  It demos the
ability to transform from one kind of constants to another kind, and to plug
bounds calculation functions into [var] to get bounds.  There's not currently
any sort of correctness theorem, and I'm not entirely sure what one would look
like.  Probably something that says that if you map a function over the syntax
tree and then interpret, you could instead have first interpreted and then
applied the function.
I'm hopeful that this will provide a template for integrating this version of
the syntax with rsloan-phoas.
I probably won't have any more time to play with this aspect of the reflection before the end of my internship; I'll be porting the CSE code, and the assembly for montgomery.
> Small example of bounds-calculation with dependent types

- src/BoundedArithmetic/Interface.v
I haven't yet written code to make sure this is everything I need, but I think it suffices.
Feedback I want:
1. Do all these instructions exist.
2. Which of them do things with the carry flag?
Also, I'm planning to implement reduce-modulo as
```
let '(CF, _) := sub ret modulus in
let '(CF, v) := subc 0 0 in
let maybe_modulus := and v modulus in
let '(CF, ret) := sub ret maybe_modulus in
Return ret
```
> Add spec for x86

- src/Util/WordUtil.v
These need to be constant time with respect to the words being manipulated, so converting to N and operating there is no good.
@JasonGross @achlipala: I introduced some machinery for working with words whose sizes are equal by `Logic.eq` but not convertible, and I am not sure whether what I did is a good way to go about it.  The core of it is `cast_word {n m} : forall {pf:wordsize_eq n m}, word n -> word m`, an identity function that only uses the proof argument in impossible cases, so the proof can be opaque. I also added hooks for proving word size equalities using hints (`omega` for now), and `Qed`-wrapped the goal type so that other tactic/typeclass machinery does not mess with it.
No correctness proofs yet, but should be rather straightforward, so I am punting until we actually …
> word manipulation functions for secret key formatting

- src/ModularArithmetic/ModularBaseSystem.v
- src/ModularArithmetic/ModularBaseSystemOpt.v
- src/ModularArithmetic/ModularBaseSystemProofs.v
- src/Specific/GF25519.v
Implementing @jadephilipoom's idea to carry on these to make the word versions into a field.
@jadephilipoom, there are two `Admitted` proofs here.  Can I assign you to fill them in?
> Add opt versions of add, sub, opp

- _CoqProject
- src/Specific/GF25519Bounded.v
Boundedness is axiomatized as
```coq
Axiom ExprBinOp : Type.
Axiom ExprUnOp : Type.
Axiom interp_bexpr : ExprBinOp -> Specific.GF25519.fe25519 ->
Specific.GF25519.fe25519 -> Specific.GF25519.fe25519.
Axiom interp_uexpr : ExprUnOp -> Specific.GF25519.fe25519 ->
Specific.GF25519.fe25519.
Axiom radd : ExprBinOp.
Axiom rsub : ExprBinOp.
Axiom rmul : ExprBinOp.
Axiom ropp : ExprUnOp.
Axiom rinv : ExprUnOp.
Axiom radd_correct : forall x y, interp_bexpr radd x y = carry_add x y.
Axiom rsub_correct : forall x y, interp_bexpr rsub x y = carry_sub x y.
Axiom rmul_correct : forall x y, interp_bexpr rmul x y = mul x y.
Axiom ropp_correct : forall x, interp_uexpr ropp x = carry_opp x.
Axiom rinv_correct : forall x, interp_uexpr rinv x = inv x.
Axiom check_bbounds : ExprBinOp -> bool.
Axiom …
```
> First pass at bounded version of GF25519

- _CoqProject
- src/Assembly/GF25519BoundedInstantiation.v
- src/Experiments/Ed25519.v
- src/Specific/GF25519Bounded.v
- src/Specific/GF25519BoundedCommonWord.v
This plugs admitted lemmas for the boundedness proofs into Experiments/Ed25519.
This should not change the code that's being run (though I haven't looked at the extracted code at all; e.g., we might need more extraction directives).
Currently, `feDec` is unsound; I was under the impression that `unpack` requires 25/26 bounds on its input to produce sane output.  But `feDec` gives only the guarantee that the elements are bounded by the wordsize.  So there's something fishy going on here. (@andres-erbsen @jadephilipoom do you know what's going on?)
Reverting the change from bounded words to bounded Z should take no more than 2.5 hours (an overestimate for how long it took me to make the bounded-Z changes for PR), if we decide to go that way.
@andres-erbsen I'd like to assign you to …
> Use Bounded Z in GF25519Bounded and fill Ed25519 with bounded things

- src/Specific/GF25519Reflective/Reified/rebuild-reified.py
This is on top of #97, and should be merged after #97.  (I don't want to update #97 because I have two PRs on top of it, and Jade mentioned working on top of it, so I don't want to rebase them.)  I'm making this a PR just so that I don't forget to do this.
> Remove dead python code

- _CoqProject
- src/Specific/GF25519Reflective/Reified/AddCoordinates.v
Currently kind-of slow, and more verbose than I'd like.  But we have a reified and mostly-bounds-checked version of `add_coordinates`.  (By "mostly", I mean that it's bounds checked, but I haven't proven that the output bounds are tighter than the input bounds, and I haven't assembled it all into a convenient package; I want to first figure out how this is going to fit into the pipeline.)
> Add reified mostly-bounds-checked add_coordinates

- src/CompleteEdwardsCurve/ExtendedCoordinates.v
- src/Experiments/Ed25519.v
This is in preparation for dropping extra carries.  What remains to be
done, after this and #106, is to finish packaging up the reified
[add_coordinates] so that it can operate on [Tuple.tuple
GF25519BoundedCommon.fe25519 4], and then to prove
```coq
forall twice_d P1 P2, Tuple.fieldwise GF25519BoundedCommon.eq
(<reflected add_coordinates> twice_d P1 P2)
(@ExtendedCoordinates.Extended.add_coordinates GF25519BoundedCommon.fe25519
GF25519Bounded.add GF25519Bounded.sub GF25519Bounded.mul twice_d
P1 P2)
```
I'm not sure how to do this, or even what the right structure for the
proof is.
> Generalize add_coordinates

- _CoqProject
- src/NewBaseSystem.v
- src/Util/Tactics.v
- src/Util/Tactics/VM.v
Use a vm_compute hack fromhttps://arxiv.org/pdf/1305.6543.pdf section 5.5:
pattern terms over what to keep opaque, then reduce the lambda using vm_compute.
This reduces the synthesis time from 37s to 1.8s.
We should decide how bad of an idea it is to actually use this strategy -- it is definitely much more fragile than `cbv -[]`.
> speed up NewBaseystem synthesis

- src/Util/Tuple.v
- src/Util/ZRange.v
We don't need both of them.  We keep the definition of pointwise2
because it's needed for reification to work, and we keep the name of
fieldwise because it's used in more places.  This closes #137.
> Coalesce Tuple.pointwise2 and Tuple.fieldwise

- _CoqProject
- src/Specific/IntegrationTestSub.v
Currently it seems that `sub` doesn't bounds-check; it fails with
```
The term "eq_refl" has type "true = true" while it is expected to have type
"Interpretation.Bounds.is_tighter_thanb
(r[0 ~> 2251799813685247], r[-18014398509481984 ~> 18014398509481984], r[-18014398509481993 ~> 18014398509481992],
r[-72057594037927936 ~> 72057594037927936], r[-72057594037927936 ~> 72057594037927936])
(r[0 ~> 2533274790395904], r[0 ~> 2533274790395904], r[0 ~> 2533274790395904], r[0 ~> 2533274790395904],
r[0 ~> 2533274790395904]) = true".
```
@jadephilipoom do you know what's up with this?  You seem to be using 2^52 in the first limb and 2^51 in all the others?
> Add IntegrationTest for Sub (doesn't work)

- src/Curves/Montgomery/XZ.v
We also need to stuff the local notations in a scope so that we can
still access the notations in core_scope
> Use the for-loop notation in Montgomery.XZ

- src/Util/ZUtil.v
Is there any reason to keep this?
> Remove dead code in ZUtil (shiftl_by)

- src/Util/ZUtil/Definitions.v
- src/Util/ZUtil/Morphisms.v
In ZUtil/Definitions.v
@jadephilipoom Are these definitions that you can work with?  (I changed them a bit from the definitions you're using, and am having them work only for powers of 2, in part so that the reified code doesn't need to carry around large values on every add, and so that I don't need to hard-code the expanded value of 2¹²⁸ into the notations); does this seem reasonable?)
@andres-erbsen Is this general enough?  Is restricting ourselves to powers of two okay?
> Add definitions for zselect and add_get_carry

- src/Compilers/CommonSubexpressionElimination.v
- src/Compilers/CommonSubexpressionEliminationInterp.v
- src/Compilers/CommonSubexpressionEliminationWf.v
- src/Compilers/TestCase.v
- src/Compilers/Z/Bounds/Pipeline/Definition.v
- src/Compilers/Z/CommonSubexpressionElimination.v
- src/Compilers/Z/CommonSubexpressionEliminationInterp.v
- src/Compilers/Z/CommonSubexpressionEliminationWf.v
- src/Specific/FancyMachine256/Core.v
This takes care of most of #158.  The remaining bits are reworking the Wf and interpretation lemmas to actually work.  (The former needs a only bit of rethinking and rephrasing to handle the fact that sometimes we change the stored symbolic expression from a complicated one to a fresh variable, while the latter needs major surgery, which Adam tells me is easy.)
> CSE modulo arithmetic without inlining

- _CoqProject
- src/Util/ZUtil/AddGetCarry.v
This is on top of #170 
It proves the transformation described in #171 correct on `Z` (the transformation is not yet implemented reflectively)
> Add-carry optimization proof

- src/Compilers/Z/ArithmeticSimplifier.v
- src/Compilers/Z/ArithmeticSimplifierInterp.v
- src/Compilers/Z/ArithmeticSimplifierWf.v
- src/Compilers/Z/Bounds/Interpretation.v
- src/Compilers/Z/Bounds/InterpretationLemmas/IsBoundedBy.v
- src/Compilers/Z/Bounds/Pipeline/Definition.v
- src/Compilers/Z/CNotations.v
- src/Compilers/Z/CommonSubexpressionElimination.v
- src/Compilers/Z/Reify.v
- src/Compilers/Z/Syntax.v
- src/Compilers/Z/Syntax/Equality.v
- src/Compilers/Z/Syntax/Util.v
- src/Specific/IntegrationTestFreezeDisplay.log
- src/Util/ZUtil/AddGetCarry.v
- src/Util/ZUtil/Definitions.v
- src/Util/ZUtil/Morphisms.v
Freeze is now almost pretty:
```
λ x : word64 * word64 * word64 * word64 * word64,
Interp-η
(λ var : Syntax.base_type → Type,
λ '(x7, x8, x6, x4, x2)%core,
uint64_t x10, bool x11 = subborrow_u51(0x0, x2, 0x7ffffffffffed);
uint64_t x13, bool x14 = subborrow_u51(Op (Syntax.Opp Syntax.TZ (Syntax.TWord 0)) (Op (Syntax.Opp (Syntax.TWord 0) Syntax.TZ) (Return x11)), x4, 0x7ffffffffffff);
uint64_t x16, bool x17 = subborrow_u51(x14, x6, 0x7ffffffffffff);
uint64_t x19, bool x20 = subborrow_u51(x17, x8, 0x7ffffffffffff);
uint64_t x22, bool x23 = subborrow_u51(x20, x7, 0x7ffffffffffff);
uint64_t x24 = (uint64_t) (x23 == 0 ? 0x0 : 0xffffffffffffffffL);
uint64_t x25 = x24 & 0x7ffffffffffed;
uint64_t x27, bool x28 = addcarryx_u51(0x0, x10, x25);
uint64_t x29 = x24 & 0x7ffffffffffff;
uint64_t x31, bool …
```
> SubWithBorrow

- _CoqProject
- src/Arithmetic/MontgomeryReduction/WordByWord/Abstract/Dependent/Definition.v
- src/Arithmetic/MontgomeryReduction/WordByWord/Abstract/Dependent/Proofs.v
- src/Arithmetic/MontgomeryReduction/WordByWord/Definition.v
- src/Arithmetic/MontgomeryReduction/WordByWord/Proofs.v
- src/Arithmetic/Saturated.v
- src/Specific/MontgomreyP256.v
- src/Util/CPSUtil.v
The new parameterized definitions and proofs are in
WordByWord/Abstract/Dependent/*; the old ones are untouched (and unused)
in WordByWord/Abstract/*.  I replaced definitions I didn't know how to
write in the Saturated API with the use of an axiom.
> Switch to using tuples for word-by-word montgomery

- src/Arithmetic/MontgomeryReduction/WordByWord/Proofs.v
- src/Arithmetic/Saturated.v
- src/Util/CPSUtil.v
You might want to do something other than locally passing `(bound_gt_1 : bound > 1)`, but that was the most local change I could make to get the proof to go through.
Remaining admits in P256:
```coq
Axioms:
Saturated.small_divmod : forall bound : Z,
(bound > 0)%Z ->
forall (n : nat) (p : Saturated.T (S n)),
Saturated.small bound p ->
Tuple.left_hd p =
(Saturated.eval bound p / Saturated.uweight bound n)%Z /\
Saturated.eval bound (Tuple.left_tl p) =
(Saturated.eval bound p
mod Saturated.uweight bound n)%Z
Saturated.small_div : forall bound : Z,
(bound > 0)%Z ->
forall (n : nat) (v : Saturated.T (S n)),
Saturated.small bound v ->
Saturated.small bound (fst (Saturated.divmod v))
Saturated.small_conditional_sub : forall bound : Z,
(bound > 0)%Z ->
forall (n : nat)
(mask : Z) (p : Saturated.T …
```
> Prove admits

- src/Specific/IntegrationTestMontgomeryP256_128_Opp.v
- src/Specific/IntegrationTestMontgomeryP256_128_Sub.v
- src/Specific/NISTP256/AMD64/IntegrationTestMontgomeryP256_Opp.v
- src/Specific/NISTP256/AMD64/IntegrationTestMontgomeryP256_Sub.v
This should not be merged until @jadephilipoom fills in `sub_then_maybe_add_cps` and `sub_then_maybe_add` in `src/Arithmetic/MontgomeryReduction/WordByWord/Definition.v`.  Once those axioms are replaced by definitions, this should be enough to make the pipeline spit out C code.
> Remove admits

- etc/governor.sh
- etc/hyperthreading.sh
- etc/machine.sh
- etc/turboboost.sh
It needs to be in performance, not powersave, to work well on my
machine.
While we're at it, also have the scripts print usage if you pass no
arguments, rather than giving an error message about $1 being unset.
> Update etc scripts to include governor

- .travis.yml
Travis was too slow to run all of the coq target, so we split off the
no-curves-proofs and the curves-proofs targets, and, while we're at it,
also add 8.7+beta1 tests.
> Hopefully fix travis

- Makefile
- _CoqProject
- src/Util/AdditionChainExponentiation.v
This is the correct way to handle things, rather than `-compat 8.6`, when we're willing to move to requiring Coq 8.6.1 or Coq 8.7 (neither of which is currently released)
> [8.6.1] Less init plugins

- .travis.yml
- src/Curves/Weierstrass/Projective.v
Prove correctness of single-case addition procedure for Weierstrass curve points `P` and `Q` such that `(P+P = Q+Q) -> P = Q`. We probably want to wrap these definitions for the simple case of `forall P, P <> zero -> P + P <> zero` where `P-Q = zero <-> (P-Q)+(P-Q) = zero`.
> projective Weierstrass: (2P = 2Q -> P = Q) -> not exceptional

- coqprime/Coqprime/Pmod.v
- coqprime/Coqprime/ZCmisc.v
This is preparing the landing of https://github.com/coq/coq/pull/1049.
For now, I'm duplicating this patch which was already done upstream in
CoqPrime, but please consider removing this ad-hoc copy (see discussion
on PR #269).
> Remove obsolete syntax for locality.

- src/Util/Notations.v
This sets the level and associativity in a common place, and will be useful for PHOAS application nodes.  Making a PR just to get travis to test the versions we care about.
> Reserve a printing-only notation for function application

- src/Experiments/SimplyTypedArithmetic.v
It's rather verbose, unfortunately.  The reification also doesn't have
any of the nice debugging features of the version of reification in
Compilers, because that's even more boilerplate.  Not sure if I should
add that back in, at the moment.
Also, for some strange reason, places where `constr`s fail to typecheck
seem to induce backtracking where I don't think they should, and I'm not
sure what's going on...
> [demo] Add reification in src/Experiments/SimplyTypedArithmetic.v

- src/Curves/Montgomery/XZ.v
- src/Curves/Montgomery/XZProofs.v
This PR is to check that the elliptic curve arithmetic at https://boringssl.googlesource.com/boringssl/+/7ce2378750f9f56459ddba67947c3c4ba001a526/third_party/fiat/curve25519.c#4945 does what we want it to do. In particular, we prove it equivalent to the version in https://cr.yp.to/ecdh/curve25519-20060209.pdf appendix B, which has already been proven to correspond to addition in affine coordinates at https://github.com/mit-plv/fiat-crypto/compare/boringladderstep?diff=split&expand=1&name=boringladderstep#diff-d9c50f42ae6bdbec2520e416b2848608R150
Apparently the previous decision to name the small hardcoded constant `a24` was a poor one: the two ladderstep functions use two different hardcoded constants (`(a+2)/4` and `(a-2)/4`) compensating for it with slight changes in the formula. …
> Curves.Montgomery.XZ: add+check boringssl ladderstep

- Makefile
This will break Coq's CI because they recently broke `src/Specific/NISTP256/AMD*/Synthesis.vo`, so we should wait for them to fix https://github.com/coq/coq/issues/6323 before merging this.
> Test more synthesis files on travis / lite

- src/Experiments/SimplyTypedArithmetic.v
Here is the code that implements what we discussed today.  It doesn't do the right thing.  In particular, the recursive call to `partial_reduce_cps` in the `Abs` node is wrong; it should not always be passing `Var`, but instead be computing something of shape `expr -> expr` that gets handled correctly elsewhere.  I'm too deep into the code to make sense of the exact issue right now; the encoding in my head is "the var types for different pieces of machinery don't line up the right way; has something to do with cps, probably; has something to do with arrows, probably", which is unhelpful.
> Partial work on implementing partial reduction

- src/Experiments/SimplyTypedArithmetic.v
Most of what we talked about today is in here.  I haven't translated @jadephilipoom 's python script to Gallina.  I also haven't assembled things together into a ring.  I'm (almost) quite happy with the tactic that executes the pipeline for a specific choice of parameters / prime:
```coq
Ltac solve_rcarry_mul _ :=
eapply rcarry_mul_correct;
lazy; reflexivity.
```
My biggest issue is that the `lazy` runs twice: once during the proof, and again during `Qed`.
Once Jade's script is translated to Gallina, the curve-specific code for a single operation will look like:
```coq
Derive fecarry_mul SuchThat (rcarry_mul_correctT "2^255 - 19" 64) As fecarry_mul_correct.
Proof. Time solve_rcarry_mul (). Time Qed.
```
A large chunk of the code here is to about allowing a more general sort of …
> [experiments] Implement much of the bounds pipeline (no proofs)

- coqprime/Coqprime/Iterator.v
- coqprime/Coqprime/Permutation.v
- coqprime/Coqprime/UList.v
The Implicit Arguments command is deprecated, and these changes already happened in https://github.com/thery/coqprime: see [Iterator.v](https://github.com/thery/coqprime/blob/bed89c336f6d0615afe86f9a7e153f9479e84199/List/Iterator.v#L85-L87) [Permutation.v](https://github.com/thery/coqprime/blob/bed89c336f6d0615afe86f9a7e153f9479e84199/List/Permutation.v#L437-L440) [UList.v](https://github.com/thery/coqprime/blob/bed89c336f6d0615afe86f9a7e153f9479e84199/List/UList.v#L258)
See also coq/coq#6802
> Change Implicit Arguments to Arguments in coqprime

- src/Util/WordUtil.v
Changes:
-  https://github.com/mit-plv/bbv/pull/1: `pow2_id` is now definitionally true and thus unnecessary.
> bump submodules; remove pow2_id

- _CoqProject
- src/Arithmetic/BarrettReduction/RidiculousFish.v
This variant comes from http://www.ridiculousfish.com/blog/posts/labor-of-division-episode-i.html. It was useful for https://boringssl-review.googlesource.com/#/c/boringssl/+/25887.
Andres suggested it could live in fiat-crypto and that I should make a PR so you all can tell me all the ways I did it inefficiently/non-idiomatically. (This is probably the first `repeat match` I've ever written by myself?) It was also originally a standalone file and I don't know what utilities you have, so I'm sure a lot of the support bits can be replaced.
> Prove another Barrett reduction variant.

- src/Experiments/SimplyTypedArithmetic.v
This allows us to remove the special case for `bool_rect`, and is a
step towards targeting `vm_compute` rather than `lazy`.
Note that this does not, in fact, seem to by itself allow `vm_compute` to work in reasonable time; the `lazy` in `base_51_add` takes about 0.5 seconds, while using `vm_compute` takes over a minute.
> [experiments] Thunk the eliminator cases

- src/Experiments/SimplyTypedArithmetic.v
This makes the pipeline faster to run under vm_compute than under lazy.
I suspect mainly because I've replaced [bool_rect] with [if].
> Thunk let-bound default values, unfold bool_rect

- src/Experiments/SimplyTypedArithmetic.v
Now things like `carry_mulmod` no longer have manual uncurrying.  This also unifies the "constant" and "1-argument" versions of the pipeline.  Uncurrying happens in the second stage of the pipeline, after caching; this makes it a bit easier to phrase the correctness and caching lemmas, because it means that we don't need to translate between curried and uncurried things when phrasing the correctness of the cache.
> [experiments] Uncurry in phoas

- src/Arithmetic/BarrettReduction/Generalized.v
- src/Util/ZUtil/Div.v
The estimated quotient in Barrett reduction (`q`, here) is known to have an error of at most 2--that is, using the variable names in the `Generalized.v` file, `q = a  / n - e` and `0 <= e <= 2`.
However, it turns out that for primes that fit a certain condition (see `n_good` in this PR), we can prove `0 <= e <= 1`, which lets us skip a modular reduction.
@JasonGross These proofs are significantly messier than the ones you wrote in `Generalized`--if you have tips for better utilizing the automation I'd appreciate it.
> barrett quotient error

- Makefile
Because pipes eat error codes, we were previously succeeding when
display targets fail.  This meant that we didn't catch
https://github.com/mit-plv/fiat-crypto/issues/344#issuecomment-381422896
on Travis.  Now we will.
> Error if a display target fails

- src/Experiments/SimplyTypedArithmetic.v
- src/Util/ZUtil/Definitions.v
I reprinted the code for Montgomery and X25519_64, and nothing is affected. This should be pretty mechanical, but I'll make a PR to pass it under @JasonGross's sanity check.
> Add some instructions in preparation for reifying barrett

- src/Curves/Weierstrass/Jacobian.v
The immediate motivation is BoringSSL's generic EC code is sadly stuck
with supporting arbitrary curves, including those where a <> -3, but it
may be more generally useful.
This makes the file slightly more general:
- It now proves that the addition formula works independent of a = -3.
- It proves a generic doubling implementation, based on
http://www.hyperelliptic.org/EFD/g1p/auto-shortw-jacobian.html#doubling-dbl-2007-bl
- There's a place to stick in other specializations should someone want
them. (I hear some folks are interested in secp256k1 for some reason.)
(The diff looks large, but it's mostly because a chunk got re-indented.)
> Generalize Jacobian.v over all a.

- src/Experiments/SimplyTypedArithmetic.v
They disappear after the end of the section, but I want them to stay in
distr_length for later proofs.
> Add some Positional Hint Rewrites

- src/Experiments/SimplyTypedArithmetic.v
Previously I was trying to make the proof easier by using the same var
type for input and output (which would allow a
correctness-of-interpretation proof which doesn't depend on
well-formedness).  We now no longer do that, and instead go from `@expr
(@expr var)` to `@expr var`, and avoid introducing useless `Abs` and
`App` nodes.
> Don't introduce extra lambdas and apps in uncurry

- src/Experiments/SimplyTypedArithmetic.v
Seems to work for P-192, but P-256 is a huge, huge term that takes longer to process than I have so far been willing to wait. 
It makes sense that P-256 is huge--by my back-of-the-napkin calculation, it should have these numbers of terms:
pre-multiplication: 8 terms per operand
post-multiplication : 128 partial products (8 * 8 * 2 -- the x2 is because we use 2-output multiplication)
reduction 1 : 64 + 4*64 terms (since 64 are in the "low" part, and c has 4 terms)
...and so on, until after the 8 required reductions we have 1649 terms. I think this can be mediated with some cancelling-out of additions and subtractions of the same partial product, but haven't quite figured that part out yet.
> Saturated solinas reduction

- .travis.yml
Now we test master, v8.8.dev, v8.7.dev, 8.8.0, and 8.7.2, instead of master,
v8.7.dev, and 8.7.1.
> Bump versions of Coq we test on travis

- src/Experiments/SimplyTypedArithmetic.v
Pass that converts code to syntactically-straightline form and a second pass that forces code to use only a particular set of operations. Seems to work for Montgomery reduction and most of Barrett reduction (it fails to translate the last few lines because of #352). No proofs yet.
I would like a review from @andres-erbsen or @JasonGross of my pass to straightline (`Module Straightline`), before I devote too much time to proofs of this version. `Module PreFancy`, the second pass, is simpler and less critical to get a review on (in particular, I imagine anything that could use improvement there would pop up in `Straightline` also).
> Straightline

- src/Curves/Montgomery/XZ.v
Dear fiat-crypto developers, this is a patch for compatibility with PR coq/coq#262.
PR coq/coq#262 makes the inference of return clauses more uniform and general but unification is sometimes not strong enough to deal with this generality. See coq/coq#5107 for details.
One reduces the search space for the return clause by forbidding it to be obtained by small inversion (using a `return _`).
Note that the patch is backwards compatible and can be applied as soon as now, even with PR coq/coq#262 not yet merged.
> Compatibility with respect to Coq PR#262

- src/Util/ListUtil.v
This allows us to make use of nested fixpoints involving map2, because
the function argument can be inlined for guard checking now.
> Move function argument out of fixpoint of List.map2

- src/Arithmetic/BarrettReduction/RidiculousFish.v
- src/Experiments/NewPipeline/Language.v
- src/Experiments/PartialEvaluationWithLetIn.v
- src/Util/GlobalSettings.v
We make all parameters implicit, and set `Uniform Inductive Parameters`.
I expect this is backwards compatible, hopefully CI backs me up.
Not to be merged until coq/coq#7254 and coq/coq#7703 have converged.
> Adapt to coq#7254

- _CoqProject
- src/Experiments/NewPipeline/Arithmetic.v
- src/Experiments/SimplyTypedArithmetic.v
- src/Util/ZUtil.v
- src/Util/ZUtil/Div.v
- src/Util/ZUtil/Le.v
Now we actually prove that it gives a unique representation out.  Note that although we've changed the definition of `to_bytesmod`, the synthesized C code is unchanged.  It would be nice to prove that we don't need this extra flatten pass; see https://github.com/JasonGross/fiat-crypto/tree/zzz-wip-better-arith-proofs for partial work in this direction.
> Update freeze to include Rows.flatten

- _CoqProject
- src/Arithmetic/BarrettReduction/Generalized.v
- src/Arithmetic/BarrettReduction/RidiculousFish.v
- src/Arithmetic/Saturated/MontgomeryAPI.v
- src/Experiments/NewPipeline/Arithmetic.v
- src/Experiments/NewPipeline/Toplevel1.v
- src/Experiments/SimplyTypedArithmetic.v
- src/LegacyArithmetic/Double/Proofs/Multiply.v
- src/LegacyArithmetic/Double/Proofs/RippleCarryAddSub.v
- src/Util/QUtil.v
- src/Util/ZUtil.v
- src/Util/ZUtil/AddGetCarry.v
- src/Util/ZUtil/CC.v
- src/Util/ZUtil/Div.v
- src/Util/ZUtil/Div/Bootstrap.v
- src/Util/ZUtil/Modulo.v
- src/Util/ZUtil/Modulo/Bootstrap.v
- src/Util/ZUtil/Tactics/DivModToQuotRem.v
- src/Util/ZUtil/Tactics/RewriteModSmall.v
- src/Util/ZUtil/ZSimplify/Autogenerated.v
It now handles things in the context by default, and also handles cases
where we don't have non-zero hypotheses.
> Make Z.div_mod_to_quot_rem stronger

- src/Experiments/NewPipeline/AbstractInterpretation.v
- src/Experiments/NewPipeline/CStringification.v
- src/Experiments/NewPipeline/CompilersTestCases.v
- src/Experiments/NewPipeline/GENERATEDIdentifiersWithoutTypes.v
- src/Experiments/NewPipeline/Language.v
- src/Experiments/NewPipeline/Rewriter.v
We now support reification of nat_rect returning an arrow.  This is
needed for montgomery.
> Allow reification of nat_rect (fun _ => _ -> _)

- src/Experiments/NewPipeline/AbstractInterpretation.v
- src/Experiments/NewPipeline/AbstractInterpretationProofs.v
Yet another premature optimization
```
After     | File Name                                                            | Before    || Change    | % Change
--------------------------------------------------------------------------------------------------------------------
17m43.04s | Total                                                                | 17m43.59s || -0m00.55s | -0.05%
--------------------------------------------------------------------------------------------------------------------
0m21.28s  | p384_32.c                                                            | 0m22.70s  || -0m01.41s | -6.25%
5m51.41s  | Experiments/NewPipeline/SlowPrimeSynthesisExamples                   | 5m50.56s  || +0m00.84s | +0.24%
4m31.08s  | Experiments/NewPipeline/Toplevel1 …
```
> Remove fastpath for Zcast in absint

- src/Experiments/NewPipeline/AbstractInterpretation.v
- src/Experiments/NewPipeline/AbstractInterpretationProofs.v
- src/Experiments/NewPipeline/AbstractInterpretationWf.v
- src/Experiments/NewPipeline/LanguageWf.v
- src/Experiments/NewPipeline/UnderLetsProofs.v
We now no longer fuse annotations
It was causing issues with proving things, and isn't really needed.
Instead, we just check if the current annotation is exactly the state
we're attempting to annotate with; if it is, then we don't double up on
identical annotations.
> A bit more progress on abstract interpretation proofs

- src/Experiments/NewPipeline/RewriterRulesGood.v
On top of #404, this proves the rewrite-rule-specific parts of the wf proofs.  As a separate PR so that maybe we can finally merge #404 without having to do more back-and-forth with travis to work around build-time/memory limits.
> Finish rewriter wf proofs

- src/Specific/Framework/MontgomeryReificationTypes.v
- src/Specific/Framework/ReificationTypes.v
> Remove unused Require

- src/Experiments/NewPipeline/CStringification.v
This is a second instance of an incompatibility introduced by coq/coq#262 (see fiat-crypto commit 251ea49a). One fixes it the same, reducing the search space for a return clause by forbidding it to be obtained by small inversion. I did not double-check explicitly but this should be backwards-compatible.
> Compatibility after Coq PR#262 (continued)

- src/Experiments/NewPipeline/GENERATEDIdentifiersWithoutTypes.v
- src/Experiments/NewPipeline/GENERATEDIdentifiersWithoutTypesProofs.v
- src/Experiments/NewPipeline/Rewriter.v
- src/Experiments/NewPipeline/RewriterProofs.v
- src/Experiments/NewPipeline/RewriterRulesGood.v
- src/Experiments/NewPipeline/RewriterWf1.v
- src/Experiments/NewPipeline/RewriterWf2.v
- src/Experiments/NewPipeline/StandaloneHaskellMain.v
- src/Experiments/NewPipeline/StandaloneOCamlMain.v
- src/Experiments/NewPipeline/Toplevel2.v
- src/Experiments/NewPipeline/arith_rewrite_head.out
- src/Experiments/NewPipeline/fancy_rewrite_head.out
- src/Experiments/NewPipeline/nbe_rewrite_head.out
This paves the way for writing down interpretation proofs for the
rewriter by writing down "default interpretations".  Otherwise, e.g.,
there was not enough type information to write down any good
interpretation for [map fst nil] (which would bind no type variables in
the previous veresion).
Unfortunately the rewriter itself got a bit slower (though the proof of
rewrite-rule-correctness got a bit faster).
```
After     | File Name                                                            | Before    || Change    | % Change
--------------------------------------------------------------------------------------------------------------------
24m05.07s | Total                                                                | 24m08.92s || -0m03.85s | -0.26% …
```
> Support type variables in patterns in the rewriter

- _CoqProject
- src/Experiments/NewPipeline/RewriterRulesInterpGood.v
- src/Experiments/NewPipeline/RewriterWf1.v
- src/Experiments/NewPipeline/RewriterWf2.v
The NBE-rewrite rules are proven correct.  The arith and fancy rewrite
rules are reduced to lemmas about Z, most of which are inconsistent (and
therefore indicate rewrite rules which are missing side-conditions).
One bad rewrite rule was found in this process, and corrected in
0842563b23f8d780f4ff1080d7620fc3f368191f
The next step after this will be using the rewrite rule correctness to
prove the rewriter correct.
@jadephilipoom I'd like to leave the remaining admits in `src/Experiments/NewPipeline/RewriterRulesInterpGood.v` in this PR to you (see the comments before `exact admit`); there are 25 of them, and most of them are false.  If you back up to after the `all: try solve [ ... ]` lines, you can see where the goals originally come from; I'm happy to help you adjust the rewrite rules …
> Add interp-correctness condition for rewriter

- src/Experiments/NewPipeline/AbstractInterpretation.v
- src/Experiments/NewPipeline/AbstractInterpretationProofs.v
- src/Experiments/NewPipeline/AbstractInterpretationWf.v
- src/Experiments/NewPipeline/AbstractInterpretationZRangeProofs.v
- src/Experiments/NewPipeline/CompilersTestCases.v
- src/Experiments/NewPipeline/Language.v
- src/Experiments/NewPipeline/LanguageWf.v
- src/Experiments/NewPipeline/Toplevel2.v
We fuse the bounds relaxation pass with the abstract interpretation pass
by folding bounds relaxation into the annotation method.  This allows us
to not need any particular assumptions about what happens when you cast
outside the range.
We can therefore now guarantee that the output of casting is always
bounded by the given range (rather, by the normalized version of the
range), which will be required to take advantage of bounds information
in the rewriter (because otherwise we're not guaranteed that casting
something to within a range actually outputs something within that
range).
> Guarantee that casting always returns inrange

- src/Util/SideConditions/ReductionPackages.v
Hi, this is a backward-compatible change in relation with coq/coq#8745
as [suggested](https://github.com/coq/coq/pull/8745#issuecomment-432335811) by @jasongross.
> Tactic-in-term: ensuring same scope for all occurrences of a notation variable

- etc/ci/travis.sh
Because remove_autogenerated.sh updates _CoqProject, and we don't want
to see the churn from that.
> [travis] Always display the diff, but don't display _CoqProject

- src/Experiments/NewPipeline/LanguageWf.v
`base_type` and `base_interp` are already abstracted by the section.
For compatibility with coq/coq#8820.
> Remove duplicate abstraction

- src/Util/SideConditions/ReductionPackages.v
Hi, this is another backward-compatible change in relation with coq/coq#8745 (I missed it initially).
Follow-up of PR #450.
> Tactic-in-term: ensuring same scope for all occurrences of a notation variable (continued)

- src/Experiments/NewPipeline/Arithmetic.v
- src/Experiments/NewPipeline/SlowPrimeSynthesisExamples.v
We now preserve the invariant that weights are in the image of the
weight function, insofar as we can, which allows a more fine-tuned
analysis of values.
With some inspiration and help from @jadephilipoom .  This should help with #326
> Use a better strategy in Rows.sat_reduce

- src/Experiments/NewPipeline/Rewriter.v
- src/Experiments/NewPipeline/RewriterRulesGood.v
- src/Experiments/NewPipeline/RewriterRulesInterpGood.v
- src/Experiments/NewPipeline/Toplevel1.v
- src/Experiments/NewPipeline/arith_rewrite_head.out
- src/Experiments/NewPipeline/arith_with_casts_rewrite_head.out
- src/Experiments/NewPipeline/nbe_rewrite_head.out
Because we need to do extra passes of DCE and subst01 to fully reduce
things, we generalize some of the interp proofs over cast behavior.
For ease of rewriting, we make [ident.interp] an alias (notation) for
[ident.gen_interp], rather than a [Definition].
We also factor out the rewriting wrapper inside the pipeline module into
its own definition.
Unfortunately, this incurs non-trivial slow-down:
```
After     | File Name                                                            | Before    || Change    | % Change
---------------------------------------------------------------------------------------------------------------------
32m09.80s | Total                                                                | 26m07.22s || +6m02.58s | +23.13% …
```
>  Split off all of the arithmetic rules that need bounds info

- src/Experiments/NewPipeline/MiscCompilerPasses.v
- src/Experiments/NewPipeline/MiscCompilerPassesProofs.v
- src/Experiments/NewPipeline/Toplevel1.v
Based on https://github.com/coq/coq/issues/8993#issuecomment-438572277,
I am guessing that DCE is currently memory-hungry.  This makes sense,
because every [var] is carrying around a full `PositiveSet.t` when
computing live variables.  Instead, we now adjust `subst01` to not
increment counts coming from dead variables, and use it to implement
DCE.  Hopefully this will be much faster and more efficient.
N.B. It was important to stop doing union of `PositiveMap.t`, and instead add to them incrementally.
```
Before: p384_32.c (real: 406.78, user: 391.99, sys: 14.82, mem: 16896040 ko)
After:  p384_32.c (real: 201.11, user: 200.33, sys:  0.80, mem:  1039520 ko)
After     | File Name                                                            | Before    || Change    | % Change …
```
> Base Dead Code Elim on Subst01

- src/Experiments/NewPipeline/Language.v
- src/Experiments/NewPipeline/LanguageInversion.v
- src/Experiments/NewPipeline/LanguageWf.v
- src/Experiments/NewPipeline/Rewriter.v
- src/Experiments/NewPipeline/RewriterRulesInterpGood.v
- src/Experiments/NewPipeline/RewriterWf1.v
- src/Experiments/NewPipeline/RewriterWf2.v
- src/Experiments/NewPipeline/UnderLetsProofs.v
This version is hopefully the right one.  It seems to be basically
exactly what we want to say, and no more and no less.  The rule for
let-ins, which is almost the only freedom we have here, is chosen to
match exactly with the rule for App+Abs.  Note that using Leibniz
equality is essential in the places where it's used.  The recursive
relation here might actually be a bit clearer as an inductive relation,
but I wanted it to simplify under reduction.
(I still need to actually prove all the generic rewriter interp proofs using this)
> Switch to a more precise version of interp_related for rewrites

- _CoqProject
- src/Experiments/NewPipeline/RewriterInterpProofs1.v
- src/Experiments/NewPipeline/RewriterProofs.v
Other than the use of function extensionality in a particular place,
this completes the proofs of the rewriter.
It was rather painful to figure out the right way to phrase rewriter
correctness.  I tried a number of more lax approaches (e.g., various
variants of saying what it means for two rawexprs to be equivalent,
saying what it means for two values to be equivalent, etc), but ran into
issues with incomparable relations.  The right approach was to find the
most precise thing that could be said, and to relate each kind of thing
(rawexpr, value, expr, etc) to an interpreted value, and push that
around throughout the proof.  The only exception to this pattern is
`eval_decision_tree`, for which a fine-grained notion of rawexpr
equivalence can be stated (basically, the equivalence-closure of …
> Finish rewriter proofs modulo funext

- src/Experiments/NewPipeline/Toplevel1.v
These are the last of the non-fancy-machine admits in the pipeline (other than funext).  They were about correctness of `to_bytes`/`from_bytes`, and now they are proven.
> Remove glue admits

- src/Experiments/NewPipeline/Arithmetic.v
- src/Util/ListUtil.v
I also did a couple things along the way, like:
- relocate some proofs about weight functions (they were previously in `Saturated`, but had nothing to do with saturated weights)
- restructure the `eval` and `small` proofs a bit so that work wasn't duplicated--instead I proved that they were both at the same time and then made tiny proofs to say each separately
- remove some cruft -- unnecessary preconditions to a few lemmas and a commented-out lemma that ended up not being needed
> Prove admits for word-by-word Montgomery

- curve25519_32.c
- curve25519_64.c
- p224_32.c
- p224_64.c
- p256_32.c
- p256_64.c
- p384_32.c
- p384_64.c
- p484_64.c
- p521_32.c
- p521_64.c
- secp256k1_32.c
- secp256k1_64.c
- src/CStringification.v
Unfortunately, signed->unsigned casts do not commute with shifts.  We
take care to only extend the range when it needs extending, now.  This
was previously causing issues with subborrow.
We should really get proofs about casts in C semantics at some point
soon.
Fixes #489
@davidben Does this fix your issue?
> Don't cast signed to unsigned before shifting

- src/PushButtonSynthesis.v
This disables the optimization that was recently introduced for
replacing things known to be 0 from the bounds analyzer with the
constant 0.  It was messing up some of the other fancy synthesis stages.
Fixes #498
> Don't allow r[0~>0] ranges in fancy synthesis

- src/CLI.v
- src/PushButtonSynthesis.v
We no longer accept `1,1` as a valid bitwidth.
This closes #488.  It does not quite fix the issue as stated, but it
resolves the underlying confusion that generated it (the difference
between passing `1,1` as a `c` vs passing `1,1` as a bitwidth).  It
still might be nice to someday emit warnings as suggested in the bug
report.
I've also factored out a bit of code to make it easier to report parse
failures, by folding over a list of parses.
On top of #499, so that travis accepts the build.
> Be stricter about rejecting command line arguments

- src/Algebra/Ring.v
This is in preparation for coq/coq#9274.
Should backward compatible but that remains to be tested.
> Make trivial instances explicit

- .travis.yml
We combine two stages that are both fairly quick (early and lite), and
we move nobigmem from coq to pre-standalone in an attempt to hopefully
decrease the incidence of OOM issues on travis.
> Improve travis stages

- src/AbstractInterpretation.v
- src/AbstractInterpretationProofs.v
- src/AbstractInterpretationWf.v
- src/BoundsPipeline.v
- src/Rewriter.v
- src/RewriterProofs.v
- src/RewriterRulesGood.v
- src/RewriterRulesInterpGood.v
- src/arith_with_casts_rewrite_head.out
- src/fancy_with_casts_rewrite_head.out
- src/strip_literal_casts_rewrite_head.out
Unless we explicitly say not to.  The ability to explicitly say not to
is required for, e.g., eta-expansion where we want to replace variable
lists of known length with with cons cells indexing into the variable
list, but don't want to pollute the code with casts.
Uniformity in this way allows rewrite rules to not blow up exponentially
(in the number of wildcards); we previously required a separate rewrite
rule for each way of choosing between wildcard and literal.
To preserve output of the pipeline, we add another pass that just strips
the casts off of literals at the end.
@jadephilipoom Is there anything I have to check (other than that things compile) to ensure I haven't broken the fancy-machine stuff?
```
After     | File Name                                    | Before    || Change …
```
> Insert casts before literals during bounds analysis

- src/AbstractInterpretation.v
- src/AbstractInterpretationProofs.v
- src/AbstractInterpretationWf.v
- src/AbstractInterpretationZRangeProofs.v
- src/BoundsPipeline.v
- src/CStringification.v
- src/CompilersTestCases.v
- src/GENERATEDIdentifiersWithoutTypes.v
- src/GENERATEDIdentifiersWithoutTypesProofs.v
- src/Language.v
- src/LanguageInversion.v
- src/LanguageWf.v
- src/Rewriter.v
- src/RewriterWf1.v
- src/UnderLets.v
- src/UnderLetsProofs.v
- src/arith_rewrite_head.out
- src/arith_with_casts_rewrite_head.out
- src/fancy_rewrite_head.out
- src/fancy_with_casts_rewrite_head.out
- src/nbe_rewrite_head.out
- src/strip_literal_casts_rewrite_head.out
This is needed to reify statements for the rewriter.
On top of #519 
You could look at this as a proof-of-concept of how hard/easy it is to add new types to the language.  Note that most of the pain of adding `option` is in supporting it in a semi-reasonable manner in abstract interpretation.
Note to self: I still need to:
>  Add support for reifying `zrange` and `option`

- src/Language.v
- src/LanguageInversion.v
These are the canonical boolean equality functions for the interpretations of the various base types.  This will probably come in handy for side conditions in proofs about reifications of rewrite rules.
> Add base.{base_,}interp_beq

- src/Rewriter.v
- src/RewriterRulesInterpGood.v
- src/arith_rewrite_head.out
- src/arith_with_casts_rewrite_head.out
- src/fancy_with_casts_rewrite_head.out
- src/nbe_rewrite_head.out
- src/strip_literal_casts_rewrite_head.out
Currently we don't handle rules that require "concrete list of cons
cells" nor rules that require "concrete nat literal to do recursion on";
both of these require special treatment, to be implemented in an
upcoming commit.
The reifier is kind-of slow, alas.
Timing diff:
```
After     | File Name                                    | Before    || Change    | % Change
--------------------------------------------------------------------------------------------
1m12.22s  | Rewriter.vo                                  | 0m47.38s  || +0m24.83s | +52.42%
```
> Reify most rewrite rules

- .travis.yml
As discussed over chat with Andres and Jason. It's annoying to fix things that work on every Coq version we support except 8.7 (especially because all of us primarily use newer versions of Coq). Merging this PR would mean we only support master, 8.9, and 8.8.
> remove 8.7 from travis tests

- _CoqProject
- src/Language.v
- src/PushButtonSynthesis/Primitives.v
- src/Rewriter.v
- src/Util/ListUtil.v
- src/Util/Tactics.v
- src/Util/Tactics/ConstrFail.v
- src/Util/Tactics/DebugPrint.v
Rather than taking the convention that failures during constr
construction emit a type error from `I : I` with the actual error
message `idtac`d above them (because Coq has no way to emit multiple
things on stderr), we instead factor everything through a new
`constr_fail` or `constr_fail_with msg_tac`, which emit more helpful
messages instructing the user to look in `*coq*` or to use `Fail`/`try`
to see the more informative error message.  When we can make our own
version that does both `idtac` and `fail` (c.f.
https://github.com/coq/coq/issues/3913), then we can do something a bit
more sane, hopefully.
> Add constr_fail and constr_fail_with

- src/Rewriter.v
- src/RewriterRulesGood.v
- src/RewriterRulesInterpGood.v
- src/RewriterWf1.v
- src/SlowPrimeSynthesisExamples.v
It unfortunately makes some of the synthesis things a bit slower, because we now rely on "rewrite again in the output" to handle more reduction.  However, it is not significantly slower at synthesis.
Next steps: Either: (a) splitting off the special "eagerly" rules, and autoinferring the "do again" annotations, or (b) separating out the lemmas into a separate file, and using proofs of the lemmas themselves in the interp-correctness conditions.
```
After     | File Name                                    | Before    || Change    | % Change
--------------------------------------------------------------------------------------------
22m23.84s | Total                                        | 21m34.63s || +0m49.21s | +3.80%
----------------------------------------------------------------------- …
```
> Finish reifying list lemmas

- src/Rewriter.v
- src/RewriterInterpProofs1.v
- src/RewriterProofs.v
- src/RewriterRules.v
- src/RewriterRulesGood.v
- src/RewriterRulesInterpGood.v
- src/RewriterWf1.v
Now we actually make use of the rewrite-rule-specific proofs, rather
than duplicating them inline.
We now support reifying `ident.gets_inlined` to
`SubstVarLike.is_var_fst_snd_pair_opp_cast`.
We also now fix a bug where we previously incorrectly substituted
context variables when reifying side conditions (needed for correct
reification of split-mul things, coming up soon).
Things are unfortunately a bit slow.
I'm not sure what's up with my proof of
`reflect_ident_iota_interp_related`; it seems more complicated than it
should be (maybe partly due to funext concerns).
Next up is to split out the rewrite rule generation bits into separate
files and have a single tactic that builds the entire package for us (in
prep for making the rewriter builder a vernacular).  After that I want
to more …
> Automate more of the rewriter reification, proof

- src/GENERATEDIdentifiersWithoutTypes.v
- src/GENERATEDIdentifiersWithoutTypesProofs.v
- src/Rewriter.v
We now rely on Ltac rather than python to generate the raw identifiers.
```
After     | File Name                                       | Before    || Change    | % Change
-----------------------------------------------------------------------------------------------
22m05.90s | Total                                           | 21m51.87s || +0m14.03s | +1.07%
-----------------------------------------------------------------------------------------------
0m49.25s  | GENERATEDIdentifiersWithoutTypesProofs.vo       | 0m55.23s  || -0m05.97s | -10.82%
0m19.14s  | GENERATEDIdentifiersWithoutTypes.vo             | 0m13.35s  || +0m05.79s | +43.37%
0m36.52s  | ExtractionHaskell/saturated_solinas             | 0m32.60s  || +0m03.92s | +12.02%
0m24.00s  | SlowPrimeSynthesisExamples.vo …
```
> Replace the python script with Ltac code

- src/GENERATEDIdentifiersWithoutTypes.v
- src/GENERATEDIdentifiersWithoutTypesProofs.v
- src/Rewriter.v
- src/RewriterWf1.v
Since more of the definitions are now done in Gallina, hopefully these
should be easier to factor out / parameterize over the type of
identifiers, now.
```
After     | File Name                                       | Before    || Change    | % Change
-----------------------------------------------------------------------------------------------
21m28.78s | Total                                           | 21m49.80s || -0m21.01s | -1.60%
-----------------------------------------------------------------------------------------------
0m22.98s  | GENERATEDIdentifiersWithoutTypesProofs.vo       | 0m49.53s  || -0m26.55s | -53.60%
0m47.26s  | p521_32.c                                       | 0m44.08s  || +0m03.17s | +7.21%
0m36.30s  | ExtractionHaskell/saturated_solinas             | 0m32.96s …
```
> Do less reduction in GENERATEDIdentifiersWithoutTypes

- Makefile
Since we in general don't build all the files (in fact, we never do), we
only try to install files that actually exist, to avoid errors from
Coq's new way of installing things.
Note that including `install` as a target along with targets that build
things is no longer supported, as it would require fancier makefile
hackery.
Fixes #548 (I hope)
> Kludge around coq/coq#9906

- _CoqProject
- src/ArithmeticCPS/BaseConversion.v
- src/ArithmeticCPS/Core.v
- src/ArithmeticCPS/Freeze.v
- src/ArithmeticCPS/ModOps.v
- src/ArithmeticCPS/Saturated.v
- src/ArithmeticCPS/WordByWordMontgomery.v
This is primarily for perf testing purposes, so we can evaluate the time
spent in the rewriter vs cbv/vm/native/etc for the cps'd versions.
We evaluate vm_compute and native_compute by parameterizing everything
over a module of runtime definitions, which can be instantiated with
module-locked opaque constants, which are not unfolded by the vm.
> Add CPS'd versions of arithmetic operations

- .travis.yml
- Makefile
By moving it to the -j1 part.  We also now build perf standalone files.
> Fix OOM on travis on PerfTesting/Core

- src/CStringification.v
- src/LanguageStringification.v
- src/PushButtonSynthesis/Primitives.v
- src/RustStringification.v
This way we can correctly (not) insert `pub` in the Rust code when we
should(n't).
@zoep does this look good to you?
> Thread `static` argument through `typedef_header`

- src/Compilers/Syntax.v
For compatibility with coq/coq#9918
Closes #564
We could instead have just removed all of the Compilers/InSet stuff, as
nothing depends on it (and the issue it was meant to work around in
reification by parametericity is (a) fixed by using `type of` in Ltac
and (b) doesn't even seem to be used in the reification pass).
Instead, I chose to leave the existing code mostly as-is, and insead
move the one inductive that needs to be template-polymorphic out of a
section.  I chose this because it seems to be the decision that is
marginally in the direction of stress-testing Coq more.
> [sp2019latest] Move a template inductive outside a section

- fiat-rust/src/curve25519_32.rs
- fiat-rust/src/curve25519_64.rs
- fiat-rust/src/p224_32.rs
- fiat-rust/src/p224_64.rs
- fiat-rust/src/p256_32.rs
- fiat-rust/src/p256_64.rs
- fiat-rust/src/p384_32.rs
- fiat-rust/src/p384_64.rs
- fiat-rust/src/p434_64.rs
- fiat-rust/src/p448_solinas_64.rs
- fiat-rust/src/p521_32.rs
- fiat-rust/src/p521_64.rs
- fiat-rust/src/secp256k1_32.rs
- fiat-rust/src/secp256k1_64.rs
- src/RustStringification.v
As the typical integration in a crypto library:
https://github.com/dalek-cryptography/curve25519-dalek/compare/master...calibra:fiat
is using combination of primitives, it makes sense to inline all primitive functions.
Fixes #575.
> Adds inlining for fiat-rust generated functions

- _CoqProject
- src/BoundsPipeline.v
- src/CLI.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/SmallExamples.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
- src/Rewriter/MulSplit.v
- src/Rewriter/PerfTesting/Core.v
- src/RewriterAll.v
- src/RewriterRules.v
- src/RewriterRulesProofs.v
- src/SlowPrimeSynthesisExamples.v
This adds a rewriting pass (disabled by default) which can split apart
multiplications to emit code in a single integer type.
Note that we can emit PHOAS code with only a single integer type, but to
emit C code, we must also allow uint1; see
https://github.com/mit-plv/fiat-crypto/issues/524#issuecomment-529060374
for more details.
We leave it like this because the bedrock2 translation will be coming
from PHOAS.
Note that we must still permit wider integer types during bounds
analysis, because otherwise we'll fail to assign bounds before we even
get to the point of splitting multipliciations.
Note that this rewriting pass is still admitted, so this commit adds a
dependency on an axiom to the overall pass.  (We could create a separate
pipeline if we wanted the code we're extracting to not …
> Add support for splitting multiplication

- src/RewriterReify.v
We won't have easy access to these identifiers when the rewriter is
parameterized over the base types, so we remove them now, for an easy
test of performance differences.
> Don't unfold as much in the rewriter pre-compilation

- .travis.yml
- README.md
- package-rewriter.sh
In preparation for a bedrock2 dependency which only compiles with Coq >=
8.9.  Debian stable (buster) has 8.9, and the newest version of Ubuntu
which has Coq >= 8.8 in fact has Coq 8.9.
We move the testing of v8.8 to v8.10 on travis; when the first release
of 8.10 is actually out, we will add back the test of the latest
released version of 8.10.
> Drop support for Coq 8.8

- curve25519_32.c
- curve25519_64.c
- p224_32.c
- p224_64.c
- p256_32.c
- p256_64.c
- p384_32.c
- p384_64.c
- p434_64.c
- p448_solinas_64.c
- p521_32.c
- p521_64.c
- secp256k1_32.c
- secp256k1_64.c
- src/CastLemmas.v
- src/Fancy/Compiler.v
- src/Language/Pre.v
- src/Stringification/C.v
This is required for dropping the carry in the mul-split addition
rewrite rule.
We also insert a compile-time test into the C code for twos-complement
wrapping behavior.
Question/TODO: Should we insert a test or use, e.g., `Wrapping`, in the
Rust code?
Note that this weakens the guarantee we get from bounds analysis; now
our guarantee is that we perform correctly when doing twos-complement
wrapping on overflow, rather than that we perform correctly regardless
of overflow behavior (as long as it is well-defined).  (@achlipala do you have thoughts/objections?)
Note also that we leave everything parameterized over the now-useless
`cast_outside_of_range` so that we don't have to change large amounts of
code just to support targeting bedrock2.
> Hard-code overflow behavior to be wrapping

- src/AbstractInterpretation/Wf.v
- src/Fancy/Compiler.v
- src/Language/API.v
- src/Language/APINotations.v
- src/Language/Identifier.v
- src/Language/IdentifiersGENERATED.v
- src/Language/IdentifiersGENERATEDProofs.v
- src/Language/IdentifiersGenerate.v
- src/Language/IdentifiersGenerateProofs.v
- src/Language/Pre.v
This results in minor churn in API.v and Fancy/Compiler.v.
Timing diff coming soon.
Next up will probably be removing `cast_out_of_range`, then seeing if I can do reification in a less hand-written way, and then packaging up the tactics for identifiers separately from running them.  After that, I'll probably move all of the identifier inductives to a single file, and then each of the other GENERATED files will just be a single definition with a single tactic call (except I guess there will still be a couple of `Hint Extern`s in the `Identifier` one).  After that is the code to scrape identifiers from a list of rewrite lemmas, and then finally writing the OCaml code.
> Generate most identifier definitions via tactics

- .gitmodules
- .travis.yml
- Makefile
- README.md
- _CoqProject
- etc/ci/travis.sh
- src/Util/ListUtil.v
This is so that we can make fiat-crypto output code in a format that can be consumed by the bedrock2 compiler.
> Add bedrock2 as a submodule

- src/AbstractInterpretation/ZRangeProofs.v
- src/Language/APINotations.v
- src/Language/Identifier.v
- src/Language/IdentifiersGENERATED.v
- src/Language/IdentifiersGenerate.v
- src/Language/Language.v
- src/Language/Pre.v
- src/Rewriter/ProofsCommon.v
On top of #600 
Note that the type of ident_Literal has changed; the type of the second
argument is now more unfolded.  Hopefully this won't slow things down.
We do it this way so that when we eventually move to OCaml code, all of
the identifier inductives can be created without needing to emit
definitions in the middle, and then we can create all the definitions
in one fell swoop with a tactic.
```
After     | File Name                                                       | Before    || Change    | % Change
---------------------------------------------------------------------------------------------------------------
55m48.98s | Total                                                           | 55m44.49s || +0m04.48s | +0.13%
--------------------------------------------------------------- …
```
> Use an auto-generated version of the ident inductive

- src/Language/IdentifierParameters.v
- src/Language/IdentifiersBasicGENERATED.v
- src/Language/IdentifiersBasicGenerate.v
- src/Language/IdentifiersBasicLibrary.v
- src/Language/IdentifiersGENERATED.v
- src/Language/IdentifiersGENERATEDProofs.v
- src/Language/IdentifiersGenerate.v
- src/Language/IdentifiersGenerateProofs.v
- src/Language/IdentifiersLibrary.v
- src/Language/IdentifiersLibraryProofs.v
- src/Language/Pre.v
- src/Rewriter/AllTactics.v
- src/Rewriter/AllTacticsExtra.v
- src/Rewriter/Examples.v
- src/Rewriter/Passes/Arith.v
- src/Rewriter/Passes/ArithWithCasts.v
- src/Rewriter/Passes/MulSplit.v
- src/Rewriter/Passes/NBE.v
- src/Rewriter/Passes/StripLiteralCasts.v
- src/Rewriter/Passes/ToFancy.v
- src/Rewriter/Passes/ToFancyWithCasts.v
- src/Rewriter/ProofsCommon.v
The arguments to the various package making tactics are now carried in
the goal type.  This will make it easier to call the tactics from OCaml.
> Adjust maker tactics to not need arguments

- src/Stringification/C.v
- src/Stringification/IR.v
- src/Stringification/Language.v
- src/Stringification/Rust.v
We now delegate the descriptions of when and where to cast to the
different languages, and let them have custom logic based on the
identifier.
This hopefully makes things a bit cleaner and more obvious, while also
making things more flexible.
> Refactor the stringification and IR code a bit

- src/BoundsPipeline.v
- src/CLI.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/Stringification/C.v
- src/Stringification/IR.v
- src/Stringification/Language.v
- src/Stringification/Rust.v
Note that this doesn't quite work yet; it still produces unused typedefs for unknown reasons, and it doesn't work for to_bytes, failing with the mysterious `Invalid identifier in arithmetic expression Z.zselect`.  But I think it's still worth merging, and I can finish making it work with to_bytes another time.
> Allow widening carry bits

- _CoqProject
- src/Arithmetic/Saturated.v
- src/Arithmetic/WordByWordMontgomery.v
- src/CLI.v
- src/Rewriter/PerfTesting/Core.v
- src/Util/Notations.v
- src/Util/Strings/Ascii.v
- src/Util/Strings/Parse/Common.v
- src/Util/Strings/ParseArithmetic.v
- src/Util/Strings/ParseArithmeticToTaps.v
- src/Util/Strings/String.v
Perhaps it is overkill, but Fiat-Crypto now includes a small parser
combinator library for parsing command-line options.  We can now parse
things like `2^(1.1 * 255) + 0xF + 0o1 + 0b1010.1010 + 2^(255/10)`.
The actual impetus for this change was to allow parsing of lists, to be
used to parse lists of bounds.
> Improve expressivity of parsing

- src/Arithmetic/BarrettReduction.v
- src/Arithmetic/WordByWordMontgomery.v
Explicitly clear useless arithmetic section variables that are eagerly used by zify.
> For temptative Coq PR #11429

- .github/workflows/publish.yml
- AUTHORS
- fiat-rust/AUTHORS
- fiat-rust/Cargo.toml
- fiat-rust/LICENSE
- fiat-rust/README.md
This publishes the fiat-rust crate, under its name/version as declared in the `Cargo.toml` manifest, when the project publishes a [release](https://help.github.com/en/github/administering-a-repository/creating-releases).
This will require:
- creating an account for the project on [crates.io](https://crates.io/), 
- [getting a token](https://crates.io/me) there, 
- [registering it as a secret named `crates_io_token`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets#creating-encrypted-secrets) on this project's Github settings,
Contributes to #647  (minus setup)
> Automatically publish the fiat-rust crate using a release-triggered Github action

- src/AbstractInterpretation/Wf.v
- src/AbstractInterpretation/WfExtra.v
- src/BoundsPipeline.v
- src/Language/UnderLetsProofsExtra.v
- src/Language/WfExtra.v
- src/MiscCompilerPassesProofs.v
- src/MiscCompilerPassesProofsExtra.v
- src/Rewriter/Passes/Arith.v
- src/Rewriter/Passes/ArithWithCasts.v
- src/Rewriter/Passes/MulSplit.v
- src/Rewriter/Passes/NBE.v
- src/Rewriter/Passes/StripLiteralCasts.v
- src/Rewriter/Passes/ToFancy.v
- src/Rewriter/Passes/ToFancyWithCasts.v
Note that we now need to explicitly annotate the `type` argument to the
rewriter passes to ensure that we don't need to unfold `Classes.base
(exprInfo *VerifiedRewriter)`.
<p>
```
After     | File Name                                                       | Before    || Change    | % Change
---------------------------------------------------------------------------------------------------------------
89m59.81s | Total                                                           | 90m54.22s || -0m54.41s | -0.99%
---------------------------------------------------------------------------------------------------------------
0m08.00s  | BoundsPipeline.vo                                               | 0m34.03s  || -0m26.03s | -76.49%
3m47.56s  | …
```
> Be more systematic about opacity

- src/BoundsPipeline.v
- src/CLI.v
- src/CompilersTestCases.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/SmallExamples.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
- src/Rewriter/Passes/Arith.v
- src/Rewriter/Passes/ArithWithCasts.v
- src/Rewriter/Passes/MulSplit.v
- src/Rewriter/Passes/NBE.v
- src/Rewriter/Passes/StripLiteralCasts.v
- src/Rewriter/Passes/ToFancy.v
- src/Rewriter/Passes/ToFancyWithCasts.v
- src/Rewriter/PerfTesting/Core.v
- src/Rewriter/PerfTesting/Specific/to_csv.py
- src/SlowPrimeSynthesisExamples.v
Allow specifying more rewriter options
We can now more easily disable use of pre-reduced constants, and can
also more easily disable use of the decision tree.
Unfortunately the extra arguments make things a bit slower in
PushButtonSynthesis.
<p>
```
After     | File Name                                                       | Before    || Change    | % Change
---------------------------------------------------------------------------------------------------------------
91m02.00s | Total                                                           | 88m48.62s || +2m13.38s | +2.50%
---------------------------------------------------------------------------------------------------------------
0m58.79s  | PushButtonSynthesis/WordByWordMontgomery.vo …
```
> Bump rewriter - Allow specifying more rewriter options

- src/Util/LetIn.v
Previously we were relying on reduction to unfold them.  With the latest
commit in the rewriter, we no longer are.
Timing diff coming soon
> rewriter: Be more robust when there are many lets

- _CoqProject
- src/AbstractInterpretation/AbstractInterpretation.v
- src/AbstractInterpretation/ZRangeProofs.v
- src/BoundsPipeline.v
- src/CLI.v
- src/Language/APINotations.v
- src/Language/IdentifierParameters.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/SmallExamples.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
- src/Rewriter/All.v
- src/Rewriter/Passes/MultiRetSplit.v
- src/Rewriter/PerfTesting/Core.v
- src/Rewriter/Rules.v
- src/Rewriter/RulesProofs.v
- src/SlowPrimeSynthesisExamples.v
- src/Stringification/IR.v
- src/Stringification/Language.v
- src/Util/ZUtil/AddGetCarry.v
- src/Util/ZUtil/Definitions.v
- src/Util/ZUtil/MulSplit.v
e.g., adc, sbb, mulx.  This should make porting to bedrock2 somewhat
easier.
<p>
```
After     | File Name                                                       | Before    || Change    | % Change
---------------------------------------------------------------------------------------------------------------
90m31.83s | Total                                                           | 89m19.85s || +1m11.97s | +1.34%
---------------------------------------------------------------------------------------------------------------
3m48.59s  | fiat-rust/src/p384_32.rs                                        | 4m12.83s  || -0m24.24s | -9.58%
0m21.53s  | Rewriter/Passes/MultiRetSplit.vo                                |    N/A    || +0m21.53s | ∞
2m44.11s  | …
```
> Add support for splitting apart multireturn functions

- src/CLI.v
- src/StandaloneHaskellMain.v
- src/StandaloneOCamlMain.v
This should allow extremely easy adaptation of the binaries to support
bedrock2.  Namely, we just need to inhabit `supported_languagesT := list
(string * ToString.OutputLanguageAPI)` with a list containing
`"bedrock2"` paired with a way of converting PHOAS ASTs to strings, and
then we can do something like
```coq
Require Import Coq.Lists.List.
Require Import Coq.Strings.String.
Require Import Crypto.CLI.
Require Import Crypto.StandaloneOCamlMain.
Require Import Crypto.Bedrock2.Stringification.
Local Open Scope string_scope.
Local Open Scope list_scope.
Local Instance bedrock2_supported_languages : ForExtraction.supported_languagesT
:= ForExtraction.default_supported_languages
++ [("bedrock2", OutputBedrock2API)].
Module UnsaturatedSolinas.
Definition main : unit
:= main_gen …
```
> Parameterize the main functions on supported langs

- src/COperationSpecifications.v
- src/PushButtonSynthesis/Primitives.v
- src/Stringification/C.v
- src/Stringification/Go.v
- src/Stringification/IR.v
- src/Stringification/Java.v
- src/Stringification/Language.v
- src/Stringification/Rust.v
This will let us be more accurate about what bitwidths we need
primitives for, and will also pave the way for possibly allowing cmovznz
to operate on negative integer types
> Use an MSet for int.type directly

- src/Rewriter/Rules.v
They now handle constants in adc/sbb better.  We also split the lists
and reindent a chunk of the arith_with_casts rules, in preparation for
adding a new optimization.  Doing this here will make the new
optimization more obvious.  Note that the change here doesn't actually
change any of the rules used in the C files.
This should help montgomery bedrock2 synthesis.
> Update the multiret rewrite rules

- src/PushButtonSynthesis/BarrettReduction.v
The file now compiles 73% faster
<p>
```
After |   Peak Mem | File Name                               |   Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
------------------------------------------------------------------------------------------------------------------------------------------------
2m22.03s | 1811740 ko | Total Time / Peak Mem                   | 2m38.67s | 1811128 ko || -0m16.64s ||       612 ko |  -10.48% |         +0.03%
------------------------------------------------------------------------------------------------------------------------------------------------
0m05.90s |  857992 ko | PushButtonSynthesis/BarrettReduction.vo | 0m22.43s |  879272 ko || -0m16.53s ||    -21280 ko |  -73.69% | …
```
> Add an optimization in Barrett Reduction

- src/BoundsPipeline.v
- src/Rewriter/Rules.v
This lets us rewrite things like 'x - 0' into 'x'.
This probably makes the BoundsPipeline file a tad bit slower, but I'm not going to bother timing it at this point.
On top of #726.
Edit: It makes BoundsPipeline 2x slower.  Probably we have a quadratic or exponential factor somewhere in proving interp correctness or wf correctness.  Since it's still only 30s to build the file, I'm not going to bother debugging it right now.
<p>
```
After |   Peak Mem | File Name                                       |    Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
----------------------------------------------------------------------------------------------------------------------------------------------------------
38m39.11s | …
```
> Add another rewrite arith pass after mul split

- src/Rewriter/Rules.v
- src/Rewriter/RulesProofs.v
- src/Util/ZUtil/AddGetCarry.v
- src/Util/ZUtil/Modulo.v
- src/Util/ZUtil/Opp.v
As discussed in #686 and #722, the bedrock2 translation was failing on `to_bytes` due to two problems, one of which was adds-with-carry and subs-with-borrow that split on a bit index other than the word size (e.g. `Z.add_with_get_carry (2^51) c x y`). These expressions weren't matching the `split_multiret` rewrite rules and were showing up as assignments to two variables, which bedrock2 doesn't support. This PR fixes that issue by adding new rules that match on non-word-size splits and split the return values.
Since we still lack a bedrock2-expressible transformation for `Z.zselect` (the second problem, which I'll start working on now), generating `to_bytes` still fails. But with many fewer errors than before!
> New rewrite rules for add/sub with carries/borrows (for bedrock2)

- src/AbstractInterpretation/AbstractInterpretation.v
- src/Language/APINotations.v
- src/Language/IdentifierParameters.v
- src/Stringification/IR.v
- src/Stringification/Language.v
Currently bounds analysis only knows how to analyze Z.lxor applied to
constants, but it still can be used in post-bounds-analysis rewrite
rules.
> Add support for Z.lxor

- src/Bedrock/Stringification.v
- src/BoundsPipeline.v
- src/CLI.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/SmallExamples.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
- src/SlowPrimeSynthesisExamples.v
- src/Stringification/C.v
- src/Stringification/Go.v
- src/Stringification/Java.v
- src/Stringification/Language.v
- src/Stringification/Rust.v
This will make bedrock2 32-bit support significantly easier.
Currently the CLI support is a bit messy, because I couldn't decide
whether bitwidth was "owned" by the overall pipeline (in which case it
probably shouldn't show up in the header, or should show up uniformly
with all the other options in the header, like static and some rewriter
options), or whether it's "owned" by individual synthesis pipelines
(like m, s, and c) (which allows it to continue showing up as its own
line in the header, as it currently does).
Probably we should eventually choose the former, but because I haven't
really thought out this design decision at this point, I currently
preserve the way the output files are currently being generated and do
this sort-of mixed support mode.
> Give stringification access to machine_wordsize

- src/Rewriter/Rules.v
- src/Rewriter/RulesProofs.v
We previously only had a rule for the double-width multiplicand on the
left; this commit adds a rewrite rule for having the double-width
multiplicand on the right.  This should allow synthesis of 32-bit
carry_square for bedrock2.
> Deal with splitting 32x64 mul, not just 64x32 mul

- src/Util/Tactics/ETransitivity.v
Coq PR coq/coq#12023 introduces a specific file `Ltac.v` to activate the ltac plugin. This implies a change of qualification of the primitive atomic tactics from `Coq.Init.Notations` to `Coq.Init.Ltac`.
This PR adapts fiat-crypto to the change. I slightly modified the flow of the impacted file so as to be backwards-compatible, but there is a little lost in clarity. So, maybe would you prefer a word-by-word backward-incompatible change.
> Moving names of primitive atomic tactics from Coq.Init.Notations to Coq.Init.Ltac

- _CoqProject
- src/Bedrock/Defaults.v
- src/Bedrock/Defaults32.v
- src/Bedrock/Defaults64.v
- src/Bedrock/Stringification.v
- src/Bedrock/Tests/Proofs/X25519_32.v
- src/Bedrock/Tests/Proofs/X25519_64.v
- src/Bedrock/Tests/X25519_32.v
- src/Bedrock/Tests/X25519_64.v
- src/Bedrock/Util.v
- src/Util/Strings/String.v
This PR:
- separates out the `Bedrock/Defaults.v` file into three files: one for global defaults, one for 32-bit-specific defaults, and one for 64-bit-specific defaults
- creates a 32-bit test in `Bedrock/Tests`
- modifies `Bedrock/Stringification.v` to select the translation parameters based on the word size
Put together, this gives us working 32-bit code from the CLI. I've tested it on all currently supported operations for curve25519 and p256. The changes should make #752 work!
> Add support for 32-bit bedrock2 translations

- src/Bedrock/Tests/Proofs/X25519_32.v
- src/Bedrock/Tests/Proofs/X25519_64.v
- src/Bedrock/Tests/X25519_32.v
- src/Bedrock/Tests/X25519_64.v
As discussed in #757, this change removes the remaining admits in the bedrock2 translation tests with the help of Jason's shiny new `prove_Wf3` tactic (which I can now confirm works beautifully and quickly!) and the existing `PushButtonSynthesis` infrastructure.
Now, when I `Print Assumptions mulmod_bedrock_correct` in the 64-bit test, the only dependencies are:
```
FunctionalExtensionality.functional_extensionality_dep : 
forall (A : Type) (B : A -> Type) (f g : forall x : A, B x),
(forall x : A, f x = g x) -> f = g
SortedListString.TODO_andres : False
used in string_strict_order to prove: SortedList.parameters.strict_order
String.ltb
SortedList.TODO_andres : False
used in map_ok to prove: forall (m : map.rep)
(k k' : SortedList.parameters.key),
k <> k' ->
map.get (map.remove m k') k = …
```
> Instantiate correctness proofs for bedrock2 tests

- _CoqProject
- src/Bedrock/Defaults.v
- src/Bedrock/Defaults32.v
- src/Bedrock/Defaults64.v
- src/Bedrock/Proofs/Expr.v
- src/Bedrock/Proofs/ValidComputable/Expr.v
- src/Bedrock/Translation/Expr.v
- src/BoundsPipeline.v
- src/CLI.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/SmallExamples.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
- src/Rewriter/All.v
- src/Rewriter/Passes/NoSelect.v
- src/Rewriter/PerfTesting/Core.v
- src/Rewriter/Rules.v
- src/Rewriter/RulesProofs.v
- src/SlowPrimeSynthesisExamples.v
- src/Util/ZUtil/Land.v
Closes #750
On top of #760 
Enables translation of zselects by, as discussed in #750, adding a new rewriter pass that translates selects into a bedrock2-expressible form, adding a new CLI flag indicating whether the rewriter pass should be run, and then introducing support for a few new patterns in the bedrock2 backend.
After this is merged and `--no-select` flags are added to the bedrock2 build targets, #733 should work.
> Enable bedrock2 translation for Z.zselect

- .github/workflows/coq-macos.yml
- .github/workflows/coq-windows.yml
- .github/workflows/coq.yml
Discussed with Jason offline. Summary of the conversation: It's been happening frequently that builds fail at the last minute due to failures in the stage when timing info is uploaded, possibly due to the timing info being simply too much data. So we're commenting out those lines to remove some development pain. (This is the cause of the current failure on master.)
See actions/virtual-environments/issues/736
> Comment out uploading-timing-info stage from GH actions

- src/Arithmetic/Core.v
The fix is a priori backward-compatible and can be merged now.
See [coq/coq#12139](https://github.com/coq/coq/issues/12139#issuecomment-622743684) for the motivation as suggested by @JasonGross and supported by @samuelgruetter.
> Adapt to Coq PR #12146: tactic subst now inactive on section variables with indirect dependency in goal

- src/AbstractInterpretation/AbstractInterpretation.v
- src/AbstractInterpretation/Proofs.v
- src/AbstractInterpretation/Wf.v
- src/AbstractInterpretation/WfExtra.v
- src/AbstractInterpretation/ZRange.v
- src/AbstractInterpretation/ZRangeProofs.v
- src/BoundsPipeline.v
- src/CompilersTestCases.v
- src/Language/APINotations.v
- src/Language/IdentifierParameters.v
- src/Language/PreExtra.v
- src/MiscCompilerPasses.v
- src/MiscCompilerPassesProofs.v
- src/MiscCompilerPassesProofsExtra.v
- src/SlowPrimeSynthesisExamples.v
- src/StandaloneHaskellMain.v
- src/Stringification/C.v
- src/Stringification/Go.v
- src/Stringification/IR.v
- src/Stringification/Java.v
- src/Stringification/Language.v
- src/Stringification/Rust.v
After `Import Crypto.Language.PreExtra`, it's now possible to do `dlet _
:= ident.comment stuff in ...` and have `stuff` appear in the
synthesized code as a comment.  There's room for improvement with
regards to quoting and handling multi-line comments, but it works for
debugging purposes.
Note that bounds analysis does not add casts underneath comments, though
I believe let-lifting still happens, and the comments are still
definitely subject to rewriting.
If you want comments whose variable dependencies are eliminated during
the very last dead-code-elimination phase of the stringification
pipeline, use `ident.comment_no_keep`.  Both `ident.comment` and
`ident.comment_no_keep` have type `forall {A}, A -> unit`.
There are now also passes `StripAnnotations` and `StripAllAnnotations`;
the …
> Add support for comments and stripping annotations

- src/PushButtonSynthesis/SaturatedSolinas.v
- src/SlowPrimeSynthesisExamples.v
@andres-erbsen @jadephilipoom Please check that my logic makes sense.  I am basing this on https://github.com/mit-plv/fiat-crypto/issues/776#issuecomment-623043271, and am sort-of guessing here.  (Also, what happens if `i = n - 1`?  What should `nreductions` be in this case?)
> Adjust computation of nreductions

- .github/workflows/rust.yml
- etc/ci/test-fiat-rust-crate-crypto-Ed448-Goldilocks.sh
- etc/ci/test-fiat-rust-curve25519-dalek.sh
As per private correspondence with @kevaundray,
https://github.com/crate-crypto/Ed448-Goldilock now supports a
fiat-crypto backend, so we add it to our CI.
> Test crate-crypto/Ed448-Goldilocks

- src/UnsaturatedSolinasHeuristics.v
Fixes #801 
Tests:
```
Compute @get_possible_limbs (2^448) [(2^224,1); (1,1)] 64. (* [8%nat; 10%nat; 13%nat] *)
Compute @get_possible_limbs (2^448) [(2^224,1); (1,1)] 32. (* [18%nat; 20%nat; 21%nat; 22%nat; 23%nat; 24%nat; 25%nat; 26%nat; 27%nat] *)
Compute @get_possible_limbs (2^480) [(2^240,1); (1,1)] 64. (* [8%nat; 10%nat; 11%nat; 12%nat; 13%nat; 14%nat; 15%nat] *)
Compute @get_possible_limbs (2^480) [(2^240,1); (1,1)] 32. (* [18%nat; 20%nat; 22%nat; 23%nat; 24%nat; 25%nat; 26%nat; 27%nat; 28%nat; 29%nat] *)
Compute @get_possible_limbs (2^192) [(2^64, 1); (1, 1)] 64. (* [4%nat; 5%nat] *)
Compute @get_possible_limbs (2^192) [(2^64, 1); (1, 1)] 64. (* [9%nat; 10%nat; 11%nat] *)
```
> Fix limb count heuristics

- src/Bedrock/Tests/Proofs/X1305_32.v
- src/Bedrock/Tests/Proofs/X25519_32.v
- src/Bedrock/Tests/Proofs/X25519_64.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/UnsaturatedSolinasHeuristics.v
We now compute the loose bounds by recording the number of additions
and/or balanced subtractions we want to be able to do in a row before we
need to multiply and carry.  Note that balanced subtraction always takes
a bit more overhead than addition.
This is a more conservative variant of #799 that doesn't actually change
the bounds, and makes the genuine change of #799 easier to see, namely,
reducing `headspace_add_count` from `2` to `1`.
> Better computation of loose bounds

- src/Arithmetic/Core.v
- src/Bedrock/Interfaces/UnsaturatedSolinas.v
- src/Bedrock/Synthesis/Examples/EncodeDecode.v
- src/Bedrock/Util.v
- src/COperationSpecifications.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/SlowPrimeSynthesisExamples.v
- src/UnsaturatedSolinasHeuristics.v
Very belatedly fixes #468 
When we did the unsaturated version of the core arithmetic library, we created `encode` (which converts a number to limbs by putting the number all in the first digit and then carrying) and also `encode_no_reduce`, which does the same thing except omitting the reduction step in carrying so the number doesn't get reduced mod M. `encode_no_reduce` was only used in a few places, e.g. for bounds, and is easily superseded by the more robust and easy to reason about `partition` definition that we wrote for saturated arithmetic. This PR replaces it with `partition` and uses that replacement to prove a couple of admits I had been waiting on the change for.
Note: this change means `chained_carries_no_reduce` is no longer used in `Core.v` and should probably be moved to …
> encode_no_reduce -> partition

- src/Bedrock/Field/UnsaturatedSolinas.v
- src/Bedrock/Synthesis/Examples/EncodeDecode.v
- src/Bedrock/Synthesis/Examples/LadderStep.v
- src/Bedrock/Synthesis/Examples/MulTwice.v
This simplifies preconditions for placeholder values and helps line up with the standalone specs in rupicola.
> Make Bignum predicate specify length

- src/Bedrock/Field/Operation.v
- src/Bedrock/Field/Tactics.v
- src/Bedrock/Field/UnsaturatedSolinas.v
- src/Bedrock/Proofs/Equivalence.v
- src/Bedrock/Proofs/EquivalenceProperties.v
- src/Bedrock/Proofs/Expr.v
- src/Bedrock/Proofs/Flatten.v
- src/Bedrock/Proofs/Func.v
- src/Bedrock/Proofs/LoadStoreList.v
The bedrock2 backend previously took in two separation-logic statements -- one that framed the input, and one that framed the output. This allowed a caller to, for example, compute `fe_add (x, y)` and store the result in `x`, because the input and output didn't need to use separate memory. Code produced by the bedrock2 backend reads all input arrays into local variables immediately, does its computation, and only then writes output, which is why we don't have to worry about reading the input after writing the output.
However, this structure *also* means that there's no need for the arguments to use separate memory from each other. This PR makes it possible to compute `fe_add(x, x)` and store the result in `x`. Specs in the bedrock2 backend now take one separation-logic statement for each …
> Remove separation requirement for inputs in bedrock2

- src/AbstractInterpretation/AbstractInterpretation.v
- src/AbstractInterpretation/Proofs.v
- src/AbstractInterpretation/Wf.v
- src/BoundsPipeline.v
- src/CompilersTestCases.v
- src/SlowPrimeSynthesisExamples.v
It's now possible to pass in an argument at a higher level specifying
whether or not casts are assumed to truncate.
This should help with
https://github.com/mit-plv/fiat-crypto/issues/833#issuecomment-655088557
> Generalize abstract interpretation over cast assumption

- src/Bedrock/Field/UnsaturatedSolinas.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/UnsaturatedSolinasHeuristics.v
Also add them to a hint db.
They more properly belong in UnsaturatedSolinasHeuristics where the lists are defined in the first place, I think.
> Move some length lemmas to UnsaturatedSolinasHeuristics

- src/Bedrock/Field/Synthesis/Examples/EncodeDecode.v
- src/Bedrock/Field/Synthesis/Examples/LadderStep.v
- src/Bedrock/Field/Synthesis/Examples/MulTwice.v
- src/Bedrock/Field/Synthesis/Generic/Operation.v
- src/Bedrock/Field/Synthesis/Specialized/ReifiedOperation.v
- src/Bedrock/Field/Synthesis/Specialized/UnsaturatedSolinas.v
- src/Bedrock/Field/Synthesis/Specialized/WordByWordMontgomery.v
- src/Bedrock/Field/Translation/Func.v
- src/Bedrock/Field/Translation/Parameters/Defaults.v
- src/Bedrock/Field/Translation/Proofs/Func.v
- src/Bedrock/Standalone/Stringification.v
I previously used a convenience notation to represent the bedrock2 function type (which is a nested tuple of `(string, (list string, list string, cmd.cmd)`, but bedrock2 has now added a `Syntax.func` definition for this purpose and the convenience notation is no longer necessary.
This is a pretty mechanical change, and confined to the bedrock2 backend, so I'll consider myself free to merge it once the CI passes.
> Remove bedrock_func notation

- src/Bedrock/Field/Common/Arrays/MakeAccessSizes.v
- src/Bedrock/Field/Synthesis/Generic/Bignum.v
See discussion in #736 
`coqchk` found four axioms. Two were completely unused and left in by mistake, so they were deleted. The `Bignum_to_bytes` and `Bignum_from_bytes` lemmas are currently unused but possibly could be useful once stack allocation is incorporated, so I've commented them out for now.
> Remove unused axioms from bedrock2 backend

- .github/workflows/coq-windows.yml
- .github/workflows/json.yml
- Makefile
- _CoqProject
- fiat-json/src/README.md
- fiat-json/src/curve25519_32.json
- fiat-json/src/curve25519_64.json
- fiat-json/src/p224_32.json
- fiat-json/src/p224_64.json
- fiat-json/src/p256_32.json
- fiat-json/src/p256_64.json
- fiat-json/src/p384_32.json
- fiat-json/src/p384_64.json
- fiat-json/src/p434_64.json
- fiat-json/src/p448_solinas_32.json
- fiat-json/src/p448_solinas_64.json
- fiat-json/src/p521_64.json
- fiat-json/src/poly1305_32.json
- fiat-json/src/poly1305_64.json
- fiat-json/src/secp256k1_32.json
- fiat-json/src/secp256k1_64.json
- src/CLI.v
- src/Stringification/JSON.v
Note that we need to keep the individual lines of each function separate
so as to not stack-overflow when joining strings before printing,
because JSON has many, many more lines than most of the other languages.
> Add a JSON output format

- src/Rewriter/PerfTesting/StandaloneOCamlMain.v
- src/StandaloneHaskellMain.v
- src/StandaloneOCamlMain.v
We provide dummy definitions locked inside opaque modules rather than
using axioms for constants to be extracted as stateful primitives.
Since all we care about with coqchk is that we cannot prove False, it
does not really matter if the model we provide for these constants does
not match their semantics. We only use them for interaction with the
system in any case.
This will make progress towards #736
@andres-erbsen , does this seem okay to you?
> Play some tricks to remove axioms from coqchk

- README.md
Apparently, the package `ocamlfind` has been renamed to `ocaml-findlib`
Added convenience cmd lines to install the required dependencies.
(Checked package names in brew / pacman and apt package-lists)
> Added info on dependencies package

- src/Bedrock/Field/Interface/Compilation.v
- src/Bedrock/Field/Interface/Representation.v
- src/Bedrock/Group/Point.v
- src/Bedrock/Group/ScalarMult/LadderStep.v
- src/Bedrock/Group/ScalarMult/MontgomeryLadder.v
- src/Bedrock/Specs/Field.v
- src/Bedrock/Specs/Group.v
- src/Bedrock/Specs/ScalarField.v
On top of #869 
Uses fiat-crypto's F datatype from `PrimeFieldTheorems` to represent field elements. This removes all the messing around with `Z.modulo` and makes the definition of Montgomery ladder functions easier and closer to the original ones from `Curves/Montgomery/XZ.v`.
@andres-erbsen Do you think this is a good idea, or should I stick with the version from #869?
> Use F for bedrock2 field specs

- _CoqProject
- src/Algebra/Nsatz.v
- src/Algebra/NsatzTactic.v
By copying over the implementation of nsatz, we can drop the
dependencies on the real axioms.  Together with
https://github.com/coq/coq/issues/12845, this should eliminate the last
axioms reported by coqchk, allowing us to be done with #736 (maybe
modulo adding a CI job to check that no axioms creep back in).
Not clear to me if this is worth it...
@andres-erbsen Do you think this is worth merging if it builds on all the versions of Coq that we care about?
> Remove dependencies on the real numbers

- _CoqProject
- src/Bedrock/Field/Common/Util.v
- src/Bedrock/Field/Interface/Compilation.v
- src/Bedrock/Field/Interface/Representation.v
- src/Bedrock/Field/Synthesis/Generic/Bignum.v
- src/Bedrock/Group/Loops.v
- src/Bedrock/Group/ScalarMult/LadderStep.v
- src/Bedrock/Group/ScalarMult/MontgomeryEquivalence.v
- src/Bedrock/Group/ScalarMult/MontgomeryLadder.v
- src/Bedrock/Group/ScalarMult/ScalarMult.v
- src/Bedrock/Specs/Field.v
- src/Bedrock/Specs/Group.v
- src/Bedrock/Specs/ScalarField.v
- src/Util/Loops.v
In terms of the "next steps" discussion on #869, this PR is the second bulletpoint :
> - proving that the ladderstep and montladder Gallina implementations match the Gallina implementations from `Curves/Montgomery/XZ.v` so we can use the proofs from `XZProofs` to say that montgomery ladder is a group scalarmult
The punchline here is `scmul_func_correct`, which goes through `XZProofs` to prove that a bedrock2 implementation of group scalar multiplication corresponds to the specification in `Bedrock/Specs/Group.v`, where the group is instantiated with a Montgomery curve. `Print Assumptions` tells me it's closed under the global context, and `Check`ing it shows the following:
```coq
M.scmul_func_correct
: forall char_ge_3 : Ring.char_ge 3,
Ring.char_ge 5 ->
Ring.char_ge 12 ->
Ring.char_ge 28 …
```
> Connect bedrock2 montladder with algebraic scalarmult

- COPYRIGHT
- LICENSE-APACHE
- LICENSE-BSD-1
- LICENSE-MIT
- Makefile
- README.md
- fiat-rust/COPYRIGHT
- fiat-rust/Cargo.toml
- fiat-rust/LICENSE-APACHE
- fiat-rust/LICENSE-BSD-1
- fiat-rust/LICENSE-MIT
- fiat-rust/README.md
Hopefully this will satisfy the Go team and might come closer to getting
us into OpenSSL.
We follow
https://github.com/rust-lang/rust/tree/e0bc267512fc0cb49c86978192857e8187017f0b#license
and
https://github.com/rust-lang/rust/blob/e0bc267512fc0cb49c86978192857e8187017f0b/COPYRIGHT
for wording.
Got out-of-band approval from all the people (and representatives of all the companies) in `AUTHORS`.  Please review for whether the way I'm laying things out seems good.
> Multi-license under MIT OR Apache-2.0 OR BSD-1-Clause

- Makefile
- _CoqProject
- output-tests/Crypto.Bedrock.Group.ScalarMult.LadderStep.ladderstep_body.expected
- output-tests/Crypto.Bedrock.Group.ScalarMult.MontgomeryLadder.montladder_body.expected
- src/Bedrock/Field/Common/Arrays/MakeAccessSizes.v
- src/Bedrock/Field/Interface/Compilation.v
- src/Bedrock/Group/ScalarMult/LadderStep.v
- src/Bedrock/Group/ScalarMult/MontgomeryLadder.v
- src/Bedrock/Group/ScalarMult/ScalarMult.v
- src/Bedrock/ScalarField/Interface/Compilation.v
- src/Bedrock/Specs/Field.v
- src/Bedrock/Specs/Group.v
- src/Bedrock/Specs/ScalarField.v
This is part of my work-in-progress on connecting the bedrock2 backend to the new field specifications and scalarmult implementation. Mainly, this change:
- moves the scalar field compilation lemmas to a new `ScalarField/` directory, so that the structure matches `Field/` and `Group/` and doesn't clutter the spec with non-trusted code
- changes the argument order for field operations so that the output pointer comes first instead of last, to match BoringSSL and the existing bedrock2 backend implementations
- introduces a separate separation-logic frame for each input instead of one for all inputs, because it should be okay to call `add(out, x, x)` (see #828)
> Clean up field specifications

- src/AbstractInterpretation/Wf.v
- src/Bedrock/Field/Translation/Cmd.v
- src/Bedrock/Field/Translation/Expr.v
- src/Bedrock/Field/Translation/Proofs/Cmd.v
This allows things like `fun (x y : Z) => (x, y)` and `fun (x y : Z) (z
: list Z) => (x, y, z)` to synthesize correctly.  This fixes #886 and is partial work towards making bedrock2 output handle divstep.
> Make translate_cmd handle pairs

- src/Bedrock/Field/Translation/Expr.v
- src/Bedrock/Field/Translation/Proofs/Expr.v
- src/Bedrock/Field/Translation/Proofs/ValidComputable/Expr.v
On top of #889 
Resolves #888
- Adds `lnot_modulo` to the computable version of `valid_expr` (`valid_expr_bool`)
- Resolves an overdue TODO by changing the ugly ad-hoc boolean flags in one of the `valid_expr_bool` internal functions into an enum
> Add lnot_modulo to computable validity checker

- src/Arithmetic/Core.v
- src/Arithmetic/MontgomeryReduction/WordByWord/Abstract/Dependent/Definition.v
- src/Arithmetic/MontgomeryReduction/WordByWord/Abstract/Dependent/Proofs.v
- src/Arithmetic/Saturated/AddSub.v
- src/Arithmetic/Saturated/Core.v
- src/Arithmetic/Saturated/MulSplit.v
- src/Compilers/Eta.v
- src/Compilers/EtaInterp.v
- src/Compilers/EtaWf.v
- src/Compilers/Inline.v
- src/Experiments/PartialEvaluationWithLetIn.v
- src/Util/Loops.v
Implicit arguments in `Context` were discarded. Coq PR [#11390](https://github.com/coq/coq/pull/11390) preserves them. The present PR adapts fiat-crypto to the new semantics.
There were several places in fiat-crypto using implicit arguments in `Context`. Depending on whether it looked intended or not that they were there, or depending on how easy it was to adapt to a change, I sometimes removed the implicit arguments and sometimes preserve them.
As a result, the PR is backward-incompatible and has to merged synchronously with coq/coq#11390. If you'd prefer a backward-compatible change, the implicit arguments should instead be removed in the few places where it has an impact.
>  Adapt to fixing dropped implicit arguments in Context

- src/Util/WordUtil.v
PR coq/coq#13568 detected that an invalid occurrence was tacitly accepted by a call to `rewrite`. This fiat-crypto PR removes it so that fiat-crypto-legacy is successful on Coq CI.
This is a backward-compatible change that can be merged as soon as now.
> Remove an invalid "at" occurrence of "rewrite"

- Makefile
- fiat-c/src/curve25519_64.c
- fiat-c/src/p224_64.c
- fiat-c/src/p256_64.c
- fiat-c/src/p384_64.c
- fiat-c/src/p434_64.c
- fiat-c/src/p448_solinas_32.c
- fiat-c/src/p448_solinas_64.c
- fiat-c/src/p521_64.c
- fiat-c/src/poly1305_64.c
- fiat-c/src/secp256k1_64.c
- src/Stringification/C.v
This allows the generated C code to compile with gcc and -Wpedantic.
Suggested in #820 by @chjj
> C Stringification: prepend __extension__ before the typedef with __int128

- src/Algebra/Ring.v
- src/Arithmetic/Core.v
- src/Bedrock/Field/Translation/Proofs/EquivalenceProperties.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/UnsaturatedSolinasReificationCache.v
- src/PushButtonSynthesis/WordByWordMontgomeryReificationCache.v
- src/Util/Bool.v
- src/Util/Bool/Reflect.v
- src/Util/Decidable.v
- src/Util/Decidable/Bool2Prop.v
- src/Util/FixCoqMistakes.v
- src/Util/LetIn.v
- src/Util/LetInMonad.v
- src/Util/ListUtil.v
- src/Util/NatUtil.v
- src/Util/PER.v
- src/Util/PointedProp.v
- src/Util/PrimitiveProd.v
- src/Util/Prod.v
- src/Util/Tactics/DebugPrint.v
- src/Util/ZUtil/Hints.v
- src/Util/ZUtil/Hints/Core.v
- src/Util/ZUtil/Hints/ZArith.v
- src/Util/ZUtil/Stabilization.v
Starting off from
```
git grep --name-only '^Hint \(Resolve\|Extern\)' | xargs sed -i 's/^Hint \(Resolve\|Extern\)/Global Hint \1/g'
```
> Globalize Hints to suppress warning on Coq master

- src/Assembly/Parse.v
- src/BoundsPipeline.v
- src/CLI.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/SmallExamples.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
- src/Rewriter/PerfTesting/Core.v
- src/SlowPrimeSynthesisExamples.v
- src/StandaloneHaskellMain.v
- src/StandaloneOCamlMain.v
We now support the `--hints-file` and `--output-asm` arguments (both
unused) and the `--output` / `-o` argument.  The first two are initial
support for interacting with assembly hint files, though we don't
currently do anything with the arguments other than opening and reading
the files, and parsing the assembly.
cc @andres-erbsen, the relevant entry point is the function `Synthesize` at the bottom of `Primitives.v`.
> Add support for interaction with files

- src/Util/Tactics/TransparentAssert.v
Use `simple notypeclasses refine` in `transparent assert`.
See
https://github.com/mit-plv/rewriter/commit/ce996ca8e48022221dda7c092d5a05f193da2e96
The `notypeclasses` behavior is the one we want; even if the type is a
typeclass, we want to leave over the corresponding goal.
> notypeclasses in transparent assert

- .github/workflows/coq.yml
- src/Bedrock/Field/Translation/Parameters/Defaults.v
There were still some uses of `omega`.  This should hopefully actually
eliminate all uses of omega, making fiat-crypto compatible with
https://github.com/coq/coq/pull/13741
> Bump bedrock2 via rupicola again

- src/Util/ZUtil/Log2.v
this PR replaces a call to `auto with zarith` by `auto`.
> compatibility with coq PR #14045

- src/Arithmetic/BarrettReduction.v
replace rewrite! by rewrite?
For some reason, it is now redundant.
> compatibility with coq PR #14045 (again)

- .github/workflows/coq.yml
Also bump Coq to 8.13.1
This is a somewhat inefficient way to test more versions of OCaml, but I
want information on if the version of OCaml has any impact on the
compilation time of the extracted binaries, a la
https://github.com/ocaml/ocaml/issues/7826 and in particular
https://github.com/ocaml/ocaml/issues/7826#issuecomment-625342743
> Test more versions of OCaml

- etc/ci/test-fiat-rust-curve25519-dalek.sh
- this uses the Dalek upstream repository to run backend tests, rather than the Novi fork used previously.
- this tests the 32-bit backend as well as the 64 bit backend.
/cc @isislovecruft for awareness of extent of backend tests running here.
> run Dalek-crypto backend tests more directly

- src/AbstractInterpretation/AbstractInterpretation.v
- src/AbstractInterpretation/Proofs.v
- src/AbstractInterpretation/Wf.v
- src/Bedrock/Field/Synthesis/Generic/Operation.v
- src/Bedrock/Field/Synthesis/Specialized/ReifiedOperation.v
- src/Bedrock/Field/Synthesis/Specialized/UnsaturatedSolinas.v
- src/Bedrock/Field/Synthesis/Specialized/WordByWordMontgomery.v
- src/Bedrock/Field/Translation/Proofs/Func.v
- src/BoundsPipeline.v
- src/Language/WfExtra.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
Now that I've managed to prove `Wf3 <-> Wf`, we can make use of it to
hide `Wf3` requirements from APIs of PHOAS passes.  Moreover, now that
we're just using `Wf`, we expose the `Wf` proofs of the various
synthesized operations, so that we can use them in the Bedrock2 backend
without having to re-prove `Wf3` from scratch.
Timing info coming soon.
Unfortunately my pushes to the rewriter broke fiat-crypto on Coq's CI, so I'm going to merge this as soon as the timing info is in and the CI passes.  @jadephilipoom , please take a look at the changes to the Bedrock files here, and let me know what you think.  If you want me to make the necessary changes to #944, I'm happy to take point on doing that.
<p>
```
After |   Peak Mem | File Name …
```
> Replace `Wf3` with `Wf` in most places

- .github/workflows/coq.yml
We now have a job that explicitly builds with the standard (non-ppa)
distributed version of Coq on Ubuntu LTS.
> Test on the CI that we work with Ubuntu LTS

- README.md
The first bits of Fiat-generated code have landed into the Zig standard library.
The code is now continuously tested on all supported platforms.
> Zig Fiat-Crypto-generated code is now continuously tested

- src/UnsaturatedSolinasHeuristics.v
We encode `2^Z.log2_up(s-c)-1` rather than `s-1` for cases when `c` is
negative.  We can't actually handle `c < 0` due to the preconditions for
`freeze`, but this brings us a step closer.
See #960
> Use a more flexible encoding for tight upperbounds

- fiat-zig/src/main.zig
- inversion/zig/inversion.zig
A breaking change was just introduced in the Zig testing framework.
This updates the Zig tests for it.
> Update Zig tests after std.testing.* changes

- src/AbstractInterpretation/ZRange.v
- src/Language/APINotations.v
- src/Util/Bool/Reflect.v
- src/Util/ListUtil.v
- src/Util/Option.v
- src/Util/Prod.v
This is in preparation for having typedefs based on bounds info.
If this passes CI, then we can merge mit-plv/rewriter#28.
> Switch to a heterogenous `base_interp_beq`

- .github/workflows/coq.yml
- src/haskell.sed
Mainly to silence warnings/annotations.
Also switch from an unmaintained action to a maintained one.
> Switch to latest version of Haskell and Cabal 

- fiat-zig/src/curve25519_32.zig
- fiat-zig/src/curve25519_64.zig
- fiat-zig/src/p224_32.zig
- fiat-zig/src/p224_64.zig
- fiat-zig/src/p256_32.zig
- fiat-zig/src/p256_64.zig
- fiat-zig/src/p384_32.zig
- fiat-zig/src/p384_64.zig
- fiat-zig/src/p434_64.zig
- fiat-zig/src/p448_solinas_32.zig
- fiat-zig/src/p448_solinas_64.zig
- fiat-zig/src/p521_64.zig
- fiat-zig/src/poly1305_32.zig
- fiat-zig/src/poly1305_64.zig
- fiat-zig/src/secp256k1_32.zig
- fiat-zig/src/secp256k1_64.zig
- src/Stringification/Zig.v
Both are equivalent, but the former is now preferred.
No functional changes.
> Zig backend: favor "inline fn" over "fn ... callconv(.Inline)"

- fiat-zig/src/curve25519_32.zig
- fiat-zig/src/curve25519_64.zig
- fiat-zig/src/p224_32.zig
- fiat-zig/src/p224_64.zig
- fiat-zig/src/p256_32.zig
- fiat-zig/src/p256_64.zig
- fiat-zig/src/p384_32.zig
- fiat-zig/src/p384_64.zig
- fiat-zig/src/p434_64.zig
- fiat-zig/src/p448_solinas_32.zig
- fiat-zig/src/p448_solinas_64.zig
- fiat-zig/src/p521_64.zig
- fiat-zig/src/poly1305_32.zig
- fiat-zig/src/poly1305_64.zig
- fiat-zig/src/secp256k1_32.zig
- fiat-zig/src/secp256k1_64.zig
- src/Stringification/Zig.v
Unsafe C-like casts have been removed from the language (or, rather, moved to a dark corner).
So, include code to emulate them by upcasting or downcasting at compile time according to the source and target bit sizes.
> Zig: emulate unsafe casts

- Makefile
This applies @JasonGross' suggestion at [#14596](https://github.com/coq/coq/pull/14596#issuecomment-875564320).
This is backward-compatible and can be merged as soon as now.
> Remove the Arguments line from the tested output of Print

- src/Algebra/Ring.v
@JasonGross  I moved Ncring_Ring instance at the top, to simply some of your proofs [1]. 
[1] https://coq.inria.fr/library/Coq.setoid_ring.Ncring.html
> Moved Ncring_Ring instance at the top, to simplify few proofs

- src/AbstractInterpretation/AbstractInterpretation.v
- src/AbstractInterpretation/Proofs.v
- src/AbstractInterpretation/Wf.v
- src/AbstractInterpretation/ZRange.v
- src/AbstractInterpretation/ZRangeProofs.v
- src/Bedrock/Field/Stringification/Stringification.v
- src/Bedrock/Field/Translation/Parameters/Defaults.v
- src/BoundsPipeline.v
- src/CLI.v
- src/CompilersTestCases.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/SmallExamples.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
- src/Rewriter/PerfTesting/Core.v
- src/SlowPrimeSynthesisExamples.v
- src/Stringification/C.v
- src/Stringification/Go.v
- src/Stringification/IR.v
- src/Stringification/JSON.v
- src/Stringification/Java.v
- src/Stringification/Language.v
- src/Stringification/Rust.v
- src/Stringification/Zig.v
We now default to avoiding uint1 in the result of `>>` operations, as
per
https://github.com/mit-plv/fiat-crypto/pull/1015#discussion_r708691741.
This is required for making symbolic equivalence checking with assembly
go through.  It might be possible to improve the symbolic equivalence
checker to know enough about bounds analysis (or to also do bounds
analysis) so that this is not necessary?
> Add `--no-shiftr-avoid-uint1`

- src/Arithmetic/Saturated/UniformWeight.v
- src/Experiments/SimplyTypedArithmetic.v
> [legacy] Adapt to coq/coq#13837 ("apply with" does not rename arguments)

- src/BoundsPipeline.v
- src/CLI.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/SmallExamples.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
- src/Rewriter/PerfTesting/Core.v
- src/SlowPrimeSynthesisExamples.v
Don't unconditionally ignore mismatch between the name of the assembly function and the name of the synthesized function.
@andres-erbsen Does making this a command-line flag seem reasonable to you (under the presumption that sometimes we might want to be warned if we're using the wrong assembly file, and also that we should be in strict mode by default to catch such mistakes earlier)?  Does the name seem fine?
>  Add `--asm-ignore-unique-name-mismatch`

- src/Compilers/InterpRewriting.v
Should be backwards compatible, but let's check the result on the other PR first.
> Adapt w.r.t. coq/coq#15178.

- fiat-amd64/8917_ratio11077_seed3401074160038646_sub_p224.asm
- src/Assembly/Symbolic.v
Supercedes and closes #1049
I got nerdsniped and wrote the rewrite rule myself.
The first commit of this PR is a reorganization of the associative-commutative machinery for operations, making more operations associative and commutative.  I tried to minimize the number of proofs in which we destruct the operation.  I decided on the following:
For an operation with identity, the spec is that if `identity o = Some id`, then:
- `interp_op G o xs = interp_op G o (List.filter (fun v => negb (v =? id)) xs)`
- `interp_op G o [] = Some id`
For an associative operation, the spec is:
- `interp_op G o xs = fold_right (fun v acc => acc <- acc; interp_op G o [v; acc])%option (interp_op G o []) xs`
- `interp_op G o [] = identity o`
- `interp_op G o ys = Some vys -> interp_op G o zs = Some vzs ->((xy <- …
> Add support for folding constants into and

- .github/workflows/coq.yml
- src/haskell.sed
Unlike #1048, we don't test on Haskell 9.2.1, because we still have a heap overflow.  But we can at least pass typechecking, so here we do.
> Partial compatibility with Haskell 9.2.1

- .github/workflows/coq.yml
This allows PR authors to not have to run the updating locally
> Upload generated files on failure

- .github/workflows/coq-windows.yml
- .github/workflows/coq.yml
For #1076; I am not sure whether still runs more versions on master or not but I think yes?
Tested versions:
- coq master from Jason's PPA
- 8.14.0 on Mac OS
- 8.12.0 on Windows, matching debian and fast ubuntu
- ubuntu lts coq package
> Representative CI

- fiat-rust/Cargo.toml
- fiat-rust/src/lib.rs
Adds `#![cfg_attr(not(feature = "std"), no_std)]` to the Rust library,
as suggested in https://github.com/mit-plv/fiat-crypto/issues/1067
Fixes #1067
@vlmutolo @brycx Does this look good?
> [rust] Add conditional `no_std` to Cargo.toml

- fiat-rust/src/curve25519_32.rs
- fiat-rust/src/curve25519_64.rs
- fiat-rust/src/p224_32.rs
- fiat-rust/src/p224_64.rs
- fiat-rust/src/p256_32.rs
- fiat-rust/src/p256_64.rs
- fiat-rust/src/p384_32.rs
- fiat-rust/src/p384_64.rs
- fiat-rust/src/p434_64.rs
- fiat-rust/src/p448_solinas_32.rs
- fiat-rust/src/p448_solinas_64.rs
- fiat-rust/src/p521_64.rs
- fiat-rust/src/poly1305_32.rs
- fiat-rust/src/poly1305_64.rs
- fiat-rust/src/secp256k1_32.rs
- fiat-rust/src/secp256k1_64.rs
- src/Stringification/Rust.v
Changes `allow(non_camel_case_types)` to be inner attribute, instead of outer. Before this, it only applied to the item immediately after declaration (all items thereafter generated warnings). Inner attributes are instead module-level.
> `allow(non_camel_case_types)` should be inner attribute

- _CoqProject
- src/Arithmetic/FLia.v
- src/Bedrock/Group/AdditionChains.v
Moves the `F_lia` tactic out of AdditionChains.v and replaces the outdated `F_lia_orig` tactic with calls to `F_lia`.
> Separate F_lia

- .github/workflows/coq-macos.yml
- .github/workflows/coq-opam-package.yml
- .github/workflows/coq-windows.yml
Since opam 2.1, depext is integrated in install, so we try disabling it.
See https://opam.ocaml.org/blog/opam-2-1-0/
> Attempt to fix windows build

- src/Stringification/Language.v
Hi,
The fixpoint `show_expr_lines_gen` in file `Stringification/Language.v` has the following form once the helpers it depends on are unfolded:
```coq
Fixpoint show_expr_lines_gen ... e ... :=
match e with
| expr.Abs s d f =>
fix show_eta_abs_cps' ... e ... :=
match e with
| expr.Abs s d f => ψ (show_eta_abs_cps' ... f ...)
| _ => show_expr_lines_gen ... e ...
end (expr.Abs s d f)
| _ => ...
end
```
This includes in the default case of `show_eta_abs_cps'` an erasable recursive call to `show_expr_lines_gen` which is not guarded and which thus may loop for a specific reduction strategy that unfolds `show_eta_abs_cps'` one step, then reduces the expression in the default case of the `match (expr.Abs s d f) with  ... end` before contracting the `match` itself. PR coq/coq#15434 forbids it. …
> Adapt to Coq PR #15434: even erasable subterms of fixpoints must be guarded

- src/CLI.v
I believe this is more in keeping with standard practice, also backed up
by https://unix.stackexchange.com/questions/222372/the-precedence-of-command-options#comment377754_222378
> [CLI] Give precedence to the final argument on the command-line

- src/Assembly/Equivalence.v
- src/Assembly/Symbolic.v
- src/Assembly/WithBedrock/Proofs.v
- src/CLI.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
Also check a couple of other sanity conditions in the equivalence
checker
@andres-erbsen I decided to allow both MS and System V conventions to be passed by name.  Feel free to review any part of this that you want; I plan to merge once CI passes
> Add support for checking callee-saved registers

- src/StandaloneOCamlMain.v
- src/Util/Strings/String.v
Unfortunately, `List.rev` is quadratic in the length of the list.  This
is a bottleneck in some generated code, so we use the linear-time
`List.rev_append _ []`.
<p>
```
After |   Peak Mem | File Name                                                   |     Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
97m13.31s | 2628008 ko | Total Time / Peak Mem                                       | 100m32.50s | 2631112 ko || -3m19.19s ||     -3104 ko |   -3.30% |         -0.11%
------------------------------------------------------------------------------------------ …
```
> `List.rev l` -> `List.rev_append l []`

- src/Assembly/WithBedrock/Proofs.v
- src/Assembly/WithBedrock/SymbolicProofs.v
Only two subgoals remain:
```coq
R_runtime_output frame runtime_rets
(type_spec_of_runtime (word_args_to_Z_args word_runtime_inputs))
(Datatypes.length x) stack_base asm_args_out asm_args_in callee_saved_registers
runtime_callee_saved_registers m'
```
and
```coq
R
(frame ⋆ R_list_scalar_or_array x0 asm_args_out
⋆ R_list_scalar_or_array (word_args_to_Z_args word_runtime_inputs)
asm_args_in ⋆ array cell64 (word.of_Z 8) stack_base x)%sep x1
(update_dag_with (init_symbolic_state d) (fun _ : dag => d0)) m
->
R_mem frame G_final dag_state1
(rev (List.combine x4 x5) ++
rev
(flat_map
(fun pat : (idx + idx * list idx) * (idx + list idx) =>
match pat with
| (inl _, _) => []
| (inr (_, addrs'), inl _) => []
| (inr (_, addrs'), inr items) => List.combine addrs' items
end) (List.combine x3 (l4 ++ …
```
> More assembly equivalence WIP

- _CoqProject
- src/Assembly/Equivalence.v
- src/Util/ListUtil/FilterN.v
- src/Util/ListUtil/RemoveN.v
Should give a better error message for https://github.com/mit-plv/fiat-crypto/pull/1123#issuecomment-1034554480
> Report equiv errors modulo commutativity

- src/Assembly/WithBedrock/Proofs.v
What remains is doing the reverse of the final symex goal to deal with
the different representations of memory specs, splitting apart input and
output values via `++` (not 100% sure how to do this yet), and showing
that the outputs are mapped to the right values (also need to figure out
how to do this).
on top of https://github.com/mit-plv/fiat-crypto/pull/1116
> Finish proving/using that SymexLines scribles only over known memory

- _CoqProject
- src/Assembly/Equivalence.v
- src/Assembly/EquivalenceProofs.v
- src/Assembly/WithBedrock/Proofs.v
- src/Util/Tactics.v
- src/Util/Tactics/RevertUntil.v
This will allow us to reuse the same code to load inputs and outputs,
when we want to enforce the spec of reading back and removing all of the
values and then saying that the resulting symbolic memory state is
empty.
Some of the proofs are not quite as complete as they were before, but I
hope to replace them soon with a more principled approach.
@andres-erbsen You might be interested in this change (this paves the way for returning scalars either in registers or by way of pointers; we could plausibly turn this into a list of bools if desired).
> Parameterize over dereference_scalar in more places

- src/Assembly/Symbolic.v
Depth determines which indices get expanded, but all references to the
same index get expanded if they appear in the output.
This is because Joel's latest examples require a rewriting pass that
needs either uneven revealing or the ability to check expression
equality modulo the dag in the middle of rewriting.
https://github.com/mit-plv/fiat-crypto/pull/1134#issuecomment-1075320548
Roughly the issue is that if we want to turn `a + 4 * a` into `5 * a`,
we need to reveal enough structure to see `4 * a`, but we need to see
that the two instances of `a` are the same (e.g., if `a` is an ExprRef
pointing to `b|c`, and we reveal uniformly, then we need to recognize
`b|c + 4 * a`)
> Add reveal_at_least, a more clever form of reveal

- fiat-amd64/16232_ratio11549_seed1785685356_square_poly1305.asm
- fiat-amd64/9789_ratio10114_seed1785685356_square_curve25519.asm
this is the PR split from #1123.
I do get an Error in `Parse.v` 
File "./src/Assembly/Parse.v", line 190, characters 129-130:
Error: Syntax error: [term level 70] expected after ';;R' (in [term]).
which I don't understand. Generally, I think I need some feedback on what I am trying to do. I just can't get the syntax right with `(Z * REG)`
Edit: I skipped the Bedrock files for now, because I want to get the others compile correct first.
> Mem extention

- .github/workflows/coq-windows.yml
- src/Assembly/Equivalence.v
- src/Assembly/EquivalenceProofs.v
- src/Assembly/Symbolic.v
- src/Assembly/WithBedrock/Proofs.v
This gets us almost all the way to the end of the proof.
The primary remaining issue is the fact that the current spec constrains
the registers holding the input and output values to not change across
the proof.  We need to rework how we're handling registers in the spec a
bit.
After chatting with @andres-erbsen , the way to spec these is to add asm_in/out
arguments that track only the arrays, and have these be the arguments
that are passed to both inputs and outputs.  Then both the inputs and
the outputs can mandate that there exist asm_in/out arguments which also
apply to scalar arguments, and spec the rest in terms of these.
<p>
```
After |   Peak Mem | File Name …
```
> Rework equivalence checker proofs to be based on remove

- src/Assembly/WithBedrock/Proofs.v
- src/Util/ListUtil/Filter.v
The proof is slow and horrible due to my attempts to make it a bit less
slow, because there's no systematicness to the chaining of `Forall` and
`Forall2` implications, and it's way too slow to use the straightfoward
brute force approach.  But it's done!
It takes 287.14s on my laptop to run this file.  Interestingly, this is actually nearly 2 minutes faster than it previously took, maybe due to `Qed` doing less work than `Admitted`? (cf https://github.com/coq/coq/pull/15860)
<p>
```
After |   Peak Mem | File Name                      |   Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
--------------------------------------------------------------------------------------------------------------------------------------- …
```
> Finish assembly equivalence checker proof

- Makefile
- fiat-amd64/gentest.py
- src/StandaloneHaskellMain.v
Also make only-test-amd64-files actually not rebuild/depend on the
binaries, and make Haskell error messages line up with OCaml ones
(always printed to stdout).
> Add support for TIMED=1 in make test-amd64-files

- src/Assembly/Equivalence.v
- src/Assembly/EquivalenceProofs.v
- src/Assembly/Symbolic.v
- src/Assembly/WithBedrock/Proofs.v
- src/Assembly/WithBedrock/SymbolicProofs.v
- src/BoundsPipeline.v
The dag now prints out where some indices came from, and assembly lines
generating values that don't exist in PHOAS are annotated with the dag
indices they generate.
We also pave the way to display information about indices that appear
only in the assembly and not in the PHOAS.  I'm not sure what the right strategy here is.
One idea:
When we transition from an inequality that contains indices appearing only in assembly to an inequality containing indices that appear in both, recursively expand all indices appearing only in asm
Edit: performance is pretty terrible:
<details><summary>Timing Diff since <a href="https://github.com/JasonGross/fiat-crypto/commit/831d6114a2c4b13b51c5985a48185c7bd2d5a3a8">831d6114a2c4b13b51c5985a48185c7bd2d5a3a8</a></summary>
<p>
```
After |  Peak Mem | File Name …
```
> Better equivalence-checker error messages

- src/Assembly/Parse.v
- src/BoundsPipeline.v
- src/PushButtonSynthesis/Primitives.v
- src/Util/Strings/ParseArithmetic.v
We now correctly show `repz ret`, support `0F3h` parsing for hex values (`h` suffix is currently case-sensitive), and give better error messages for unused labels, mentioning which hints file they came from.
> Minor asm improvements

- src/Bedrock/End2End/RupicolaCrypto/Low.v
- src/Bedrock/End2End/RupicolaCrypto/Spec.v
Revert "Prove compilation lemma for memcpy. TODO: needs cleanup"
This reverts commit cb6a5f7621503ff9cf05223e910d57dc9c3c8c7b.
Revert "Update to match felem spec and mostly implement memcpy lemma"
This reverts commit 245d8fe64ec8143c0abf1f22a357f3eeff735c02.
Revert "Update spec to use felems"
This reverts commit dd949789cdc38511bd12641cd5133a6cde3588f1.
Errors with
```
Error: Cannot find a physical path bound to logical path
Rupicola.Examples.Loops.
```
Maybe the submodule needs to be updated?
Please don't push commits that don't build on master, it breaks Coq's
CI.
cc @DIJamner
> Revert commits that don't build on master.

- _CoqProject
- src/Assembly/Equivalence.v
- src/Assembly/Symbolic.v
- src/Util/Strings/Subscript.v
- src/Util/Strings/Superscript.v
Prints things like
```
(addcarry₆₄, [((#15 >>₆₄ #10) +₆₄ (addcarry₆₄, [(#3 *₆₄ #5), ((#19 >>₆₄ #10) +₆₄ (addcarry₆₄, [#20, #26]))]))]) ≠ (addcarry₆₄, [(#15 >>₆₄ #10), (addcarry₆₄, [(#3 *₆₄ #5), (#19 >>₆₄ #10), (addcarry₆₄, [#20, #26])])])
```
> Add pretty-printer for asm error messages

- .github/workflows/coq-windows.yml
- .github/workflows/coq.yml
- Makefile
- README.md
It's confusing to have `make` not work by default on older versions of
Coq, I think, so instead when `SKIP_BEDROCK2` is unset we will set it by
default on old versions of Coq.
Fixes #1212
> Automatically skip bedrock2 on older versions of Coq

- src/Util/Relations.v
<p>
```
After |   Peak Mem | File Name                                                       |     Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
138m52.03s | 4072760 ko | Total Time / Peak Mem                                           | 139m15.93s | 4075576 ko || -0m23.90s ||     -2816 ko |   -0.28% |         -0.06%
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
7m23.75s | 1061508 ko | fiat-json/src/p384_32.json …
```
> Add some subrelation instances

- Makefile
- Makefile-coq.local
- _CoqProject
These are useful interactively but not really in CI, when they can
trigger on older versions needlessly.
> Suppress masking-absolute-name, make unsupported-attributes a warning

- .gitignore
- Makefile
- src/Bedrock/Standalone/StandaloneHaskellMain.v
- src/Bedrock/Standalone/StandaloneOCamlMain.v
- src/ExtractionHaskell/with_bedrock2_base_conversion.v
- src/ExtractionHaskell/with_bedrock2_saturated_solinas.v
- src/ExtractionHaskell/with_bedrock2_unsaturated_solinas.v
- src/ExtractionHaskell/with_bedrock2_word_by_word_montgomery.v
- src/ExtractionOCaml/with_bedrock2_base_conversion.v
- src/ExtractionOCaml/with_bedrock2_saturated_solinas.v
- src/ExtractionOCaml/with_bedrock2_unsaturated_solinas.v
- src/ExtractionOCaml/with_bedrock2_word_by_word_montgomery.v
This is in preparation for #1250.  We generate `with_bedrock2_*`
binaries which support bedrock2 output but default to C.  We also
install these by default when we are installing with bedrock2 enabled.
These will be the source files that we want to package up into source
releases of our generated code, as well as the source we use for
generating statically-linked redistributable binaries.
> Add `with_bedrock2` binaries

- src/Bedrock/End2End/RupicolaCrypto/Derive.v
- src/Bedrock/End2End/RupicolaCrypto/Low.v
Fixes some inconveniences and poor ergonomics around using `compile_buf_append`, making it more appropriate for automatic compilation.
> Fix issues in buf_append lemma and its usage, as well as memcpy lemma.

- inversion/zig/inversion.zig
Also rename `fieldElement` to `FieldElement `since the function returns a type.
> Zig inversion code: compute f and precomp at compile-time

- .github/workflows/c.yml
- .github/workflows/coq-macos.yml
- .github/workflows/coq-windows.yml
- .github/workflows/coq.yml
- .github/workflows/go.yml
- .github/workflows/java.yml
- .github/workflows/json.yml
- .github/workflows/rust.yml
- .github/workflows/zig.yml
We now cancel previous queued and in progress actions runs on PRs when a
PR is updated. Because [`github.head_ref` is only defined for PRs and
`github.run_id` is
unique-per-workflow](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value-1),
we won't cancel previous jobs on branches, meaning that we'll still see
a log of which commits succeeded and which ones failed.
> Friendlier GH Actions Queue

- Makefile
When rupicola depends on bedrock2 and `make -j` is run, both fiat-crypto
and rupicola race to build bedrock2 (rupicola on the noex part and
fiat-crypto on the compiler part).  This results in a race where two
processes are deleting and recreating bedrock2 makefile dependencies,
resulting in frequent errors of parallel make.  We avoid this issue by
declaring that rupicola is not allowed to start building until
bedrock2-compiler is done, whenever both are targets for building.
We could instead have rupicola just depend directly on
bedrock2-compiler?  Not sure if it matters that much.
cc @andres-erbsen @jadephilipoom for visibility
> Make rupicola depend on bedrock2-compiler as an order-only dependency

- Makefile
We use `sed` for word-splitting (should hopefully be Mac-compatible,
since it doesn't use any fancy extended sed features), and then we use a
heavy-handed nested patsubst in make to capitalize the first letter of
each word.  Should hopefully resolve
https://github.com/coq/coq/pull/16154.
> Do the heavy-lifting of title-case in GNU Make

- src/Util/FSets/FMapFacts.v
- src/Util/FSets/FMapOption.v
- src/Util/FSets/FMapProd.v
- src/Util/FSets/FMapSum.v
- src/Util/FSets/FMapTrie.v
- src/Util/Structures/Orders.v
I was finding that `reflexivity` was taking a long time to fail because
tc/conversion decided to try to unify FMap `Equal` with the relation I
was using.  So we eagerly remove most of the extraneous hints.
Timing coming soon, on top of <strike>#1290</strike>
> Remove some pesky FMap hints

- .gitignore
- Makefile
- src/ExtractionOCaml/base_conversion.v
- src/ExtractionOCaml/bedrock2_base_conversion.v
- src/ExtractionOCaml/bedrock2_saturated_solinas.v
- src/ExtractionOCaml/bedrock2_unsaturated_solinas.v
- src/ExtractionOCaml/bedrock2_word_by_word_montgomery.v
- src/ExtractionOCaml/perf_unsaturated_solinas.v
- src/ExtractionOCaml/perf_word_by_word_montgomery.v
- src/ExtractionOCaml/saturated_solinas.v
- src/ExtractionOCaml/unsaturated_solinas.v
- src/ExtractionOCaml/with_bedrock2_base_conversion.v
- src/ExtractionOCaml/with_bedrock2_saturated_solinas.v
- src/ExtractionOCaml/with_bedrock2_unsaturated_solinas.v
- src/ExtractionOCaml/with_bedrock2_word_by_word_montgomery.v
- src/ExtractionOCaml/word_by_word_montgomery.v
- src/Rewriter/PerfTesting/StandaloneOCamlMain.v
- src/StandaloneOCamlMain.v
This way we can hopefully avoid https://github.com/coq/coq/issues/7954
Timing data coming soon
> Generate .mli files: `{ => Recursive} Extraction`

- src/Util/FSets/FMapOption.v
- src/Util/FSets/FMapSum.v
This fixes errors like those of coq/coq#7954, e.g.,:
```
File "src/ExtractionOCaml/unsaturated_solinas.ml", line 1:
Error: The implementation src/ExtractionOCaml/unsaturated_solinas.ml
does not match the interface src/ExtractionOCaml/unsaturated_solinas.cmi:
... ... ... ... ... ... ... ... In module SumWSfun_gen.SumWSfun_gen:
Values do not match:
val empty : '_weak1 M1.t * '_weak2 M2.t
is not included in
val empty : 'a1 t
File "src/ExtractionOCaml/unsaturated_solinas.mli", line 5958, characters 4-21:
Expected declaration
File "src/ExtractionOCaml/unsaturated_solinas.ml", line 16856, characters 8-13:
Actual declaration
```
> Work around coq/coq#7954

- src/Assembly/Equivalence.v
- src/Assembly/EquivalenceProofs.v
- src/Assembly/Symbolic.v
This will allow us to switch to using the more efficient data structures just by removing the `Old` module and importing `New` instead.  We unfortunately can't do this yet because it makes extraction take forever (90ish minutes).
> Hide dag behind a (not very strong) interface

- src/Bedrock/End2End/X25519/MontgomeryLadderProperties.v
This should fix the failures observed in https://github.com/mit-plv/fiat-crypto/pull/1299.
> bump rupicola and adapt to bedrock2 compiler changes

- src/Util/FSets/FMapOption.v
- src/Util/FSets/FMapProd.v
- src/Util/FSets/FMapSum.v
- src/Util/FSets/FMapTrie/ShapeEx.v
This works around the issue with exponentially sized types in
extraction, COQBUG(https://github.com/coq/coq/issues/16172)
> Use records in FMap structures

- src/Util/FSets/FMapProd.v
COQBUG(https://github.com/coq/coq/issues/16288) means we can't use
extraction with primitive records inside functors
> Work around COQBUG(https://github.com/coq/coq/issues/16288)

- src/Experiments/SimplyTypedArithmetic.v
Partial adaptation for coq/coq#16258
> [sp2019latest] More work on `#[export]`-default rewrite hints

- src/MiscCompilerPasses.v
- src/MiscCompilerPassesProofs.v
I have no idea of what I'm doing but this seems to be dead code introducing a major algorithmic slowdown, so let's see what it gives.
> Do not compute elements of set as a list in MiscCompilerPasses.subst0n.

- src/Assembly/Equality.v
- src/Assembly/Equivalence.v
- src/Assembly/Parse.v
- src/Assembly/Symbolic.v
- src/Assembly/Syntax.v
Fixed the bug that caused the "overwhelmingly long list" mentioned in https://github.com/mit-plv/fiat-crypto/issues/1351.
The issue was caused by the assembly checker not recognizing that identical (separate) lines of assembly code were not in fact the same line.  The annotations from identical lines were all lumped together, resulting in the "overwhelmingly long" annotations.
> fixed annotations on assembly output for assembly-checker

- .github/workflows/coq.yml
It seems to be timing out on Ubuntu LTS or something, and we don't really need to see the validate output from multiple versions.  Insofar as we want to stress coqchk, we sort-of only care about stressing the newest version, I think.  Note that validate already only runs on commits to master, not on PRs, so this won't speed up PR CI timing at all.
> Only run validate on Coq master / dev

- README.md
Since d9f123fd330dab3fab551d69cd144a15dd0a77c5 (#1292) we've been using `Int.t` to work around a lack of coq/coq#11987.  The `Int` module was added in OCaml 4.08.
Dropping support for older OCaml is not such a big loss, as Coq 8.16 will require OCaml >= 4.09, (8.15 allows >= 4.05), Debian stable has 4.11, and Ubuntu LTS has 4.13 (even the old Ubuntu LTS has 4.08).
> Note OCaml 4.08 minimal version in the README

- fiat-rust/Cargo.toml
In light of the failure of https://github.com/mit-plv/fiat-crypto/actions/runs/2938420615/jobs/4692905587 and https://github.com/mit-plv/fiat-crypto/actions/runs/3168539692 we must bump twice
> Bump rust crate version

- .github/workflows/coq-windows.yml
- fiat-amd64/gentest.py
- src/BoundsPipeline.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
When we move to using more caching, we need to be more careful to not unfold the reified definitions.
<p>
```
After |   Peak Mem | File Name                                                   |    Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
33m54.38s | 5261256 ko | Total Time / Peak Mem                                       | 33m55.10s | 5262224 ko || -0m00.72s ||      -968 ko |   -0.03% |         -0.01%
--------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> More selective correctness proof tactics for PushButtonSynthesis

- etc/machine.sh
Old version prints
```
./etc/machine.sh: line 21: hostname: command not found
-noht-tb-nops-schedutil-haswell
option:
```
because
```
$ gcc -march=native -Q --help=target|grep march
-march=                               haswell
Known valid arguments for -march= option:
```
New version prints
```
transparent-rooster-noht-tb-nops-schedutil-haswell
```
> Adjust etc/machine.sh to work better on Arch

- .github/workflows/coq-windows.yml
We add back non-heavy generated files, but remove the heavy asm tests
> Try to make the windows target a bit lighter

- src/Bedrock/End2End/X25519/GarageDoor.v
Should improve https://github.com/mit-plv/fiat-crypto/issues/1427
Closes #1428
> use vm_compute instead of Ltac to check instruction bounds

- src/BoundsPipeline.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/SmallExamples.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
- src/SlowPrimeSynthesisExamples.v
They were explicit because they predated the implicit typeclass way of passing options.  Since the fancy argument does not change within a single file, there's no reason to make it easy to set and clog up the pipeline invocations.
> Make fancy arguments an implicit typeclass

- src/BoundsPipeline.v
- src/SlowPrimeSynthesisExamples.v
- src/Stringification/Language.v
Rather than trying to be clever about which casts to print, we instead always print all casts when displaying PHOAS.  This can be overridden via typeclass instances by leaving around other values for `PHOAS.with_casts` (boolean controling the previous default) and `PHOAS.with_all_casts` (boolean controlling the new default, overriding `PHOAS.with_casts`).
> Show more casts in PHOAS printing, sometimes

- src/Bedrock/End2End/Poly1305/Field1305.v
- src/Bedrock/End2End/X25519/Field25519.v
- src/Bedrock/Field/Synthesis/Examples/p224_64_new.v
- src/Bedrock/Field/Synthesis/Generic/UnsaturatedSolinas.v
- src/Bedrock/Field/Synthesis/Generic/WordByWordMontgomery.v
- src/Bedrock/Field/Synthesis/New/UnsaturatedSolinas.v
- src/Bedrock/Field/Synthesis/New/WordByWordMontgomery.v
- src/Bedrock/Field/Translation/Parameters/Defaults.v
- src/Bedrock/Field/Translation/Parameters/Defaults32.v
- src/Bedrock/Field/Translation/Parameters/Defaults64.v
- src/Bedrock/Field/Translation/Parameters/FE310.v
- src/BoundsPipeline.v
- src/Fancy/Barrett256.v
- src/Fancy/Montgomery256.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/SmallExamples.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
- src/Rewriter/PerfTesting/Core.v
- src/SlowPrimeSynthesisExamples.v
- src/StandaloneDebuggingExamples.v
Alternative to #1440
Closes #1440
I decided to add some debugging ability to rewriting (in particular some options to let fiat-crypto print out the AST before/after each rewrite pass), and decided in passing to reorganize the options to the pipeline to allow for less invasive future additions.  #1440 was too heavy, so I decided to instead base the records on how we use the options (BoundsPipeline to AST, BoundsPipeline to strings, field Pipeline to AST, field pipeline to strings, (the field synthesis does a bit more computation on top of the bounds pipeline, because it knows which operation is being synthesized, whether it's for the fancy machine, etc), or the full field synthesis pipeline (which also does things like assembly equivalence checking)).
Timing check coming soon
> Reorganize pipeline options to allow for easier additions to them

- src/Curves/EdwardsMontgomery.v
Let's see how it fares on master
cc https://github.com/mit-plv/fiat-crypto/issues/1434
> sprinkle Optimize Proof and Optimize Heap

- etc/ensure_stack_limit.sh
This means we won't quit `make` when we can't set the stack size.
> Use `return` rather than `exit` in `ensure_stack_limit.sh`

- src/BoundsPipeline.v
- src/CLI.v
- src/PushButtonSynthesis/BarrettReduction.v
- src/PushButtonSynthesis/BaseConversion.v
- src/PushButtonSynthesis/FancyMontgomeryReduction.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinas.v
- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/PushButtonSynthesis/WordByWordMontgomery.v
- src/Rewriter/PerfTesting/Core.v
- src/SlowPrimeSynthesisExamples.v
- src/StandaloneDebuggingExamples.v
- src/StandaloneOCamlMain.v
- src/Util/DebugMonad.v
- src/Util/FSets/FMapString.v
- src/Util/MSets/MSetString.v
- src/Util/Strings/ParseDebugOptions.v
Passing `--debug rewriting` will now print out info on the rewriting passes when synthesis fails; passing `--debug rewriting,on-success` will also print out the information even if synthesis succeeds.
This will hopefully help with debugging https://github.com/mit-plv/fiat-crypto/pull/1358#discussion_r990919165
Thoughts @andres-erbsen on whether or not we want to see all the intermediate debug info about rewriting passes on every synthesis failure?  (That is, should we be passing `--debug " -rewriting"` to disable the debug info, or should we have to pass `--debug rewriting` to enable it?)
Timing info coming soon
> Add `--debug` flag and debug info for rewriting

- src/Rewriter/Rules.v
- src/Rewriter/RulesProofs.v
For #1358 supporting bedrock2.
On top of #1473
> Handle `r[0~>0]` casts on `Z.mul_split`

- fiat-amd64/gentest.py
This way make test-amd64 will rebuild the status files when the binary changes.
> test-amd64: dependency on binary should not be order-only

- src/Assembly/Symbolic.v
- src/Assembly/WithBedrock/SymbolicProofs.v
This should allow more fine-grained bounds and easier extensibility.  This might be duplicative with some work in #1481, but I think this strategy will allow for better code reuse going forward.
Thoughts @andres-erbsen @OwenConoly ?
> Reuse PHOAS bounds analysis for asm bounds

- src/CLI.v
- src/StandaloneDebuggingExamples.v
- src/Util/Strings/ParseFlagOptions.v
h/t Andres
This will let us reuse them for rewrite passes without me feeling silly about naming.
> Rename Debug options to Flag options

- src/Assembly/Equivalence.v
- src/Assembly/EquivalenceProofs.v
- src/Assembly/Symbolic.v
- src/Assembly/WithBedrock/Proofs.v
- src/Assembly/WithBedrock/SymbolicProofs.v
- src/CLI.v
- src/StandaloneDebuggingExamples.v
- src/Util/Strings/ParseFlagOptions.v
Alternate implementation of the part of #1481 that enables control of which asm passes are enabled.  We go for a much more full-featured approach here, allowing the user to fully customize which rules are run, in what order, and how many times.  On top of #1495, #1496, #1497.
cc @OwenConoly @andres-erbsen
> Enable CLI control of equiv checker rewrite passes with `--asm-rewriting-pipeline`, `--asm-rewriting-passes`

- src/Assembly/EquivalenceProofs.v
- src/Assembly/Symbolic.v
- src/Assembly/WithBedrock/SymbolicProofs.v
- src/Util/Tactics/DestructHead.v
- src/Util/Tactics/DestructHyps.v
We don't currently use it, but this will allow us to augment `bound_expr` to make use of bounds in the dag and write passes that use this augmented bounds information.
In theory, this may also allow us to do lazy revealing of expressions rather than needing to reveal them deeply up-front.
This is split off so that it is possible to add more rewrite passes without conflicting too much with changes to how bounds are handled.
On top of #1504 
Timing info coming soon
cc @OwenConoly
> Make the dag available in ASM equiv rewrite passes

- src/Assembly/Symbolic.v
We don't currently include any proofs about it, nor make use of it; this is separated out so we can profile the overhead of including the bounds info in the dag.
We will later make use of it for better bounds analysis.
<p>
```
After |   Peak Mem | File Name                                                 |     Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
156m02.28s | 4384020 ko | Total Time / Peak Mem                                     | 151m16.20s | 4383892 ko || +4m46.07s ||       128 ko |   +3.15% |         +0.00% …
```
> ASM Equiv Checker: Include bounds info in dag

- src/Assembly/Symbolic.v
This is another part of #1481 ripped out and implemented in a somewhat different way.  Here we maintain the abstraction barrier of the dag implementation, and separate out the commits enough to profile the change of using dag bounds on its own.
We pay only a small cost for this, so it seems more than worth it.
<p>
```
After |   Peak Mem | File Name                                                 |     Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
158m20.95s | 4393964 ko | Total Time / Peak Mem                                     | 156m15.65s | 4393936 ko …
```
> ASM Equivalence Checker: Use bounds from the dag

- .github/workflows/c.yml
For `os.ReadFile` as per https://pkg.go.dev/os#ReadFile to avoid
```
Error: util/embed_test_data.go:79:16: undefined: os.ReadFile
Error: util/embed_test_data.go:129:16: undefined: os.ReadFile
```
https://github.com/mit-plv/fiat-crypto/actions/runs/3564511625/jobs/5988555886#step:8:110
cc @davidben
> Bump Go from 1.13 to 1.16

- src/Arithmetic/BarrettReduction/Generalized.v
- src/Arithmetic/BarrettReduction/HAC.v
- src/Arithmetic/BarrettReduction/Wikipedia.v
- src/Arithmetic/ModularArithmeticTheorems.v
- src/Arithmetic/SolinasReduction.v
- src/Curves/TableMult/TableMult.v
- src/Util/NumTheoryUtil.v
- src/Util/ZUtil/Div.v
- src/Util/ZUtil/Modulo.v
Remove deprecated `Z_div_mod_eq`, `div_Zdiv` and `mod_Zmod` (coq/coq#16920).
> Adapt to coq/coq#16920

- .github/workflows/java.yml
Reverts mit-plv/fiat-crypto#1531
Seems that this version no longer exists
> Revert "Bump actions/setup-java from 3.6.0 to 3.7.0"

- etc/ensure_stack_limit.sh
Apparently 66520 is the absolute limit on Mac, cf https://github.com/mit-plv/fiat-crypto/issues/1565#issuecomment-1499054965
> Use 66520 for stack size limit for MacOS compat

- src/Arithmetic/BarrettReduction/Generalized.v
- src/Arithmetic/BarrettReduction/HAC.v
- src/Arithmetic/BarrettReduction/Wikipedia.v
- src/Arithmetic/ModularArithmeticTheorems.v
- src/Util/NumTheoryUtil.v
- src/Util/ZUtil/Div.v
- src/Util/ZUtil/Modulo.v
Remove deprecated Z_div_mod_eq, div_Zdiv and mod_Zmod (coq/coq#16920)
> Adapt fiat-crypto-legacy to coq/coq#16920

- src/Util/Loops.v
This is backwards compatible.
The current master branch exploits a bug in the intropattern evaluation, where a split pattern is successfully applied to a higher-order hypothesis even though the dependent argument cannot be solved.
> Adapt w.r.t. coq/coq#17564.

- fiat-zig/src/curve25519_32.zig
- fiat-zig/src/curve25519_64.zig
- fiat-zig/src/curve25519_scalar_32.zig
- fiat-zig/src/curve25519_scalar_64.zig
- fiat-zig/src/curve25519_solinas_64.zig
- fiat-zig/src/p224_32.zig
- fiat-zig/src/p224_64.zig
- fiat-zig/src/p256_32.zig
- fiat-zig/src/p256_64.zig
- fiat-zig/src/p256_scalar_32.zig
- fiat-zig/src/p256_scalar_64.zig
- fiat-zig/src/p384_32.zig
- fiat-zig/src/p384_64.zig
- fiat-zig/src/p384_scalar_32.zig
- fiat-zig/src/p384_scalar_64.zig
- fiat-zig/src/p434_64.zig
- fiat-zig/src/p448_solinas_32.zig
- fiat-zig/src/p448_solinas_64.zig
- fiat-zig/src/p521_32.zig
- fiat-zig/src/p521_64.zig
- fiat-zig/src/poly1305_32.zig
- fiat-zig/src/poly1305_64.zig
- fiat-zig/src/secp256k1_dettman_32.zig
- fiat-zig/src/secp256k1_dettman_64.zig
- fiat-zig/src/secp256k1_montgomery_32.zig
- fiat-zig/src/secp256k1_montgomery_64.zig
- fiat-zig/src/secp256k1_montgomery_scalar_32.zig
- fiat-zig/src/secp256k1_montgomery_scalar_64.zig
- inversion/zig/inversion.zig
- src/Stringification/Zig.v
`@truncate()` and `@bitCast()` now do type inference, so the code can be simplified a bit.
I still really wish there was a way to make the distinction between casts that truncate, and casts that extend the types (and thus are always guaranteed to be safe).
> Update for Zig 0.11.0

- src/Experiments/SimplyTypedArithmetic.v
- src/Primitives/EdDSARepChange.v
Like #1627, this anticipates coq/coq#17888 for fiat-crypto-legacy.
Note that two `rewrite` are now useless in SimplyTypedArithmetic.v` (and actually failing). This is strange, so either I missed some qualification, or there is another change in the Coq PR that makes these `rewrite` useless. I don't know if I should have investigated further to be sure of the answer, or if it is not so important.
> Qualifying expr.expr and cie coming from Uncurried and EdDSA.sign from Spec

- src/Curves/Montgomery/XZProofs.v
In anticipation of coq/coq#17888 which would declare a new name `M.eq` in `XZProofs.v`, this PR qualifies the use of `M.eq` into `MontgomeryCurve.M.eq`.
The PR is not needed as long as the merge of coq/coq#17888 is not confirmed, but the PR can also be merged as soon as now if you think that the disambiguation is worth, independently of coq/coq#17888.
> Qualifying M.eq coming from MontgomeryCurve

- src/BoundsPipeline.v
Should help with debugging https://github.com/mit-plv/fiat-crypto/pull/1609#discussion_r1284644023
> Print more casts when stringification fails

- src/Bedrock/End2End/Poly1305/Field1305.v
- src/Bedrock/End2End/RupicolaCrypto/Low.v
- src/Bedrock/End2End/X25519/Field25519.v
- src/Bedrock/Field/Synthesis/New/UnsaturatedSolinas.v
- src/Bedrock/Field/Synthesis/New/WordByWordMontgomery.v
- src/Bedrock/Specs/Field.v
Very similar to #1635, but for subtraction. `carry_sub` guarantees `tight_bounds` on the output, which will be necessary for a bedrock2 version of [point doubling](https://github.com/mit-plv/fiat-crypto/blob/5978c17a79ef72758882da9773fe3c90e303d500/src/Curves/Edwards/XYZT/Basic.v#L136).
> Pipe through carry_sub function

- fiat-rust/Cargo.toml
- fiat-rust/src/curve25519_32.rs
- fiat-rust/src/curve25519_64.rs
- fiat-rust/src/curve25519_scalar_32.rs
- fiat-rust/src/curve25519_scalar_64.rs
- fiat-rust/src/p224_32.rs
- fiat-rust/src/p224_64.rs
- fiat-rust/src/p256_32.rs
- fiat-rust/src/p256_64.rs
- fiat-rust/src/p256_scalar_32.rs
- fiat-rust/src/p256_scalar_64.rs
- fiat-rust/src/p384_32.rs
- fiat-rust/src/p384_64.rs
- fiat-rust/src/p384_scalar_32.rs
- fiat-rust/src/p384_scalar_64.rs
- fiat-rust/src/p434_64.rs
- fiat-rust/src/p448_solinas_32.rs
- fiat-rust/src/p448_solinas_64.rs
- fiat-rust/src/p521_32.rs
- fiat-rust/src/p521_64.rs
- fiat-rust/src/poly1305_32.rs
- fiat-rust/src/poly1305_64.rs
- fiat-rust/src/secp256k1_montgomery_32.rs
- fiat-rust/src/secp256k1_montgomery_64.rs
- fiat-rust/src/secp256k1_montgomery_scalar_32.rs
- fiat-rust/src/secp256k1_montgomery_scalar_64.rs
- src/Stringification/Rust.v
This PR fixes #1620 by replacing type aliases for arrays with newtypes. As the types for Montgomery/non-Montgomery or tight/loose field elements are now distinct, this will prevent misuse by consumers. Since this is a breaking change, I bumped the crate version to 0.2.0.
I couldn't figure out how to make the suggested changes to stringification of `IR.List_nth` expressions, so I solved that part of the problem in Rust instead. Bare arrays, without typedefs, are still used in function arguments. Thus, any `IR.List_nth` operation would either need to be lowered to `({v}[{n}])` or `({v}.0[{n}])`, depending on the type of the operation's argument. I couldn't figure out how to access type information starting from these IR nodes, so I instead implemented `Index` and `IndexMut` on the new Rust …
> Rust: Create newtype structs for typedefs

- .github/workflows/rust.yml
- fiat-rust/Cargo.toml
- fiat-rust/src/curve25519_32.rs
- fiat-rust/src/curve25519_64.rs
- fiat-rust/src/curve25519_scalar_32.rs
- fiat-rust/src/curve25519_scalar_64.rs
- fiat-rust/src/p224_32.rs
- fiat-rust/src/p224_64.rs
- fiat-rust/src/p256_32.rs
- fiat-rust/src/p256_64.rs
- fiat-rust/src/p256_scalar_32.rs
- fiat-rust/src/p256_scalar_64.rs
- fiat-rust/src/p384_32.rs
- fiat-rust/src/p384_64.rs
- fiat-rust/src/p384_scalar_32.rs
- fiat-rust/src/p384_scalar_64.rs
- fiat-rust/src/p434_64.rs
- fiat-rust/src/p448_solinas_32.rs
- fiat-rust/src/p448_solinas_64.rs
- fiat-rust/src/p521_32.rs
- fiat-rust/src/p521_64.rs
- fiat-rust/src/poly1305_32.rs
- fiat-rust/src/poly1305_64.rs
- fiat-rust/src/secp256k1_montgomery_32.rs
- fiat-rust/src/secp256k1_montgomery_64.rs
- fiat-rust/src/secp256k1_montgomery_scalar_32.rs
- fiat-rust/src/secp256k1_montgomery_scalar_64.rs
- src/Stringification/Rust.v
closes #1645 
I have also added a Actions test to prevent this from happening in the future.
> Rust: Reference newtype operators from `core` instead of `std`

- src/Fancy/Prod.v
Before coq/coq#17964 `replace foo with bar by tac` actually means `replace foo with bar by first [assumption | symmetry; assumption | tac]`.
> Stop relying on `replace by` automatic `assumption`-based solving

- src/StandaloneOCamlMain.v
This should be backwards compatible with old versions of OCaml
Fixes #1674
> Drop use of Pervasives

- fiat-rust/src/curve25519_32.rs
- fiat-rust/src/curve25519_64.rs
- fiat-rust/src/curve25519_scalar_32.rs
- fiat-rust/src/curve25519_scalar_64.rs
- fiat-rust/src/curve25519_solinas_64.rs
- fiat-rust/src/p224_32.rs
- fiat-rust/src/p224_64.rs
- fiat-rust/src/p256_32.rs
- fiat-rust/src/p256_64.rs
- fiat-rust/src/p256_scalar_32.rs
- fiat-rust/src/p256_scalar_64.rs
- fiat-rust/src/p384_32.rs
- fiat-rust/src/p384_64.rs
- fiat-rust/src/p384_scalar_32.rs
- fiat-rust/src/p384_scalar_64.rs
- fiat-rust/src/p434_64.rs
- fiat-rust/src/p448_solinas_32.rs
- fiat-rust/src/p448_solinas_64.rs
- fiat-rust/src/p521_32.rs
- fiat-rust/src/p521_64.rs
- fiat-rust/src/poly1305_32.rs
- fiat-rust/src/poly1305_64.rs
- fiat-rust/src/secp256k1_dettman_32.rs
- fiat-rust/src/secp256k1_dettman_64.rs
- fiat-rust/src/secp256k1_montgomery_32.rs
- fiat-rust/src/secp256k1_montgomery_64.rs
- fiat-rust/src/secp256k1_montgomery_scalar_32.rs
- fiat-rust/src/secp256k1_montgomery_scalar_64.rs
- src/Stringification/Rust.v
The cargo clippy reports as an issue returning an empty tuple and recommends remove it.
[1] https://rust-lang.github.io/rust-clippy/master/index.html#/unused_unit/
> rust: Replaces return an empty tuple by nothing (void).

- src/Util/Notations.v
This follows what was done for notations at level binder_constr in Coq PR #18014.
This should fix the compilation of fiat crypto legacy in Coq CI, but I could not fully check (I get a segfault on src/Algebra/Field.v, maybe due to a previous failure to set the ulimit??)
> Moving at level 10 notations which were originally at level 200

- .github/workflows/c.yml
- .github/workflows/coq-debian.yml
- .github/workflows/coq-macos.yml
- .github/workflows/coq-windows.yml
- .github/workflows/docker-coq.yml
- .github/workflows/go.yml
- .github/workflows/java.yml
- .github/workflows/json.yml
- .github/workflows/rust.yml
- .github/workflows/zig.yml
As per
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions this will allow us to enable merge queues in
https://github.com/mit-plv/fiat-crypto/settings/branch_protection_rules/3303819
Note that this doesn't actually change any behavior when this setting is not enabled, but I plan to enable this setting shortly. (cc @andres-erbsen )
> [CI] Add `merge_group:` trigger for merge queue

- .github/workflows/coq-alpine.yml
- .github/workflows/coq-debian.yml
- .github/workflows/coq-docker.yml
We remove the slow test from debian CI, hopefully speeding up CI execution significantly, replacing them with the lite-amd64 tests, and add the lite-amd64 tests to alpine.
@andres-erbsen Does this look good to you?
> Only test full amd64 files in Docker CI

- .github/workflows/coq-alpine.yml
- .github/workflows/coq-debian.yml
- .github/workflows/coq-docker.yml
- .github/workflows/coq-macos.yml
- .github/workflows/coq-windows.yml
There's also some minimal testing to see that the binaries work without installing all the extra Coq infrastructure.
Presumably we should get #1625 working and upload only statically-linked elf binaries (+ mac & windows), not separate binaries for docker, debian, etc.  Also TODO: figuring out if we need to do extra things to get Windows binaries working (probably?).
On top of #1710
> Upload standalone binaries to release pages

- fiat-rust/src/curve25519_32.rs
- fiat-rust/src/curve25519_64.rs
- fiat-rust/src/curve25519_scalar_32.rs
- fiat-rust/src/curve25519_scalar_64.rs
- fiat-rust/src/curve25519_solinas_64.rs
- fiat-rust/src/p224_32.rs
- fiat-rust/src/p224_64.rs
- fiat-rust/src/p256_32.rs
- fiat-rust/src/p256_64.rs
- fiat-rust/src/p256_scalar_32.rs
- fiat-rust/src/p256_scalar_64.rs
- fiat-rust/src/p384_32.rs
- fiat-rust/src/p384_64.rs
- fiat-rust/src/p384_scalar_32.rs
- fiat-rust/src/p384_scalar_64.rs
- fiat-rust/src/p434_64.rs
- fiat-rust/src/p448_solinas_32.rs
- fiat-rust/src/p448_solinas_64.rs
- fiat-rust/src/p521_32.rs
- fiat-rust/src/p521_64.rs
- fiat-rust/src/poly1305_32.rs
- fiat-rust/src/poly1305_64.rs
- fiat-rust/src/secp256k1_montgomery_32.rs
- fiat-rust/src/secp256k1_montgomery_64.rs
- fiat-rust/src/secp256k1_montgomery_scalar_32.rs
- fiat-rust/src/secp256k1_montgomery_scalar_64.rs
- src/Stringification/Rust.v
Includes doc comments for auxiliary type alias, which are created for one-byte variables.
> rust: Include documentation comments for type alias.

- .github/workflows/coq-alpine.yml
- .github/workflows/coq-debian.yml
- .github/workflows/coq-docker.yml
- .github/workflows/coq-macos.yml
- .github/workflows/coq-windows.yml
- etc/ci/find-arch.sh
We upload the statically-linked Alpine edge binaries, as these are
probably the most portable.
Note that the statically-linked Alpine binaries are actually smaller
than the Debian executables (~35 MB archive vs ~41 MB archive), though
the Debian ones are pie (position-independent executables, supporting
Address Space Layout Randomization).
Current names file names:
fiat-crypto-windows.zip
fiat-crypto-macos.tar.gz
fiat-crypto-linux-x86_64.tar.gz
Suggestions welcome cc @andres-erbsen
> Only upload one copy of linux binaries to releases

- .github/workflows/coq-alpine.yml
- .github/workflows/coq-debian.yml
- .github/workflows/coq-macos.yml
- .github/workflows/coq-windows.yml
We match the various opam install targets.
Skipping docker for now due to sudo problems, that's coming in another PR.
Fixes #1732
> Test install target on CI (no docker)

- src/Algebra/Hierarchy.v
- src/Arithmetic/ModularArithmeticTheorems.v
- src/Arithmetic/MontgomeryReduction/WordByWord/Abstract/Proofs.v
- src/Compilers/Named/NameUtilProperties.v
- src/Compilers/WfReflectiveGen.v
- src/Compilers/Z/Bounds/RoundUpLemmas.v
- src/Experiments/SimplyTypedArithmetic.v
- src/LegacyArithmetic/BaseSystem.v
- src/LegacyArithmetic/BaseSystemProofs.v
- src/LegacyArithmetic/Pow2BaseProofs.v
- src/Primitives/EdDSARepChange.v
- src/Spec/EdDSA.v
- src/Util/Decidable/Decidable2Bool.v
- src/Util/FixedWordSizesEquality.v
- src/Util/ListUtil.v
- src/Util/NUtil.v
- src/Util/NUtil/WithoutReferenceToZ.v
- src/Util/NatUtil.v
- src/Util/NumTheoryUtil.v
- src/Util/Strings/String.v
- src/Util/Tuple.v
- src/Util/WordUtil.v
- src/Util/ZUtil.v
- src/Util/ZUtil/Hints/Core.v
- src/Util/ZUtil/Shift.v
These changes should be mostly backwards compatible (at least down to 8.16).
PS: the sp2019 target is intended, I'm trying to pass "fiat_crypto_legacy" in Coq's CI.
> Adapt wrt Coq/Coq#18164

- fiat-html/fiat-crypto.html
- fiat-html/fiat_crypto_worker.js
- fiat-html/main.js
Now that `--enable effects` means we're no longer hitting recursion limits, it's useful to not block the UI thread and to use a cache (currently in localStorage).
On top of #1737.  Separate PR so that we can finally merge #1737.
> Use WebWorkers and a cache for js-of-ocaml

- .github/workflows/coq-docker.yml
We match the various opam install targets.
Non-docker targets in #1734 
Fixes #1732
> Test install target on CI (docker only)

- Makefile
This way the opam install target won't fail.
> Make install targets depend on vo files

- src/Bedrock/End2End/Poly1305/Field1305.v
- src/Bedrock/Field/Synthesis/Examples/p224_64_new.v
Two changes are needed because coqutil's Bitwidth instances are now `#[export]` instead of `#[global]`.
> bump rupicola

- README.md
Unfortunately some of the synthesis examples (32-bit p256 and all of the bedrock2 examples) still exceed available stack, see https://github.com/ocsigen/js_of_ocaml/issues/1533
> Add web links to README

- .github/workflows/coq-docker.yml
This way we can more easily build both js_of_ocaml and wasm_of_ocaml outputs, which require different ocaml compilers.  This would also allow decoupling the testing of Coq versions from OCaml versions on extracted code.
> Split up coq-docker job a lot

- fiat-html/disable-wasm-option.js
- fiat-html/fiat-crypto.html
- fiat-html/main.js
- fiat-html/wasm_fiat_crypto_worker.js
Currently kinda blocked on
- https://github.com/ocaml-wasm/wasm_of_ocaml/issues/9
- https://github.com/ocaml-wasm/wasm_of_ocaml/issues/10
- https://github.com/ocaml-wasm/wasm_of_ocaml/issues/11
But I can do a feature check for firefox tail-call support, and hopefully I'll get an event trigger for the wasm code ready.
> Deploy WASM integration to https://mit-plv.github.io/fiat-crypto

- README.md
- src/Language/WfExtra.v
Depends on https://github.com/mit-plv/rewriter/pull/124 and https://github.com/mit-plv/fiat-crypto/pull/1753, for https://github.com/JasonGross/fiat-crypto/tree/dont-bottomify
> Adapt to expr.Wf4

- .github/workflows/coq-opam-package.yml
Addresses the specific complaint in https://github.com/ocaml/setup-ocaml/issues/720. A run of this workflow can be seen [on my fork](https://github.com/dra27/fiat-crypto/actions/runs/7003071299). In particular, the "Set up OCaml" step has this for the three Windows jobs:
```yaml
Run ocaml/setup-ocaml@v2
with:
ocaml-compiler: 4.11.1
opam-repositories: opam-repository-mingw: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
default: https://github.com/ocaml/opam-repository.git
```
(both `opam-repository-mingw` and `default` for `opam-repositories`) but the 6 macOS and Ubuntu jobs have:
```yaml
Run ocaml/setup-ocaml@v2
with:
ocaml-compiler: 4.11.1
opam-repositories: 
default: https://github.com/ocaml/opam-repository.git
```
Likewise, the step "Run `opam install coq-fiat-crypto …
> Use objects instead of arrays in coq-opam-package.yml

- src/AbstractInterpretation/ZRangeProofs.v
- src/CompilersTestCases.v
Also add some utility functions to ZRangeProofs
This is very minor progress towards avoiding replacing the abstract state of higher order functions with bottom when we can avoid it, in service of #1609.
> Future-proof CompilersTestCases

- src/Util/ZRange/Operations.v
Towards more fine-grained bounds analysis of `if` and `Z.{max,min,ltb,leb,gtb,geb}`
Towards https://github.com/mit-plv/fiat-crypto/pull/1609 and https://github.com/mit-plv/fiat-crypto/pull/1769
> Add support for applying bool functions to zrange

- src/PushButtonSynthesis/UnsaturatedSolinas.v
- src/UnsaturatedSolinasHeuristics.v
- src/UnsaturatedSolinasHeuristics/Tests.v
- src/Util/ListUtil.v
- src/Util/Notations.v
- src/Util/Option.v
- src/Util/Tuple.v
To replace `RingMicromega.map_option2` in
https://github.com/mit-plv/fiat-crypto/pull/1609
> Add `Util.Option.bind2`

- src/AbstractInterpretation/ZRange.v
- src/AbstractInterpretation/ZRangeProofs.v
Of `if` and `Z.{max,min,ltb,leb,gtb,geb}`
Splitting out a bit of #1609 that can be merged in isolation
On top of https://github.com/mit-plv/fiat-crypto/pull/1768 and https://github.com/mit-plv/fiat-crypto/pull/1770
<p>
```
After |   Peak Mem | File Name                                                         |     Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
118m07.69s | 2852656 ko | Total Time / Peak Mem                                             | 120m57.22s | 2852384 ko || -2m49.52s ||       272 ko |   -2.33% |         +0.00% …
```
> More fine-grained bounds analysis

- src/AbstractInterpretation/ZRange.v
- src/AbstractInterpretation/ZRangeCommonProofs.v
- src/AbstractInterpretation/ZRangeProofs.v
- src/Assembly/Equivalence.v
- src/BoundsPipeline.v
- src/Language/APINotations.v
- src/Language/IdentifierParameters.v
- src/Language/PreExtra.v
- src/Stringification/IR.v
- src/Stringification/Language.v
For https://github.com/mit-plv/fiat-crypto/pull/1609
Slow identifiers are commented out.  I'll have to figure out a different
way to prove the ZRange bounds proof that isn't so slow.
<p>
```
After |   Peak Mem | File Name                                                       |    Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
65m48.78s | 2852620 ko | Total Time / Peak Mem                                           | 67m03.79s | 2852280 ko || -1m15.01s ||       340 ko |   -1.86% |         +0.01% …
```
> Add more identifiers for saturated solinas

- src/Rewriter/RulesProofs.v
For https://github.com/mit-plv/fiat-crypto/pull/1609 and https://github.com/mit-plv/fiat-crypto/pull/1777
> Augment rewrite rule proving tactics for saturated arithmetic

- .github/workflows/coq-alpine.yml
- .github/workflows/coq-debian.yml
- .github/workflows/coq-docker.yml
- .github/workflows/coq-macos.yml
- .github/workflows/coq-windows.yml
- .github/workflows/java.yml
This reverts commit 723baacab7bdd8187d47b2aa07796294ceb95f84.
v4 is buggy and has a very high failure rate, see also https://github.com/actions/download-artifact/issues/249
> Revert "Bump actions/download-artifact and actions/upload-artifact from 3 to 4 (#1786)"

- .github/workflows/coq-archlinux.yml
In Arch this time.
v4 is buggy and has a very high failure rate, see also https://github.com/actions/download-artifact/issues/249
> Downgrade actions/{download,upload}-artifact 4=>3

- README.md
This changes unordered lists at the third nesting level to use `*` instead of `.` as bullets, so that they are properly formatted by Markdown.
(same idea as mit-plv/rewriter#147)
> Fix nested unordered lists in README.md

- .github/workflows/coq-alpine.yml
Once https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/57766 is merged we will no longer require this workaround.
> [CI] Drop alpine workaround

- src/Compilers/Named/ContextProperties/Proper.v
With coq/coq#18445, notations hiding constants with multiple signatures of implicit arguments inherit as expected the underlying implicit arguments.
File `src/Compilers/Named/ContextProperties/Proper.v` was depending on the "bug". We adapt it by changing the notation so that it becomes indifferent to potential insertion of maximal implicit arguments.
Note that this is one possible fix among others (for instance, it is probably also possible to change the signatures of the underlying constant).
It is (a priori) backwards compatible and can be merged as soon as now.
> Adapt to Coq's PR #18445 fixing inheritance of multiple signatures of implicit arguments in notations

- src/BoundsPipeline.v
- src/Language/TreeCaching.v
- src/MiscCompilerPasses.v
- src/MiscCompilerPassesProofs.v
- src/MiscCompilerPassesProofsExtra.v
The naive encoding of PHOAS passes that need to produce both [expr]-like output and data-like output simultaneously involves exponential blowup.
This commit adds caching of results (and/or intermediates) of a data-producing PHOAS pass in a tree structure that mimics the PHOAS expression so that a subsequent pass can consume this tree and a PHOAS expression to produce a new expression.
More concretely, suppose we are trying to write a pass that is `expr var1 * expr var2 -> A * expr var3`. We can define an `expr`-like-tree-structure that (a) doesn't use higher-order things for `Abs` nodes, and (b) stores `A` at every node. Then we can write a pass that is `expr var1 * expr var2 -> A * tree-of-A` and then `expr var1 * expr var2 * tree-of-A -> expr var3` such that we incur only linear …
> Fix DCE/Subst01 to work under lambdas

- src/Assembly/Symbolic.v
- src/Util/ListUtil.v
> adapt to coq/coq#18563

- src/Algebra/Group.v
- src/Assembly/Equivalence.v
- src/Bedrock/Field/Common/Types.v
- src/CLI.v
- src/Stringification/Language.v
Adapt to https://github.com/coq/coq/pull/18590
> Adapt to https://github.com/coq/coq/pull/18590

- src/Algebra/Group.v
- src/LegacyArithmetic/Interface.v
For https://github.com/coq/coq/pull/18590
Change made with
```bash
python -c "$(printf 'import re\nfs = {f:open(f, "r").read() for f in (%s)}\nfs2 = {f:[m for m in re.findall(r"%s", c, flags=re.MULTILINE|re.DOTALL) if not m.startswith("Existing") and ":>" in m and re.search(r"%s", m, flags=re.MULTILINE|re.DOTALL)] for f, c in fs.items()}\nfs3 = {f:m for f, m in fs2.items() if m}\nfs4 = {}\nfor f, m in fs3.items():\n    orig = rep = fs[f]\n    for val in m:\n        rep = rep.replace(val, val.replace(":>", "::"))\n    fs4[f] = rep\nfor f, c in fs4.items():\n    open(f, "w").write(c)' "$(printf '"%s", ' $(git grep --name-only 'Class '))" '(?:Existing\s+)?Class\s.*?\.\s' ':=\s*{')"
```
> [sp2019latest] Adapt to coq/coq#18590

- src/LegacyArithmetic/Interface.v
For https://github.com/coq/coq/pull/18590
Changes made with https://gist.github.com/JasonGross/59fc3c03664f2280849abf50b531be42
> Adapt definitional classes to coq/coq#18590

- .github/workflows/coq-alpine.yml
> Use etc/ci/github-actions-make.sh on alpine

- Makefile
- src/Curves/Weierstrass/Jacobian/CoZ.v
- src/Curves/Weierstrass/Jacobian/Jacobian.v
- src/Curves/Weierstrass/Jacobian/ScalarMult.v
Not sure if this is of interest for inclusion, feel free to close if not. 
I have proved correctness of an implementation of Joye's double-add ladder for short Weierstrass curves in co-Z arithmetic (basically algorithm 14 from ["Scalar Multiplication on Weierstraß Elliptic Curves from Co-Z Arithmetic", Goundar et al., Journal of Cryptographic Engineering 2011](https://marcjoye.github.io/papers/GJMRV11regpm.pdf)) to study on Fiat-Crypto a bit.
Just for my own interest, what would be the easiest way to synthesize some C code out of it?
> Joye double-add ladder for short Weierstrass curves in co-Z arithmetic

- src/Bedrock/End2End/X25519/GarageDoorTop.v
~~Depends on successful fast-forward of https://github.com/mit-plv/rupicola/pull/105 https://github.com/mit-plv/bedrock2/pull/408 https://github.com/mit-plv/coqutil/pull/113~~
> bump bedrock2, use "always" in GarageDoor spec

- src/Bedrock/End2End/X25519/GarageDoor.v
- src/Bedrock/End2End/X25519/GarageDoorTop.v
```coq
Definition protocol_step : state -> list _ -> state -> Prop. Admitted.
Definition protocol_spec t := exists s s', labeled_transitions protocol_step s s' t.
Definition io_spec : list LogItem -> Prop := only_mmio_satisfying (boot_seq +++ protocol_spec).
Definition initial_conditions mach := 0x20400000 = mach.(getPc) /\ [] = mach.(getLog) /\ ... .
Theorem garagedoor_correct : forall mach : RiscvMachine, initial_conditions mach ->
always run1 (eventually run1 (fun mach' => io_spec mach'.(getLog))) mach.
```
> paperify spec

- src/Experiments/SimplyTypedArithmetic.v
- src/LegacyArithmetic/Double/Proofs/Decode.v
- src/LegacyArithmetic/Double/Proofs/RippleCarryAddSub.v
- src/Util/Equality.v
- src/Util/NatUtil.v
- src/Util/ZUtil/Div.v
- src/Util/ZUtil/Hints.v
- src/Util/ZUtil/Hints/ZArith.v
- src/Util/ZUtil/LandLorBounds.v
- src/Util/ZUtil/Pow.v
I've spotted a few suspect lines around the ones I've modified, it seems the code adds the same hints several times.
> Adapt w.r.t. coq/coq#18895.

- .github/dependabot.yml
All times are UTC, so running builds when it's nighttime in Boston.
> Stagger dependabot update times

- .github/workflows/coq-debian.yml
Passing `GITHUB_STEP_SUMMARY="$GITHUB_STEP_SUMMARY"` through to the chroot was not working, so let's try using a container instead
> [CI] use container instead of chroot for Debian

- src/Algebra/Field.v
- src/Algebra/Group.v
- src/Algebra/Hierarchy.v
- src/Algebra/IntegralDomain.v
- src/Algebra/Ring.v
- src/Bedrock/End2End/RupicolaCrypto/ChaCha20.v
- src/Bedrock/Field/Synthesis/New/Signature.v
- src/Bedrock/Field/Translation/Proofs/EquivalenceProperties.v
- src/Bedrock/Field/Translation/Proofs/Func.v
- src/Spec/CompleteEdwardsCurve.v
- src/Util/Relations.v
> Adapt w.r.t. coq/coq#18909.

- .github/workflows/coq-macos.yml
- etc/ci/find-arch.sh
Fixes #1727
Note that this currently deliberately errors, because I need to check on the generated file name and figure out how to get etc/ci/find-arch.sh to emit "universal"
> Build universal (x86_64+arm64) binaries for MacOS

- .github/workflows/coq-macos.yml
Maybe this time it's more stable. The v3 version will be removed in
November 2024 according to
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
git grep --name-only -- -artifact@v3 | grep coq-macos | xargs sed -i 's/-artifact@v3/-artifact@v4/g'
```
On top of #1891
> [CI] Use {upload,download}-artifact@v4 in MacOS

- .github/workflows/coq-docker.yml
Fixes #1900
(hopefully; the CI doesn't test the validate job)
> Reuse docker images for validate job

- .github/workflows/coq-alpine.yml
- .github/workflows/coq-archlinux.yml
- .github/workflows/coq-debian.yml
- .github/workflows/coq-docker.yml
- .github/workflows/coq-windows.yml
- .github/workflows/java.yml
Maybe this time it's more stable.  The v3 version will be removed in November 2024 according to
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
git grep --name-only -- -artifact@v3 | grep -v coq-macos | xargs sed -i 's/-artifact@v3/-artifact@v4/g'
```
Skip MacOS to avoid conflicts with #1891
> [Non-Mac] Switch to {upload,download}-artifact@v4

- .github/workflows/coq-docker.yml
https://github.com/coq-community/docker-coq-action/pull/89 was merged
> [CI] Remove dead code

- .github/workflows/coq-debian.yml
This should hopefully deal with https://github.com/mit-plv/fiat-crypto/issues/1394#issuecomment-2160967034
@andres-erbsen What do you think?
> [CI] [debian] Containerize testing of standalone

- src/Util/ZUtil/Hints/Core.v
coq/coq#19310 rewrites the Coq prefix to Stdlib on the fly
> [sp2019latest] (partial) compatibility with coq/coq#19310

- .github/workflows/coq-windows.yml
Work around
```
opam exec -- etc/ci/github-actions-make.sh -j2 deps
Fatal error: exception C:\hostedtoolcache\windows\opam\2.2.1\x86_64\opam.exe: "create_process" failed on etc/ci/github-actions-make.sh: Exec format error
```
> [CI] [Windows] Attempt to fix Windows CI

- .github/workflows/coq-docker.yml
- .github/workflows/coq-opam-package.yml
Until https://github.com/ocaml/setup-ocaml/issues/872 / https://github.com/ocaml/setup-ocaml/issues/860 are fixed.
> [CI] Pin action steps that use setup-ocaml to ubuntu 22.04

- .github/workflows/coq-docker.yml
- .github/workflows/coq-opam-package.yml
Reverts mit-plv/fiat-crypto#1971
Now that https://github.com/ocaml/setup-ocaml/pull/879 has been merged
> Revert "[CI] Pin action steps that use setup-ocaml to ubuntu 22.04"

- src/Bedrock/End2End/RupicolaCrypto/Broadcast.v
- src/Bedrock/End2End/RupicolaCrypto/Spec.v
> Adapt to https://github.com/coq/coq/pull/19530

- etc/ci/github-actions-make.sh
This should make it a bit easier to debug cases like https://github.com/mit-plv/fiat-crypto/pull/2009#issuecomment-2627878238
> Remove --output-sync from build log when make fails

- .github/workflows/coq-alpine.yml
- .github/workflows/coq-archlinux.yml
- .github/workflows/coq-debian.yml
- .github/workflows/coq-docker.yml
- .github/workflows/coq-macos.yml
- .github/workflows/coq-windows.yml
This may help with debugging https://github.com/mit-plv/fiat-crypto/pull/2009#issuecomment-2635374832
> Upload *.timing files on failure

- src/Arithmetic/BarrettReduction/Refined.v
This proves the correctness of the Barrett reduction strategy that is used for instance in Kyber/ML-KEM with regards to a signed modulo operation.
I haven't proved that this signed modulo operation gives rise to a field structure isomorphic to the usual one used in Fiat-Crypto, though it shouldn't be too hard if one needs it.
> Refined/Signed Barrett Reduction

- src/Bedrock/End2End/X25519/GarageDoor.v
- src/Bedrock/End2End/X25519/GarageDoorTop.v
Resolves #2007.
This needs mit-plv/bedrock2#445 to be merged first.
> switch GarageDoor to LeakageSemantics

- fiat-html/fiat-crypto.html
- fiat-html/main.js
- src/StandaloneJsOfOCamlMain.v
Also allow links that pass `&inputType=json` or `&inputType=string`.
This will allow us to run the assembly checker in HTML.  Currently the inputs are hidden, I haven't wired up the UI yet.
> [HTML] Add support for input and output files

- src/Util/Strings/ParseArithmetic.v
This conflicts with parsing it as a register.  Number literals that end in `h` to indicate hex must begin with a digit.
> Don't parse 'ah' as a hex number

- src/Assembly/Equality.v
- src/Assembly/Equivalence.v
- src/Assembly/EquivalenceProofs.v
- src/Assembly/Parse.v
- src/Assembly/Symbolic.v
- src/Assembly/Syntax.v
- src/Assembly/SyntaxTests.v
- src/Assembly/WithBedrock/Proofs.v
- src/Assembly/WithBedrock/Semantics.v
- src/Assembly/WithBedrock/SymbolicProofs.v
- src/Util/Listable.v
This is much faster, especially as we add more registers and opcodes
> Use Listable to prove equality of registers and opcodes

- src/Assembly/Parse.v
- src/Assembly/Parse/Examples/fiat_25519_all_clang_19_1_0_Os.v
- src/Assembly/Parse/TestAsm.v
- src/Assembly/Syntax.v
- src/Assembly/WithBedrock/Semantics.v
I want to be able to handle the output of gcc/clang on our C code.
Right now, I have added support for parsing the assembly output.
Equivalence checking is still to come.
Also still to come is parsing data declarations
> Add support for parsing more assembly

- src/Assembly/Equality.v
- src/Assembly/Parse.v
- src/Assembly/Syntax.v
The idea to parse `rip` specially rather than as a register is due to @andres-erbsen 
Supersedes #2023
Closes #2023
> Handle rip-relative addressing

- src/Assembly/Equivalence.v
- src/CLI.v
- src/PushButtonSynthesis/Primitives.v
It can be disabled with `--asm-label-exact-match`
> Allow fuzzy matching of assembly labels

- src/Assembly/Equivalence.v
- src/Assembly/Symbolic.v
- src/Assembly/WithBedrock/Proofs.v
- src/CLI.v
This flag results in running symex on the asm side first, resulting in easier debugging when there is an error in symbolically executing the assembly at all.
> Add `--debug-asm-symex-first`

- src/Assembly/Equivalence.v
This is less confusing when some simplification is missing.
> Print the node values of registers

- Makefile
- src/AbstractInterpretation/Wf.v
- src/Arithmetic/BaseConversion.v
- src/Arithmetic/Freeze.v
- src/Arithmetic/ModOps.v
- src/Bedrock/Group/AdditionChains.v
- src/Bedrock/Group/ScalarMult/CSwap.v
- src/Bedrock/Group/ScalarMult/MontgomeryLadder.v
- src/BoundsPipeline.v
- src/PushButtonSynthesis/BYInversionReificationCache.v
- src/PushButtonSynthesis/BarrettReductionReificationCache.v
- src/PushButtonSynthesis/BaseConversionReificationCache.v
- src/PushButtonSynthesis/DettmanMultiplicationReificationCache.v
- src/PushButtonSynthesis/FancyMontgomeryReductionReificationCache.v
- src/PushButtonSynthesis/Primitives.v
- src/PushButtonSynthesis/SaturatedSolinasReificationCache.v
- src/PushButtonSynthesis/SolinasReductionReificationCache.v
- src/PushButtonSynthesis/UnsaturatedSolinasReificationCache.v
- src/PushButtonSynthesis/WordByWordMontgomeryReificationCache.v
- src/Util/ZUtil/Pow.v
For compatibility with https://github.com/rocq-prover/rocq/pull/20373
Is someone willing to fix the issues that this causes so that fiat-crypto doesn't get removed from Coq's CI?  cf https://github.com/rocq-prover/rocq/pull/20373#issuecomment-2768550004
> Enable `+fragile-hint-constr`

- .github/workflows/coq-docker.yml
We no longer need to depend on the repository, we can just use the released version, now that it's been released.
> [CI] update wasm_of_ocaml

- etc/ensure_stack_limit.sh
mac os has a hard limit of `65520` not `66520`
> fix: ulimit typo

- .github/workflows/coq-windows.yml
This might fix the issue where Coq is failing to set printing width big enough?
cf https://github.com/mit-plv/fiat-crypto/issues/1394#issuecomment-2825962067
> Downgrade setup-ocaml to v3.2.16

- .github/workflows/coq-macos.yml
- Makefile.standalone
As per https://github.com/mit-plv/fiat-crypto/commit/4986ba94a6edc20fb09f82d9a1144c922ebd5fa5#r161506462, jsoo.6.1.0 includes significant memory usage improvements, and will hopefully work even work even with M1 GH Action runners which have only 7GB RAM.
cc @hhugo
> [CI] [MacOS] Enable JSOO again

- src/Assembly/WithBedrock/Semantics.v
- src/Assembly/WithBedrock/SymbolicProofs.v
- src/Bedrock/End2End/RupicolaCrypto/Broadcast.v
- src/Bedrock/Field/Common/Util.v
- src/Bedrock/Field/Synthesis/Generic/Bignum.v
- src/Bedrock/Group/AdditionChains.v
Cc @miriampolzer @lukaszobernig
This is the refactor I was talking about. It's not ready to land quite yet, but Fiat-crypto should build (but untested from clean build). You probably don't want to build on top of this branch, but perhaps it can be useful as a glimpse of things to come.
Key changes;
- [Scalars](https://github.com/mit-plv/bedrock2/compare/7a9231067c4bee29c2a6cd0b868281a28d669019...42910f02a8653edc2e12622079921968e157a7be#diff-ecabcc922edaeb5d11aca7cb817e8a72dc43591edfe439ddd7b0d16d90b568ffR22) are defined using `le_split`
- [Memory.v](https://github.com/mit-plv/bedrock2/compare/7a9231067c4bee29c2a6cd0b868281a28d669019...42910f02a8653edc2e12622079921968e157a7be#diff-11ec9d5dd13b52cadf5ab8a27aa5937c342dbc53d0ac0b8d0d5538de7b3cc7e8) rewritten, including definition of anybytes …
> Define Scalars, anybytes using $@ without tuples or ptsto_bytes

- .github/workflows/c.yml
We'd like to have them back, but right now they are just failing
> Disable BoringSSL-integration tests

- src/Bedrock/End2End/X25519/EdwardsXYZT.v
Convert the doubling function to a point based format, the rest of the functions will follow.
> Ed25519: Point-based separation logic for doubling

- src/Bedrock/Group/AdditionChains.v
- src/Bedrock/Secp256k1/Addchain.v
- src/Bedrock/Secp256k1/JoyeLadder.v
I will change program_logic_goal_for to not reduce functions automatically. Prepare fiat-crypto by removing automatic goal creation or normalizing before calling the goal-creation tactic.
Not blindly calling cbv on function definitions will allow us to use parameterized functions without having to worry about unnecessary slow unfolding.
> Reduce function definitions before goal creation
