mit-plv/fiat-crypto

folkwisdom.md

I dug through my email archive and consolidated bits of advice that enabled us to build fiat-crypto to the extent it is a thing now. The first pass turned out about 2k5 words. If you feel like doing soft-technical work for a while, read it and comment here what you think. Hopefully there will be consensus on some of the points, which we would then commit to the repository.
What else could be covered:

Document "folk wisdom" tips that would have been good to know

---

.dir-locals.el.in
.gitignore
Makefile

This fixes #31
Thanks @cpitclaudel!

Add target for .dir-locals.el

---

_CoqProject
src/ModularArithmetic/BarrettReduction/ZHandbook.v

From http://cacr.uwaterloo.ca/hac/about/chap14.pdf
This should take care of most of #43, at least the specification on Z
part of it.

Implement Barrett Reduction following HAC 14.42

---

src/Assembly/Pseudize.v
src/Assembly/Pseudo.v
src/Util/Notations.v

@JasonGross sorry it took me so long to fix this

Remove unnecessary pseudo notations

---

src/ModularArithmetic/ModularBaseSystemOpt.v

By using reflection, we can speed up the overall build time by about
half a minute.  By fully reducing [base_from_limb_widths] once we plug
in arguments, and not before, we can get about another half-minute in
8.5pl2 (and a great deal more in 8.6, where vm_compute no longer is
slow; see https://coq.inria.fr/bugs/show_bug.cgi?id=5004).
Times in 8.5pl2:
```
After    | File Name                                | Before   || Change
---------------------------------------------------------------------------
0m27.80s | Total                                    | 1m19.59s || -0m51.78s
---------------------------------------------------------------------------
0m04.71s | Experiments/SpecificCurve25519           | 0m26.78s || -0m22.07s
0m17.13s | Specific/GF25519                         | 0m39.10s …
```

Massively speed up construct_params

---

src/Specific/GF25519.v

```
After    | File Name                      | Before   || Change
-----------------------------------------------------------------
0m13.37s | Total                          | 0m40.29s || -0m26.91s
-----------------------------------------------------------------
0m10.09s | Specific/GF25519               | 0m37.00s || -0m26.91s
0m03.29s | Experiments/SpecificCurve25519 | 0m03.30s || -0m00.00s
```
Making this a PR because I don't want to step on anyone's toes.  (Also, I didn't bother to change it here because I didn't notice it until just now, but `repeat progress` and `repeat` have the same behavior.)

Speed up src/Specific/GF25519.v

---

src/Experiments/Ed25519.v

As per https://github.com/mit-plv/fiat-crypto/commit/d8f43bab543bfcf38df73ab92baa8c6cdee5c869#commitcomment-19475250

Fill in some things in Ed25519 from SC25519

---

src/Experiments/Ed25519.v
src/Util/WordUtil.v

Most of the admits in Ed25519.v are already proved. Keeping this PR open 'til I prove the rest.
I'll refactor the proofs I imported into WordUtil later: I know they're messy.
@JasonGross

New Word/Z Util Lemmas

---

src/Util/WordUtil.v

Lemmas about winit, wlast

---

.travis.yml
Makefile

This closes #121 and closes #124

Remove display .vo from default target

---

.travis.yml

[travis] Only build the lite target on Coq 8.5

---

_CoqProject
src/Reflection/Named/MapCast.v
src/Reflection/Named/MapCastInterp.v

Based on @andres-erbsen's work towards #123.
I haven't ported the example from #123, though I kept the statement of the correctness lemma basically the same (modulo changing the form of the equality-decidability we require for names and base-type-codes).

Add a Named version of MapCast

---

src/Algebra/Field.v
src/Algebra/Field_test.v
src/CompleteEdwardsCurve/CompleteEdwardsCurveTheorems.v
src/Spec/MontgomeryCurve.v
src/WeierstrassCurve/WeierstrassCurveTheorems.v

Closes #114 
May travis have fun.

Make fsatz recurse on nonzeroness-subgoals

---

src/NewBaseSystem.v

This works around [bug #5434](https://coq.inria.fr/bugs/show_bug.cgi?id=5434) that `vm_compute` breaks an invariant asserted on [line 115 of `pretyping/constr_matching.ml`](https://github.com/coq/coq/blob/V8.6/pretyping/constr_matching.ml#L115).  This was triggering whenever we tried to reify one of the operations.
Does this seem fine to you two, @jadephilipoom and @andres-erbsen ?
N.B. This commit cannot work with Coq 8.4, unless I do some typeclass hackery that I didn't want to bother with.

Work around bug #5434

---

_CoqProject
src/Reflection/Z/ArithmeticSimplifier.v
src/Reflection/Z/ArithmeticSimplifierInterp.v
src/Reflection/Z/ArithmeticSimplifierUtil.v
src/Reflection/Z/ArithmeticSimplifierWf.v
src/Reflection/Z/Bounds/Interpretation.v
src/Reflection/Z/Bounds/InterpretationLemmas.v
src/Reflection/Z/Reify.v
src/Reflection/Z/Syntax.v
src/Reflection/Z/Syntax/Equality.v
src/Reflection/Z/Syntax/Util.v

Needed for opp_sig, ladderstep

Support Z.opp in reification

---

Makefile
_CoqProject
src/Specific/IntegrationTestLadderstep.v

I believe this fully refines the ladderstep goal.  It takes forever to run (I haven't seen it finish yet, but it seems to be making slow by steady progress).
The tactic invocations on my side of the pipeline are expanded so that we can see timing data; the sequence is identical to an invocation of `refine_reflectively`.

Add IntegrationTestLadderstep.v

---

_CoqProject
src/Util/ForLoop.v
src/Util/ForLoop/Instances.v
src/Util/ForLoop/InvariantFramework.v
src/Util/ForLoop/Tests.v
src/Util/ForLoop/Unrolling.v

Also fix bugs in for-loop definition to make the proofs go through

Add loop invariant framework for for-loops

---

_CoqProject
src/Arithmetic/MontgomeryReduction/WordByWord/Definition.v

I think I got the loop itself wrong, though:
1. I'm worried that it'll overflow off the end of the positional
representation, since I'm not actually dividing by 2^s
2. I'm not carrying/reducing anywhere, so the getting the nth value
might be wrong
3. I'm not sure if I got indexing right.
But I want to submit this early version to get comments from @andres-erbsen, before I put
more effort into it.

Initial stab at word-by-word montgomery

---

_CoqProject
src/Specific/IntegrationTestKaratsubaMul.v
src/Specific/IntegrationTestKaratsubaMulDisplay.v

This closes #182.
Currently, it doesn't build.  When you try to run `make`, you'll get an error indicating how Karatsuba overflows its bounds.  When karatsuba mul is correctly bounded, this should pass fine.

Finish karatsuba mul, add display file

---

src/Arithmetic/MontgomeryReduction/WordByWord/Proofs.v
src/Arithmetic/Saturated.v

You could probably write a better proof than I could, since you have more knowledge of and familiarity with the underlying building blocks, but I got nerdsniped.  @jadephilipoom I'll leave this for you to decide what to do with.

Weaken preconditions on small_add

---

_CoqProject
src/Arithmetic/Core.v
src/Arithmetic/MontgomeryReduction/WordByWord/Definition.v
src/Arithmetic/MontgomeryReduction/WordByWord/Proofs.v
src/Arithmetic/Saturated.v
src/Compilers/Z/Bounds/Pipeline/Glue.v
src/Specific/IntegrationTestMontgomeryP256_128_Nonzero.v
src/Specific/IntegrationTestMontgomeryP256_128_NonzeroDisplay.log
src/Specific/IntegrationTestMontgomeryP256_128_NonzeroDisplay.v
src/Specific/MontgomeryP256_128.v
src/Specific/NISTP256/AMD64/IntegrationTestMontgomeryP256_Nonzero.v
src/Specific/NISTP256/AMD64/IntegrationTestMontgomeryP256_NonzeroDisplay.log
src/Specific/NISTP256/AMD64/IntegrationTestMontgomeryP256_NonzeroDisplay.v
src/Specific/NISTP256/AMD64/MontgomeryP256.v

@jadephilipoom Can you sanity check / ack the changes to `Saturated.v`?
@andres-erbsen Does the spec seem fine to you?

Synthesize Nonzero

---

.gitignore
Makefile
src/Arithmetic/MontgomeryReduction/WordByWord/Definition.v
src/Arithmetic/MontgomeryReduction/WordByWord/Proofs.v
src/Arithmetic/Saturated.v
src/Compilers/CommonSubexpressionEliminationInterp.v
src/Compilers/Z/CNotations.v
src/Specific/IntegrationTestMontgomeryP256_128Display.log
src/Specific/IntegrationTestMontgomeryP256_128_AddDisplay.log
src/Specific/IntegrationTestMontgomeryP256_128_OppDisplay.log
src/Specific/IntegrationTestMontgomeryP256_128_SubDisplay.log
src/Specific/MontgomeryP256_128.v
src/Specific/NISTP256/AMD64/IntegrationTestMontgomeryP256Display.log
src/Specific/NISTP256/AMD64/IntegrationTestMontgomeryP256_AddDisplay.log
src/Specific/NISTP256/AMD64/IntegrationTestMontgomeryP256_OppDisplay.log
src/Specific/NISTP256/AMD64/IntegrationTestMontgomeryP256_SubDisplay.log
src/Specific/NISTP256/AMD64/MontgomeryP256.v
src/Util/ZUtil/AddGetCarry.v
src/Util/ZUtil/Definitions.v

As per #222. Putting this up early so we can try to make code from it, but it's unpolished--there are currently several admitted proofs and context variables don't line up.

Smarter addition/subtraction chains

---

Makefile

@andres-erbsen Are you fine with using more makefile variables and less copy-paste?

Update Makefile by deduplicating some file lists

---

src/Compilers/Z/Bounds/Interpretation.v
src/Compilers/Z/Bounds/InterpretationLemmas/IsBoundedBy.v

This makes it easier to extend the bounds analysis framework.

Factor out truncation_bounds

---

.travis.yml

Update .travis.yml from 8.7+beta2 to 8.7.0

---

src/Arithmetic/Saturated/MontgomeryAPI.v

One of them is Admitted; @jadephilipoom , can you prove it?  (Note that this is a special case of #257.)

Add MontgomeryAPI.encode and two lemmas about it

---

src/Experiments/SimplyTypedArithmetic.v

This will make it easier to reify
This is on top of #271

[Demo] Define [place] in terms of nat_rect

---

src/Experiments/SimplyTypedArithmetic.v

Oops, forgot this in #271.  Planning to merge this soon.

[demo] Replace (max (length a) (length b)) with explicit nat arg

---

src/Experiments/Loops.v

Here is a cleaned up version of the loop framework @jadephilipoom  wrote a while back. I am considering using this for boringssl ed25519, so go, critique. Current point of uncleaniness
1. Handling termination in lemma statements `loop` vs `loop_default`, `while` vs `while_default`
2. Namespacing, naming
Notations would be desirable, but let's worry about that after we figure out the semantics.

Loops (trying again)

---

src/Curves/Montgomery/XZ.v
src/Curves/Montgomery/XZProofs.v
src/Experiments/Loops.v
src/Util/QUtil.v

@davidben was not able to jump into this file earlier, so a cleanup is warranted. Unfortunately this change causes a slowdown in the biggest proof, 19s -> 160s. It is possible that the speed could be re-gained with less mess than this file contained before...

Curves.Montgomery.XZProofs overhaul

---

CONTRIBUTORS
src/Curves/Montgomery/XZProofs.v

This is largely copy-pasted from the other one. I also have no clue what I'm doing, so feel free to ask me to change things arbitrarily.

Prove montladder correct in the zero case.

---

src/Util/ZUtil/Peano.v

Add a comment for why Z.peano_rect_strong exists.

---

src/Curves/Montgomery/XZProofs.v

This required tending to montladder not being proved Feq-preserving
(sidestepped by proving for all P = 0), and then some wrestling with
scalarmult to show the right-hand side was indeed zero when x is (0, 0).

Combine the zero and non-zero cases together.

---

src/Experiments/SimplyTypedArithmetic.v

We now do bounds analysis in experiments.  This is the minimum product necessary to prototype the idea; there are a number of admits, mostly arounds bounds proofs, but also around casting.  My hope is that, with feedback, we can turn this into something more reasonable.  Please question everything that seems the least bit unfortunate.
I created this as a pull request to take advantage of GitHub's review infrastructure.

[Work in Progress] Experiment with Bounds Analysis based on lists

---

src/Experiments/SimplyTypedArithmetic.v

See also #300.
We take the simple path of pulling all of the constant multiplication of
sufficiently small size to the end of any expression like a * b * c * d
* ..., and then we associate all addition and multiplication all the way
to the right.  This might be very much the wrong choice in some cases;
I invite suggestions that don't require knowing any bounds, which
perform better.  (Doing things that require bounds would complicate this
significantly.)
I have no idea why this reassociation results in this part of the diff:
```diff
expr_let 15 := (uint64)(x_14 >> 51) in
expr_let 16 := ((uint64)x_14 & 2251799813685247) in
- expr_let 17 := x_4 +₆₄₋₆₄₋₆₄ (19) *₃₂₋₆₄₋₆₄ x_15 in
- expr_let 18 := (uint32)(x_17 >> 51) in
+ expr_let 17 := x_4 +₆₄ x_15 *₆₄₋₆₄₋₆₄ (19) in
+ expr_let 18 := …
```

[experiments] Use smaller multiplication for 19*x

---

src/Experiments/SimplyTypedArithmetic.v

The proper cps transform of
```
if b then (let x := y in z) else w
```
is
```
cps b (fun b' =>
if b'
then cps y (fun y'
=> let x := y' in cps z k)
else cps w k
```
not
```
cps b (fun b' =>
cps y (fun y' =>
let x := y' in
cps z (fun z' =>
cps w (fun w' =>
if b' then k z' else k w')
```
So we fix the cps transform, and remove the now useless dead code
elimination.  The partial reduction pipeline is now 2x faster.

Fix CPSify of bool_rect to eliminate dead code

---

src/Experiments/SimplyTypedArithmetic.v

I've added a couple of operations to the experiments arithmetic stuff, and left some `Axiom`s for @jadephilipoom to fill in.  Mostly copied from `Arithmetic.Core`, so I might have messed up some naming conventions or stuff.

[experiments] Add some more arithmetic operations

---

src/Experiments/SimplyTypedArithmetic.v

On top of #330 
This adds a pass which inline let-bound variables which are used at most once.

NoBrainer cps 1

---

src/Experiments/SimplyTypedArithmetic.v

Most of the changes are due to the fact that the PrePipeline (cache)
part no longer errors, and the pre-check post-cache part of the pipeline
can now error.
Note that this slows rcarry_mul down from about 0.3 s to about 2.6 s
(some of which is probably counter-balanced by the fact that caching is
probably now faster).

Move cps out of cache part of the pipeline

---

src/Experiments/SimplyTypedArithmetic.v

- Since we pass through a flat representation, we no longer need to
invoke `vm_compute` twice, so we don't need to separate out bounds
checking from bounds analysis
- Only call partial evaluation once, not twice
- Remove the call to constant reassociation, as it no longer has a place
(it only works post-partial-evaluation pre-bounds-analysis)

Do some pipeline consolidation and reorganization

---

src/Experiments/NewPipeline/Arithmetic.v

I also add a bunch of `Proof using` for ease of use with PG-async

Add [freeze] to Arithmetic

---

src/Util/FixCoqMistakes.v

Also make it easy to redeclare such instances.

Prefer relations of the form [eq ==> eq ==> ... ==> eq] in setoids

---

_CoqProject
src/Experiments/NewPipeline/LanguageWf.v

```
After    | File Name                          | Before   || Change    | % Change
--------------------------------------------------------------------------------
0m10.67s | Total                              | 0m00.00s || +0m10.67s | N/A
--------------------------------------------------------------------------------
0m10.68s | Experiments/NewPipeline/LanguageWf |   N/A    || +0m10.67s | ∞
```

Add basic wf proofs

---

src/Arithmetic/CoreUnfolder.v

https://github.com/coq/coq/pull/8200

Backwards compatible fix for some issues from https://github.com/coq/coq/pull/8200

---

src/Experiments/NewPipeline/AbstractInterpretation.v
src/Experiments/NewPipeline/AbstractInterpretationProofs.v

It was a premature optimization
```
After     | File Name                                            | Before    || Change    | % Change
----------------------------------------------------------------------------------------------------
12m57.07s | Total                                                | 12m59.91s || -0m02.84s | -0.36%
----------------------------------------------------------------------------------------------------
5m49.37s  | Experiments/NewPipeline/SlowPrimeSynthesisExamples   | 5m49.86s  || -0m00.49s | -0.14%
4m31.64s  | Experiments/NewPipeline/Toplevel1                    | 4m32.60s  || -0m00.96s | -0.35%
1m33.27s  | Experiments/NewPipeline/Toplevel2                    | 1m33.94s  || -0m00.66s | -0.71%
0m44.30s  | Experiments/NewPipeline/AbstractInterpretationProofs …
```

Remove thunking from abstract interpretation

---

src/Experiments/NewPipeline/AbstractInterpretation.v
src/Experiments/NewPipeline/AbstractInterpretationProofs.v
src/Experiments/NewPipeline/AbstractInterpretationWf.v
src/Experiments/NewPipeline/LanguageWf.v

Otherwise we'd have to pipe Wf3 hypotheses around everywhere

Add another GeneralizeVar pass to add support for using Wf3

---

src/Experiments/NewPipeline/AbstractInterpretation.v
src/Experiments/NewPipeline/AbstractInterpretationProofs.v

Also, we now pull bounds out of the initial expression, rather than the
final expression, because it makes the proofs easier.  (It means we only
have to run bounds analysis with one var type, not talk about its
relatedness with multiple var types.)

Push back admits in interp lemmas

---

README.md

The readme gives a close but not correct location for the remake_curves.sh script.

README: note remake_curves.sh is in Specific/CurveParameters

---

src/Experiments/NewPipeline/AbstractInterpretation.v

We used to claim that casts brought values into the intersection of the
known range and the casted range.  This is absurd, in the same way that
it's absurd to claim that attempting to dereference a pointer guarantees
that it's non-null.  Instead, we pass through bounds that fit soundly
within the casted range, and otherwise guarantee nothing about the
bounds of the resulting code.

Don't guarantee anything about casting outside of range

---

src/Experiments/NewPipeline/LanguageWf.v

This reverts commit 29f1c8b447294b4a0a6a5127c6db23d54d43343f.
Try to be more judicious about instances

Revert "Revert "Add more instances for type.related""

---

Makefile
README.md
src/Experiments/NewPipeline/CLI.v
src/Experiments/NewPipeline/Toplevel1.v

The documentation is very minimal at the moment, but I plan to update it
with more details in the near future.
cc @agl @davidben

Add some documentation to README about the new pipeline

---

src/Experiments/NewPipeline/AbstractInterpretation.v
src/Experiments/NewPipeline/AbstractInterpretationProofs.v
src/Experiments/NewPipeline/AbstractInterpretationWf.v
src/Experiments/NewPipeline/Toplevel1.v

This was an enormous pain, because although we don't actually
bounds-analyze higher-order functions, we need to make sure that we
discard the bounds information about them in exactly the same way in
multiple places.
The only remaining admits in bounds analysis are the fancy machine bounds proofs.

Finish interp proof of abstract interpretation

---

src/Experiments/NewPipeline/Arithmetic.v
src/Experiments/NewPipeline/Toplevel1.v

I also stripped off the latest 2 commits from that PR because a) I accidentally introduced a syntax error in 8.7 and b) they weren't actually that related to the change. Will be merged once the build completes.

Rebased version of #434

---

src/Specific/Framework/ArithmeticSynthesis/Montgomery.v

Based on hints from @andres-erbsen

Compatibility with Coq PR#8457

---

src/Util/GlobalSettings.v

Enable the option of https://github.com/ppedrot/coq/tree/faster-namegen
Should be a no-op in 8.8, 8.9, current master, etc.  Hopefully @ppedrot will make a PR from his branch and merge soon.
```
After     | File Name                                                                  | Before    || Change    | % Change
--------------------------------------------------------------------------------------------------------------------------
91m26.27s | Total                                                                      | 94m51.65s || -3m25.38s | -3.60%
--------------------------------------------------------------------------------------------------------------------------
2m45.41s  | Experiments/NewPipeline/SlowPrimeSynthesisExamples.vo                      | 6m11.63s  || -3m26.21s | …
```

Global Set Fast Name Printing

---

src/Experiments/NewPipeline/RewriterWf1.v

We now use interp-relatedness of values primarily to define an "ok"
relation on them, and thereafter mostly talk about expr-interping the
reified value.  This will hopefully be easier to prove things about.
Idea came from Andres, after much discussion between me and Andres and
Adam.

Refactor interpretation of values

---

src/Experiments/NewPipeline/Arithmetic.v

uweight_partition_unique can probably be generalized to not be specific to uniform weights, but that is left to a future person.

Add uweight_partition_unique, move weight_1 to uweight_1, add Positional.eval_map_mul

---

src/LegacyArithmetic/ArchitectureToZLikeProofs.v
src/LegacyArithmetic/ZBoundedZ.v

This option is soon going to be turned off by default. See
https://github.com/coq/coq/pull/9270

Do not rely on `Refine Instance Mode`

---

README.md

will merge tonight if no objections

link to papers in readme

---

.travis.yml
Makefile

https://github.com/mit-plv/fiat-crypto/pull/483#pullrequestreview-191513529

Remove unused variable from Makefile

---

src/Rewriter.v
src/RewriterInterpProofs1.v
src/RewriterWf1.v
src/arith_rewrite_head.out
src/arith_with_casts_rewrite_head.out
src/fancy_with_casts_rewrite_head.out
src/nbe_rewrite_head.out

We never used the cps form, and this form is easier to read.

Uncps unify_extracted

---

src/AbstractInterpretationWf.v
src/Arithmetic.v
src/CStringification.v
src/Language.v
src/LanguageWf.v
src/Primitives/EdDSARepChange.v
src/RewriterProofs.v
src/RewriterRulesGood.v
src/RewriterWf1.v
src/RewriterWf2.v
src/UnderLetsProofs.v
src/Util/Option.v
src/Util/OptionList.v

These will be useful for extending the AST with `option` types.

Add Option.{lift,map,combine}, List.Option.lift

---

Makefile

Otherwise write to .c.tmp file

Only write to .c files on success

---

src/Arithmetic.v
src/Arithmetic/BarrettReduction/Generalized.v
src/Fancy/Barrett256.v
src/Fancy/Montgomery256.v
src/PushButtonSynthesis/BarrettReduction.v
src/PushButtonSynthesis/BarrettReductionReificationCache.v
src/PushButtonSynthesis/MontgomeryReduction.v
src/Rewriter.v
src/Util/ZUtil/Divide.v
src/Util/ZUtil/Pow.v

This is #533, rebased on top of the removal of 8.7 support and other changes to master that happened in the meantime.

Generalize barrett2

---

package-rewriter.sh

For the rewriter paper
Any objection to having this in master, @andres-erbsen ?

Add a package-rewriter.sh script

---

.travis.yml
etc/ci/travis.sh

Hopefully this will fix intermittant problems on travis.
c.f. https://travis-ci.org/mit-plv/fiat-crypto/jobs/559167924

Use -j1 on travis for the coq target

---

src/CStringification.v
src/IR.v

Regenerated C files and the exact same output is produced.

Parameterized PHOAS translation over language-specific numeric conversions

---

src/Arithmetic/ModularArithmeticPre.v
src/Util/Tuple.v

See https://github.com/coq/coq/issues/10474 and
https://github.com/coq/coq/issues/10480
This should be backward compatible, but it remains to be tested.

Avoid relying on `Export` bugs

---

.travis.yml
Makefile
etc/ci/travis.sh
fiat-rust/src/curve25519_32.rs
fiat-rust/src/curve25519_64.rs
fiat-rust/src/p224_32.rs
fiat-rust/src/p224_64.rs
fiat-rust/src/p256_32.rs
fiat-rust/src/p256_64.rs
fiat-rust/src/p384_32.rs
fiat-rust/src/p384_64.rs
fiat-rust/src/p434_64.rs
fiat-rust/src/p448_solinas_64.rs
fiat-rust/src/p521_32.rs
fiat-rust/src/p521_64.rs
fiat-rust/src/secp256k1_32.rs
fiat-rust/src/secp256k1_64.rs

@zoep is "nightly" the right version of the Rust compiler to use?

Test Rust on travis

---

.travis.yml
etc/ci/travis.sh

Don't rebuild rust files before testing them

---

_CoqProject
src/AbstractInterpretation.v
src/AbstractInterpretationZRangeProofs.v
src/IR.v
src/IdentifiersGENERATED.v
src/Language.v
src/LanguageStringification.v
src/Rewriter.v
src/Util/ZUtil/Definitions.v
src/Util/ZUtil/TruncatingShiftl.v

See #524 for discussion and justification.

Add Z.truncating_shiftl

---

src/Language/Identifier.v

This one should be more amenable to automation
Timing difference is probably all/mostly noise

Use a different def of try_make_base_transport_cps

---

src/AbstractInterpretation/Proofs.v
src/AbstractInterpretation/ZRangeProofs.v
src/Fancy/Compiler.v
src/Language/Identifier.v
src/Language/Language.v
src/Rewriter/AllTactics.v
src/Rewriter/ProofsCommon.v
src/Rewriter/ProofsCommonTactics.v

In preparation for automating things

Be more uniform about interpreting identifiers

---

src/Rewriter/Rules.v
src/Rewriter/RulesProofs.v
src/Util/ZRange/BasicLemmas.v
src/Util/ZUtil/Land.v
src/Util/ZUtil/Tactics/ZeroBounds.v

Prove mul_split admits

---

src/Language/IdentifiersBasicGenerate.v
src/Language/IdentifiersGenerate.v
src/Language/Pre.v
src/Rewriter/AllTactics.v

Add tactics to scrape the initial data from rewrite rules

---

Makefile

This should reduce the build noise a bit more, and make things faster

Bump submodule and only make bedrock2 noex

---

src/Language/IdentifiersBasicGenerate.v
src/Language/IdentifiersBasicLibrary.v
src/Language/IdentifiersGenerate.v
src/Language/IdentifiersGenerateProofs.v
src/Language/Pre.v
src/Rewriter/AllTactics.v

It is now much faster.
I also fixed some incorrect-number-of-arguments issues with some
tactics, and copied over some utility notations which will prove helpful
when moving to OCaml.

Speed up generation of invertIdent{,AndCorrect}

---

src/Language/IdentifiersBasicGenerate.v
src/Language/Pre.v

Not used yet, but will be helpful for the OCaml code.

Better heuristic processing for lists of rewrite lemmas

---

src/Rewriter/AllTactics.v

Maybe this will speed things up?  We'll see.

Revert a needless cache_term

---

src/Rewriter/Rules.v
src/Rewriter/RulesProofs.v

c.f.
https://github.com/mit-plv/fiat-crypto/issues/524#issuecomment-540059615
@jadephilipoom Does this fix the 32-bit bedrock2 compilation?

Better conversion to 32-bit for bedrock2

---

src/Language/IdentifiersGenerate.v
src/Rewriter/Reify.v

This will make it easier to extract as a separate repo

Make the rewriter core not depend on zrange

---

Makefile
_CoqProject
src/AbstractInterpretation/Proofs.v
src/AbstractInterpretation/Wf.v
src/AbstractInterpretation/ZRangeProofs.v
src/Algebra/Ring.v
src/Arithmetic/BarrettReduction.v
src/Arithmetic/BaseConversion.v
src/Arithmetic/Core.v
src/Arithmetic/Freeze.v
src/Arithmetic/ModOps.v
src/Arithmetic/PrimeFieldTheorems.v
src/Arithmetic/Saturated.v
src/Arithmetic/WordByWordMontgomery.v
src/CompilersTestCases.v
src/Fancy/Compiler.v
src/PushButtonSynthesis/UnsaturatedSolinas.v
src/StandaloneOCamlMain.v
src/Util/CPSUtil.v
src/Util/Decidable/Bool2Prop.v
src/Util/ListUtil.v
src/Util/Strings/ParseArithmetic.v
src/Util/Strings/String_as_OT.v
src/Util/ZUtil/AddGetCarry.v

The build output is now a bit less noisy.
Requesting review about making these things errors (not about the individual changes).

Fix a bunch of warnings and turn them into errors

---

src/CLI.v
src/Util/Strings/ParseArithmetic.v
src/Util/Strings/Show.v

e.g., we now can parse 25.5, and we print any fraction whose denominator
is a power of 10 as a decimal.

Allow parsing and printing fractions from decimal

---

src/Arithmetic/Primitives.v
src/BoundsPipeline.v
src/CLI.v
src/PushButtonSynthesis/Primitives.v
src/PushButtonSynthesis/SaturatedSolinas.v
src/PushButtonSynthesis/UnsaturatedSolinas.v
src/PushButtonSynthesis/WordByWordMontgomery.v
src/Rewriter/PerfTesting/Core.v
src/SlowPrimeSynthesisExamples.v

Add an alternate implementation of cmovznz

---

src/CLI.v
src/COperationSpecifications.v
src/PushButtonSynthesis/BaseConversion.v
src/PushButtonSynthesis/Primitives.v

We add more configurability to base conversion.  Since #640 seems stuck waiting for feedback, I've copied over the straightforward improvements here, without touching the methods in arithmetic

Some minor improvements to CLI.v & base conversion

---

.github/workflows/coq.yml

[ci] Also test Haskell standalone binaries

---

.gitmodules

Needed to make the upcoming Windows CI work nicely

Bump bedrock2

---

_CoqProject
src/Util/MSets/Iso.v
src/Util/Structures/Equalities/Iso.v
src/Util/Structures/Orders/Iso.v

Add MSets/Iso

---

src/Util/Bool/Reflect.v
src/Util/Sum.v

<p>
```
After |   Peak Mem | File Name                                                    |    Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
84m16.75s | 2689648 ko | Total Time / Peak Mem                                        | 84m04.98s | 2689084 ko || +0m11.76s ||       564 ko |   +0.23% |         +0.02%
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
8m31.50s | 2689648 ko | Curves/Weierstrass/AffineProofs …
```

Add some more things about `sum`

---

_CoqProject
src/Util/MSets/Sum.v
src/Util/Structures/Equalities/Sum.v
src/Util/Structures/Orders.v
src/Util/Structures/Orders/Sum.v

This, combined with MSets.Iso, will let us make an MSet based on
MSetPositive for int.type in the stringification machinery.

Add Crypto.Util.MSets.Sum

---

src/Util/GlobalSettings.v

Closes #700
See #700 for discussion

Unset Fast Name Printing

---

src/Rewriter/Rules.v

It was resulting in inconsistent handling of adc/sbb depending on
whether they were introduced by rewrite rules vs not.  However, it
didn't actually impact any code generation, so this is primarily just
for consistency.

Don't introduce literals without casts in rewrite rules

---

.github/workflows/c.yml
.github/workflows/coq.yml

cf https://github.com/actions/virtual-environments/issues/675

Work around azure timeouts on GitHub actions, hopefully

---

.github/workflows/rust.yml
etc/ci/test-fiat-rust.sh

Hopefully this will prevent us from breaking the Rust code.
Closes #705
Thanks to @huitseeker for instructions on how to do this

Use curve25519-dalek to test fiat-rust on CI

---

.github/workflows/coq-macos.yml
.github/workflows/coq-windows.yml
.github/workflows/coq.yml
etc/ci/github-actions-display-per-line-timing.sh
etc/ci/github-actions-make.sh

This will let us see per-line timings on the CI

Add timing files for the ci

---

src/BoundsPipeline.v

This should speed it up.
Given that the generated code changed almost not at all (the only change
was making the fancy options a primitive record), I'm assuming that the
changes seen in the p384 files are just noise resulting from varying
machine load.
<p>
```
After |   Peak Mem | File Name                                       |    Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
----------------------------------------------------------------------------------------------------------------------------------------------------------
38m34.34s | 1817452 ko | Total Time / Peak Mem                           | 38m25.47s | 1816956 ko || +0m08.86s ||       496 ko |   +0.38% |         +0.02% …
```

BoundsPipeline proof: custom automation

---

.github/workflows/coq.yml

Maybe this'll work around
https://gitlab.haskell.org/ghc/ghc/issues/18038 ?

Don't parallelize the extraction-haskell build

---

.github/workflows/coq-macos.yml
.github/workflows/coq-windows.yml
.github/workflows/coq.yml
.gitignore

Closes #717
Let's see how much this slows things down on the CI...

Also run coqchk on the CI

---

.github/workflows/coq-windows.yml

To work around COQBUG(https://github.com/coq/coq/issues/12072)

[ci] [windows] Switch to V8.11.1

---

.github/workflows/coq-windows.yml

as per
https://github.com/actions/virtual-environments/issues/698#issuecomment-612882856

Add download retry logic on Windows

---

_CoqProject
src/Bedrock/Tests/Proofs/X1305_32.v
src/Bedrock/Tests/X1305_32.v

Closes #761
Easy to add, just a copy-pasting of 32-bit curve25519. Right now, like the other tests, it translates multiplication and addition and has proofs only about multiplication. There's no reason that adding more would be complicated except that I'd like to make stuff nice and clean and automated before I do more copy-pasting (see #764).

Bedrock2 poly1305 test with proofs

---

_CoqProject
src/Rewriter/RulesProofs.v
src/Util/ZUtil/AddGetCarry.v
src/Util/ZUtil/Ltz.v

As discussed in https://github.com/mit-plv/fiat-crypto/pull/749#discussion_r409675126

Add ZUtil/Ltz.v

---

.gitignore
Makefile

Backwards compatible version of #793
Closes #793

[coq] Backwards-compatible: Adapt to coq/coq#11980 : Improvements on Print Assumptions

---

src/PushButtonSynthesis/Primitives.v

This is required for #670.
We now do a bit more post-processing of the correctness conditions,
including inlining `let '(x, y) := z in ...` expressions, reducing `fst
(x, y)` and `snd (x, y)`, and pulling tuples outside of `if` statements.

Improve stringification of correctness conditions

---

.github/workflows/c.yml
Makefile
etc/ci/test-fiat-c-boringssl.sh

Significant work on #708
@davidben Please review for this being the correct way to patch, build, and run tests on BoringSSL.

Test C and bedrock2 code with BoringSSL

---

_CoqProject
src/Bedrock/Arrays/MaxBounds.v
src/Bedrock/Field/Bignum.v
src/Bedrock/Field/Operation.v
src/Bedrock/Field/Tactics.v
src/Bedrock/Field/UnsaturatedSolinas.v
src/Bedrock/Field/WordByWordMontgomery.v
src/Bedrock/Proofs/Equivalence.v
src/Bedrock/Proofs/EquivalenceProperties.v
src/Bedrock/Proofs/Expr.v
src/Bedrock/Proofs/Flatten.v
src/Bedrock/Proofs/Func.v
src/Bedrock/Proofs/LoadStoreList.v
src/Bedrock/Proofs/ValidComputable/Expr.v
src/Bedrock/Synthesis/Examples/EncodeDecode.v
src/Bedrock/Synthesis/Examples/LadderStep.v
src/Bedrock/Synthesis/Examples/MulTwice.v
src/Bedrock/Synthesis/Examples/p224_64.v
src/Bedrock/Synthesis/Examples/p256_64.v
src/Bedrock/Synthesis/WordByWordMontgomery.v
src/Bedrock/Translation/Expr.v

On top of #828 
Adds proofs and synthesis tactics for bedrock2 word-by-word Montgomery, and a few examples.

Bedrock2 word-by-word Montgomery

---

.github/workflows/coq-macos.yml

[ci] Try using the latest version of Homebrew

---

src/Util/ListUtil.v
src/Util/ZUtil/Hints/Ztestbit.v
src/Util/ZUtil/Shift.v
src/Util/ZUtil/Testbit.v

From developing a theory of bitwise bounds

Add some more helper lemmas

---

_CoqProject
src/Util/ListUtil.v
src/Util/ZUtil/Bitwise.v
src/Util/ZUtil/Hints/Ztestbit.v
src/Util/ZUtil/Shift.v
src/Util/ZUtil/Stabilization.v
src/Util/ZUtil/Testbit.v

This is important for proving a tighter bound on the bitwise zrange
operations.

Add a theory of bitlists and bitwise

---

src/Arithmetic/BarrettReduction.v
src/Arithmetic/Partition.v
src/Util/ListUtil.v
src/Util/NatUtil.v

This came up as part of the alternate solution to #857 
@jadephilipoom does this seem fine to you?

Add more utility lemmas

---

output-tests/Crypto.Fancy.Barrett256.prod_barrett_red256_correct.Assumptions.expected
output-tests/Crypto.Fancy.Montgomery256.prod_montred256_correct.Assumptions.expected

Bump the rewriter to remove funext
There were two insights that went into making it possible to remove
functional extensionaliy.
1. The insight that went into 4d7999ebb66c1497222d024a1d9f9d0f1ecb2356:
interp-relatedness implies equivalence.
2. Requiring `f x = v` in the `App`/`LetIn` case of `interp_related_gen`
et al is essentially saying that, in order to prove
`interp_related_gen`, we need to materialize an interpretation of the
function part of applications.  Since interpretation is in general
highly non-trivial (for `rawexpr`s, `value`s, etc), we must weaken
this condition.  By instead only requiring `f x == v`, we only
require being able to manifest *some* function which interprets to
`v`, a much easier task.  This weakening allows us to prove for each
interpretation-relation `R` …

Bump the rewriter to remove funext

---

src/Algebra/Ring.v
src/Curves/Edwards/AffineProofs.v

This will make progress towards #736
@andres-erbsen Please comment on my naming, and whether `of_Z_absorbs_homomorphism` seems okay, or if there's a different name you'd suggest

Remove the axiom in Curves/Edwards/AffineProofs

---

src/AbstractInterpretation/Wf.v

Adapt w.r.t. coq/coq#13139.

---

src/Bedrock/Field/Translation/Expr.v
src/Bedrock/Field/Translation/Proofs/Expr.v
src/Bedrock/Field/Translation/Proofs/ValidComputable/Expr.v

On top of #890 ; @jadephilipoom please review the final commit here
Just in case this gets merged before #890 :
Closes #890 
Closes #888

Fix cast argument for lnot_modulo

---

src/Util/ZUtil/Log2.v

compatibility with coq PR #14045

---

src/Arithmetic/BarrettReduction/HAC.v
src/Util/ZUtil/Shift.v

Sorry for the noise. This should be stable now.

sill PR 14045, zify is a bit better for Z.pow

---

src/Compilers/Z/Bounds/InterpretationLemmas/Tactics.v
src/Util/ZRange/SplitBounds.v
src/Util/ZUtil/AddGetCarry.v
src/Util/ZUtil/Modulo.v
src/Util/ZUtil/Modulo/Bootstrap.v
src/Util/ZUtil/Rshi.v
src/Util/ZUtil/Shift.v

This PR works with https://github.com/coq/coq/pull/14086 in a backwards compatible manner.
Some auxiliary lemmas for `Z` are removed.

Compatibility with coq/coq#14086

---

.github/workflows/coq.yml
src/Bedrock/Field/Interface/Representation.v
src/Bedrock/Field/Synthesis/Generic/Bignum.v
src/Bedrock/Field/Translation/Proofs/LoadStoreList.v

Let's see if we'll have any issues to solve here in order to integrate
https://github.com/mit-plv/bbv/pull/34, which will be required for
https://github.com/coq/coq/pull/14086.

Bump bedrock2 via rupicola

---

src/AbstractInterpretation/ZRange.v
src/Arithmetic/BYInv.v
src/Util/NatUtil.v
src/Util/ZRange/Operations.v
src/Util/ZRange/SplitBounds.v
src/Util/ZUtil/AddGetCarry.v
src/Util/ZUtil/Modulo.v
src/Util/ZUtil/Modulo/Bootstrap.v
src/Util/ZUtil/Rshi.v
src/Util/ZUtil/Shift.v
src/Util/ZUtil/Testbit.v
src/Util/ZUtil/TruncatingShiftl.v

This PR works with https://github.com/coq/coq/pull/14086 in a (hopefully) backwards compatible manner.

Compatibility with (n mod 0 = n)

---

inversion-c/inversion_template.c

Hi,
I've worked together with Benjamin Hvass (@bshvass) and Bas Spitters (@spitters) in the Fiat-Crypto implementation of divstep-based field inversion. Our C templates had a minor timing issue at the end of algorithm that was later fixed, so I'm pushing a manual fix here as well.
Thank you!

Make inversion run in constant time.

---

.github/workflows/coq-windows.yml

The cygwin packages from 8.11 are no longer valid.

Bump Windows CI to 8.13

---

src/Fancy/Barrett256.v
src/Fancy/Montgomery256.v

```
After |   Peak Mem | File Name              |   Before |   Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
-------------------------------------------------------------------------------------------------------------------------------
2m42.56s | 1437132 ko | Total Time / Peak Mem  | 3m38.00s | 2159616 ko || -0m55.43s ||   -722484 ko |  -25.43% |        -33.45%
-------------------------------------------------------------------------------------------------------------------------------
1m38.85s | 1437132 ko | Fancy/Barrett256.vo    | 2m16.63s | 2159616 ko || -0m37.78s ||   -722484 ko |  -27.65% |        -33.45%
1m03.71s | 1348908 ko | Fancy/Montgomery256.vo | 1m21.37s | 1672768 ko || -0m17.66s ||   -323860 ko |  -21.70% |        -19.36%
```

Faster version of wf proofs in fancy

---

src/Bedrock/Field/Synthesis/Examples/EncodeDecode.v
src/Bedrock/Field/Synthesis/Generic/UnsaturatedSolinas.v
src/Bedrock/Field/Synthesis/Generic/WordByWordMontgomery.v
src/PushButtonSynthesis/Primitives.v
src/PushButtonSynthesis/UnsaturatedSolinas.v
src/PushButtonSynthesis/WordByWordMontgomery.v
src/SlowPrimeSynthesisExamples.v

This makes things more uniform

Make `prime_bytes_bounds` not an `option`

---

src/Compilers/CommonSubexpressionElimination.v

Manually generate equality subschemes as mandated per the Coq documentation

---

README.md

``ocalm-zarith`` is also needed on Arch Linux

README: updates dependency list

---

inversion/zig/inversion.zig

inversion/zig: remove redundant comptime

---

src/Primitives/MxDHRepChange.v

That's the last one for coq/coq#14819 ;-)

Adapt to coq/coq#14819

---

src/Primitives/MxDHRepChange.v
src/Util/ListUtil.v

Hopefully this will make us compatible with coq/coq#14819

Compatability with coq/coq#14819

---

_CoqProject.in
src/Util/Bool/LeCompat.v
src/Util/ListUtil/Permutation.v
src/Util/ListUtil/PermutationCompat.v
src/Util/NUtil/Testbit.v
src/Util/Tuple.v
src/Util/ZUtil/Hints/ZArith.v
src/Util/ZUtil/Ones.v

Also add some lemmas for compat of x86 branch with 8.11

Factor utility lemmas from x86 out of asm files

---

.github/workflows/coq.yml

As per https://github.com/coq/coq/issues/15180, 9.2.1 cannot compile our code :-(

Pin Haskell to 9.0.1

---

src/Assembly/Equivalence.v
src/Assembly/Symbolic.v

Error messages now contain explanations such as:
```
Unable to unify: [inr [191, 197, 199, 201]] == [inr [34, 40, 43, 49]]
index 0: [191, 197, 199, 201] != [34, 40, 43, 49]
index 0: 191 != 34
(add 64, [3, 8, 10, 190]) != (add 64, [3, 8, 10, 33])
index 3: 190 != 33
(and 64, [30, 31]) != (and 1, [30])
(and 64, [(selectznz, [28, 8, 29]), (const 1, [])]) != (and 1, [(selectznz, [28, 8, 29])])
Operation mismatch: and 64 != and 1
```
@andres-erbsen @dderjoel what do you think?  Any suggestions/requests?

Improve symbolic equivalence unification errors

---

_CoqProject
src/Curves/EdwardsMontgomery.v

Andres and I looked at the proof and it doesn't look simple to automate it fully.

Edwards-Montgomery isomorphism proof

---

src/Assembly/Equivalence.v
src/Assembly/WithBedrock/Proofs.v
src/Assembly/WithBedrock/SymbolicProofs.v

I want to merge this now in case I don't get a chance to come back to it soon.
The remaining pieces are:
- define `get_asm_arguments`
- finish any missing pieces of `R_runtime_input`
- define `R_runtime_output`
- finish specing `build_merge_base_addresses` and prove it
- spec and prove `build_merge_stack_placeholders`
- spec and prove `LoadOutputs`
- finish connecting them in `symex_asm_func_M_correct`

Some progress on equivalence proofs

---

.github/workflows/coq.yml

Alternative to and closes #1046, per the response to
https://github.com/coq/coq/issues/15180

Compatibility with Haskell 9.2.1

---

src/Assembly/Equivalence.v
src/Assembly/WithBedrock/Proofs.v

Also, factor out build_merge_array_addresses
What remains is figuring out how to spec `LoadOutputs`, how to connect up the specs involving `R` with the ones not involving `R`.
@andres-erbsen could you review the changes in src/Assembly/Equivalence.v, the addition of `Definition get_asm_reg`, the changes to `Definition R_runtime_input`, and the changes to the preconditions of `Theorem generate_assembly_of_hinted_expr_correct` (the top-level theorem)?  You might also be interested in the spec `build_merge_stack_placeholders_ok` and the somewhat more monstrous spec `build_merge_base_addresses_ok`.

Some more work on equivalence-checking assembly proofs

---

src/Assembly/WithBedrock/Proofs.v

Also automate the asm proof a bit

Finish fleshing out input and output specs

---

src/Assembly/WithBedrock/Proofs.v

cc @andres-erbsen for the change in `R_list_scalar_or_array` and the parameterization over whether or not output scalars are encoded as pointers

Update asm equiv to finish all but output goal

---

src/Assembly/Symbolic.v

c.f. https://github.com/mit-plv/fiat-crypto/pull/1123#issuecomment-1035216542
Let's see what goes wrong

Enable const folding for mul asm

---

src/Assembly/WithBedrock/Proofs.v

More WIP on asm equiv

---

_CoqProject
src/Bedrock/End2End/X25519/MontgomeryLadder.v
src/Bedrock/Group/ScalarMult/CSwap.v
src/Bedrock/Group/ScalarMult/MontgomeryEquivalence.v
src/Bedrock/Group/ScalarMult/MontgomeryLadder.v

Implement cswap for felems and integrate into montladder.

Felem cswap

---

src/Assembly/WithBedrock/Proofs.v

The only thing that remains to be proven is that the runtime output
values that we get are the ones we expect to get.  I need to figure out
where to propogate this information from, but this proof is almost done!

More progress on assembly equivalence proof (almost done!)

---

_CoqProject
src/Util/ListUtil.v
src/Util/ListUtil/GroupAllBy.v
src/Util/ListUtil/Partition.v
src/Util/ListUtil/StdlibCompat.v

We can use groupAllBy to simplify #1134

Add groupBy and groupAllBy

---

src/Bedrock/End2End/X25519/MontgomeryLadderProperties.v
src/Bedrock/Field/Common/Util.v
src/Bedrock/Field/Translation/Parameters/Defaults.v

not built fully yet locally, but let's already see what CI says...

bump rupicola/bedrock2

---

src/Bedrock/Group/ScalarMult/MontgomeryLadder.v

According to the CI of Coq, this is the last one!

Adapt to coq/coq#15754

---

.github/workflows/coq-windows.yml

Maybe this will fix the issue in #1170

[CI] [Windows] Use -j2

---

.github/workflows/coq-macos.yml
.github/workflows/coq-windows.yml
.github/workflows/coq.yml

This should fix OOM issues.  Requires
https://github.com/coq/coq/pull/15886

Enable vm_compute on validate with bedrock2

---

src/Util/ListUtil.v

Adapt w.r.t. coq/coq#15434.

---

Makefile

Not sure how useful ocamlprof will be...

Add support for WITH_PERF=1 to use ocamloptp

---

.gitignore
Makefile
fiat-amd64/gentest.py

<strike>On top of #1199</strike>

Add PERF_TESTS=1 to call perf record on outputs

---

src/Assembly/Parse.v
src/Util/Strings/ParseArithmetic.v
src/Util/Strings/ParseArithmeticToTaps.v

Use poly parsing to support more labels 

---

src/BoundsPipeline.v
src/PushButtonSynthesis/Primitives.v

Error if there are assembly files with no globals

---

src/Assembly/Symbolic.v
src/Assembly/WithBedrock/Semantics.v
src/Assembly/WithBedrock/SymbolicProofs.v

We now support `mul`, `push`, `pop`.  <strike>On top of #1197.</strike>
@andres-erbsen @davidben do either of you want to review my implementation of push, pop, etc?

Add some operations to equivalence checker

---

_CoqProject
src/Util/FSets/FMapSect.v

Add FMapSect

---

_CoqProject
src/Util/FSets/FMapBool.v
src/Util/FSets/FMapEmpty.v
src/Util/FSets/FMapUnit.v

Next Up:
`FMapOption`, `FMapSum`, `FMapProd`
On top of #1234

Add some basic FMap structures

---

_CoqProject
src/Util/FSets/FMapOption.v
src/Util/FSets/FMapSum.v

On top of #1243 #1245 #1239 #1241

Add FMap{Option,Sum}

---

src/Util/Tactics/SetoidSubst.v

For when part of the relation involves a binder.

Use `setoid_rewrite` in `setoid_subst_rel` too

---

_CoqProject
src/Bedrock/Everything.v
src/Everything.v
src/Util/FSets/FMapProd.v

I've left some unused tactics in there because they may be useful
references in the future, or as a prototype for tries.
On top of #1256

Add FMapProd

---

.github/workflows/coq.yml
etc/ci/github-actions-make.sh

Only generate files on master PRs

---

_CoqProject
src/Bedrock/Everything.v
src/Everything.v
src/Util/FSets/FMapTrie.v

It compiles, but unfortunately the positivity checker is unhappy with
our schema for non-empty maps :-(, see
https://github.com/coq/coq/issues/16120
It's also very slow :-(
```
src/Util/FSets/FMapTrie.vo (real: 194.55, user: 193.16, sys: 1.24, mem: 818488 ko)
```

First stab at FMapTrie

---

_CoqProject
src/Bedrock/Everything.v
src/Everything.v
src/Util/FSets/FMapTrie.v
src/Util/FSets/FMapTrie/Shape.v
src/Util/Tactics/InHypUnderBindersDo.v

Split FMapTrie proofs and definitions for positivity checker

---

src/Util/FSets/FMapIso.v
src/Util/FSets/FMapOption.v
src/Util/FSets/FMapProd.v
src/Util/FSets/FMapSect.v
src/Util/FSets/FMapSum.v
src/Util/FSets/FMapTrie.v

Works around COQBUG(https://github.com/coq/coq/issues/16133)

Remove stupid hints from core db

---

_CoqProject
src/Bedrock/Everything.v
src/Everything.v
src/Util/FSets/FMapFlip.v
src/Util/FSets/FMapZ.v

On top of <strike>#1271</strike>, <strike>#1270</strike>, <strike>#1276</strike>

Add FMap{Flip,N,Z}

---

_CoqProject
src/Bedrock/Everything.v
src/Everything.v
src/Util/FSets/FMapFacts.v
src/Util/FSets/FMapOption.v
src/Util/FSets/FMapProd.v
src/Util/FSets/FMapSum.v
src/Util/FSets/FMapTrie.v

Add FMapFacts and make use of common facts

---

_CoqProject
src/Bedrock/Everything.v
src/Everything.v
src/Util/FSets/FMapTrie/ShapeEx.v
src/Util/FSets/FMapTrieEx.v

Hopefully it's actually efficient when extracted.
On top of <strike>#1266</strike>, <strike>#1270</strike>, <strike>#1271</strike>, #1272, <strike>#1273</strike>, <strike>#1276</strike>, <strike>#1280</strike>

Add examples of Tries for positive, N, Z

---

src/Util/FSets/FMapTrieEx.v

This is a bandaid for https://github.com/mit-plv/fiat-crypto/issues/1284

[TEMP] Disable FMapTrie functor instantiation

---

src/Util/FSets/FMapTrie.v
src/Util/FSets/FMapTrieEx.v

Factor FMapTrie proofs out of the module functor

---

src/Assembly/Symbolic.v

Should help with performance issues of https://github.com/coq/coq/pull/16206#issuecomment-1159711068

Disable equality schemes for `symbolic_state`

---

Makefile
Makefile-coq.local

Adjust warnings in _CoqProject

---

src/Stringification/Language.v

This will help debug rewriting

Show casts in comparisons

---

.github/workflows/coq-macos.yml
.github/workflows/coq-opam-package.yml
.github/workflows/coq-windows.yml
.github/workflows/coq.yml
Makefile
README.md
src/Language/API.v
src/Language/APINotations.v
src/Language/IdentifierParameters.v

Closes #1350 
To be reviewed and merged in tandem with https://github.com/mit-plv/rewriter/pull/57
Note for future reference: timing done with
```
export branch=ltac2-reify; export n="$(git log 9af638cfe53c76f7bf8e38b8c22464af2e587cb6..origin/ltac2-reify --oneline  | wc -l)"; for i in $(seq $((n-1)) -1 0); do spec="$branch$(for j in $(seq 1 $i); do echo -n ^; done)"; git checkout "$spec" && if ! git log -1 | grep -q 'Timing Diff'; then ./etc/coq-scripts/timing/make-pretty-timed-diff-tip.sh -j5 pre-standalone SKIP_BEDROCK2=1 && ((git log -1 --pretty=%B; echo; echo '<details><summary>Timing Diff</summary>'; echo '<p>'; echo; echo '```'; cat ./time-of-build-both.log; echo; echo '```'; echo '</p>'; echo '</details>') | git commit --amend -F - ) && export sha="$(git log -1 --pretty=%H)"; git …
```

Port reification to Ltac2

---

Makefile

I tested that build succeeded locally with SKIP_BEDROCK2=1 and then running make again started building bedrock2 files.

Makefile fixups

---

Makefile
etc/check_stack_limit.sh

c.f. https://github.com/coq/platform/issues/178#issuecomment-1265444555
@andres-erbsen Does this seem like a good idea to you?

Add stacksize warnings to avoid confusion

---

.github/workflows/coq-windows.yml
fiat-amd64/gentest.py

Still TODO: add lighter targets for amd64 tests (waiting to avoid conflict with #1417)

Make a lighter build target for windows CI

---

.github/workflows/coq-macos.yml
.github/workflows/coq-windows.yml
.github/workflows/coq.yml
Makefile
Makefile.config
Makefile.examples
Makefile.standalone
etc/ci/describe-system-config-macos.sh
etc/ci/describe-system-config-win.bat
etc/ci/describe-system-config.sh

Also factor out machine description printing.

Split out makefiles to allow binary testing without Coq files

---

.github/workflows/coq.yml
.github/workflows/docker-coq.yml
etc/ci/describe-system-config.sh
etc/ci/github-actions-docker-make.sh
etc/ci/github-actions-make.sh

We need to use the docker job for #1413 unless https://answers.launchpad.net/launchpad/+question/703409 gets answered.  I've reorganized the Makefile a bit so we can run standalone code outside docker (hopefully, we'll see).  I also factored the build param echoing into scripts.  I can explain the design a bit more if desired.  (Though in part this was a "least effort" thing.)
Thoughts @andres-erbsen ?

Use docker for master job

---

.github/workflows/coq.yml
.github/workflows/docker-coq.yml
etc/ci/describe-system-config.sh
etc/ci/github-actions-docker-make.sh
etc/ci/github-actions-make.sh
src/BoundsPipeline.v
src/PushButtonSynthesis/FancyMontgomeryReduction.v
src/PushButtonSynthesis/Primitives.v
src/PushButtonSynthesis/UnsaturatedSolinas.v
src/PushButtonSynthesis/WordByWordMontgomery.v

Note that this will need to be changed once https://github.com/mit-plv/rewriter/pull/77 is merged

Bump rewriter for Cache reified lemmas with LetIn

---

src/Rewriter/Rules.v
src/Rewriter/RulesProofs.v

These are from saturated solinas (#1358)

Add some rewrite rules about Z bool comparisons

---

etc/ensure_stack_limit.sh

Update ensure_stack_limit.sh to be POSIX-compliant

---

src/CLI.v
src/StandaloneHaskellMain.v
src/StandaloneOCamlMain.v
src/haskell.sed

This will eventually allow for better debugging of rewriting

Add support for printing to stderr

---

Makefile.standalone
etc/ensure_stack_limit.sh

See https://github.com/coq/coq/pull/16671#issuecomment-1280142881

Be more robust to ulimit failures

---

src/Bedrock/End2End/X25519/Field25519.v
src/Bedrock/Field/Synthesis/Examples/p224_64_new.v
src/Bedrock/Field/Synthesis/Generic/UnsaturatedSolinas.v
src/Bedrock/Field/Synthesis/Generic/WordByWordMontgomery.v
src/Bedrock/Field/Synthesis/New/UnsaturatedSolinas.v
src/Bedrock/Field/Synthesis/New/WordByWordMontgomery.v
src/Bedrock/Field/Synthesis/Specialized/UnsaturatedSolinas.v
src/Bedrock/Field/Translation/Parameters/Defaults32.v
src/Bedrock/Field/Translation/Parameters/Defaults64.v

Proof using annotations inserted automatically by `Set Suggest Proof Using` + ProofGeneral, except for the one instance of https://github.com/ProofGeneral/PG/issues/674 I had to manually correct.

Cleanup: remove some trailing spaces and add some Proof using

---

etc/ci/github-actions-docker-make.sh

Add bsdmainutils to github-actions-docker-make.sh

---

etc/ci/github-actions-make.sh

[CI] Don't run validate twice when it fails

---

etc/ci/github-actions-docker-make.sh

As per https://github.com/coq-community/docker-coq-action/issues/70#issue-1157215075

[CI] More fine-grained permissions

---

src/Bedrock/End2End/RupicolaCrypto/Broadcast.v
src/Bedrock/End2End/RupicolaCrypto/Derive.v
src/Bedrock/End2End/RupicolaCrypto/Low.v

Finishes the remaining admitted proofs in Broadcast.v and makes progress on chacha20.

Finish broadcast and make progress on chacha20

---

src/Assembly/Symbolic.v

On top of #1485 
This is a pass that I had mostly already written and proven in #1187.
It should help with 
<details><summary>error messages like the ones in <a href="https://github.com/mit-plv/fiat-crypto/pull/1187">#1187</a></summary>
```
```
check_args
/* Autogenerated: 'src/ExtractionOCaml/word_by_word_montgomery' p256 64 '2^256 - 2^224 + 2^192 + 2^96 - 1' mul --no-wide-int --shiftr-avoid-uint1 --hints-file 'fiat-amd64/boringssl_intel_manual_mul_p256.asm' */
/* curve description: p256 */
/* machine_wordsize = 64 (from "64") */
/* requested operations: mul */
/* m = 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff (from "2^256 - 2^224 + 2^192 + 2^96 - 1") */
/*                                                                    */
/* NOTE: In addition to the bounds …

Equiv checker: fuse inner add{,Z} into addcarry{,Z}

---

src/Assembly/Equivalence.v
src/CLI.v
src/PushButtonSynthesis/Primitives.v

This should make it a bit easier and more self-contained to extend options within Assembly/

Factor out assembly options a bit more

---

src/Assembly/Symbolic.v

This is necessary for memoizing bounds information in the dag.

ASM Equiv: Move bounds definitions up

---

src/Assembly/Symbolic.v

We still only enforce it in Symbolic.v, but hopefully that'll be enough to mostly ensure that future changes to one dag representation don't desync with the other one.
Hopefully at some point I or someone else will manage to track down the performance issues in switching to the New dag representation, and then maybe we'll be able to drop this?  Or it might be good to make it easy to change dag representations in the future.
In doing this, I've taken the opportunity to deduplicate some proofs between the new and old implementations.
Note that this is mostly just moving code around.

Reorganize dag modules to enforce better abstraction

---

src/Assembly/Symbolic.v

This should be enough to include bounds info from the dag in bounds analysis.
On top of #1508 
(cc @OwenConoly )

Prove some properties of the bounds in the dag

---

src/Assembly/Symbolic.v

Adjust a lemma for use in dag bounds

---

Makefile
src/PerfTesting/PerfTestPrint.v
src/PerfTesting/PerfTestSearch.v
src/PerfTesting/PerfTestSearchPattern.v

The other commands are mostly copying the sorts of things company-coq runs

Add a performance test for `Search` for Coq's bench

---

.github/workflows/c.yml

Also add C problem matcher
gcc 7 is no longer available?

Use default gcc version

---

src/Bedrock/End2End/RupicolaCrypto/Broadcast.v
src/Bedrock/End2End/RupicolaCrypto/Derive.v
src/Bedrock/End2End/RupicolaCrypto/Low.v

Fills in admits and fixes supporting lemmas to finish the chacha20 derivation. Note that the derivation is still aborted because Qed takes an unreasonable amount of time (it's unconfirmed whether it finishes).  This PR should hopefully help address #1512 as well.

(Almost) finish the chacha20 derivation

---

.github/workflows/c.yml

Try Newer Go

---

src/Bedrock/End2End/RupicolaCrypto/Broadcast.v

Compatibility with coq/coq#16756

---

etc/ci/test-fiat-rust-curve25519-dalek.sh

cf https://github.com/dalek-cryptography/curve25519-dalek/issues/414 , https://github.com/dalek-cryptography/curve25519-dalek/pull/428/files
@huitseeker Does this seem right?  (Are you the person to tag on this?)
Closes https://github.com/dalek-cryptography/curve25519-dalek/issues/480

[CI] [Rust] Adapt to new backend selection

---

fiat-zig/src/main.zig
inversion/zig/inversion.zig

Zig inversion code: replace std.meta.bitCount() with @bitSizeOf()

---

src/Util/ListUtil.v
src/Util/Tactics/SideConditionsBeforeToAfter.v
src/Util/WordUtil.v
src/Util/ZUtil/Div.v

Should be backwards compatible up to 8.16 at least.

Adapt w.r.t. coq/coq#16910.

---

src/Bedrock/End2End/X25519/MontgomeryLadderProperties.v
src/Bedrock/Field/Synthesis/Examples/redc.v

bump rupicola with v8.15 support

---

src/LegacyArithmetic/Double/Proofs/Decode.v

The lemma is something like
`... -> (X n -> X (1 * n)) * (X (1 * n) -> X n)`
applying to the goal produces the harder unification problem (with 1*n involved).

Adapt to coq/coq#16960 (less evar sensitive unification behaviour)

---

etc/ci/github-actions-docker-make.sh

Another attempt to fix the docker CI

---

fiat-zig/build.zig
fiat-zig/src/main.zig
inversion/zig/build.zig

Zig 0.11.0 is going to be tagged soon, and some changes to the build configuration were necessary to support the new package manager.

Minor changes to the build.zig files to prepare for Zig 0.11

---

etc/ci/test-fiat-c-boringssl.sh

Quick fix for #1592
Fixes #1592
cc @andres-erbsen

Exclude curve25519_64_msvc.c

---

src/Arithmetic/BYInv.v
src/Rewriter/Rules.v
src/Rewriter/RulesProofs.v
src/Util/ZUtil/Shift.v

Add another rule for bedrock2 rewriting

---

src/Arithmetic/BinaryExtendedGCD.v

This is a lightly updated version of #333, as discussed on that PR. The only changes I made were to fix things that broke because lemmas got renamed, moved, etc. in the last few years. Given the amount of time that's passed, there were surprisingly few of these!

Add a constant-time binary extended GCD algorithm.

---

src/Util/Loops.v

Should be backwards compatible. Fixes a bug exploit.

Adapt w.r.t. coq/coq#17564.

---

src/Curves/Montgomery/XZ.v
src/Util/FSets/FMapProd.v
src/Util/FSets/FMapTrie.v

Adapt to https://github.com/coq/coq/pull/17576

Adapt to https://github.com/coq/coq/pull/17576

---

.github/workflows/coq-debian.yml
.github/workflows/coq-macos.yml
.github/workflows/coq-windows.yml
README.md

In preparation for https://github.com/mit-plv/coqutil/pull/102

Drop CI testing of 8.16

---

etc/ci/describe-system-config.sh

Make etc/ci/describe-system-config.sh POSIX-compliant

---

.github/workflows/coq-alpine.yml
.github/workflows/coq-debian.yml
.github/workflows/coq-macos.yml
.github/workflows/coq-windows.yml
.github/workflows/docker-coq.yml
Makefile.standalone
etc/ci/mktemp_d.sh

In preparation for automatically deploying them to release pages.

Add packaging for standalone files

---

.github/workflows/coq-alpine.yml
.github/workflows/coq-debian.yml
.github/workflows/coq-docker.yml
.github/workflows/coq-macos.yml
.github/workflows/coq-windows.yml

This way the GitHub annotations won't just say "build"

[CI] Add names to build jobs

---

src/Language/IdentifierParameters.v

Adapt to coq/coq#18273 (Ltac2 supports head reduction)

---

.github/workflows/coq-docker.yml

Blocked on https://github.com/mit-plv/bedrock2/issues/388

Test more install targets on docker

---

.github/workflows/coq-docker.yml

Hopefully this speeds things up by a minute or so

[CI] Remove hopefully-useless --dry-run make install

---

src/AbstractInterpretation/Wf.v
src/Algebra/Hierarchy.v
src/Arithmetic/Core.v
src/Arithmetic/ModularArithmeticTheorems.v
src/Arithmetic/SolinasReduction.v
src/Assembly/WithBedrock/Proofs.v
src/Bedrock/Field/Synthesis/Generic/Bignum.v
src/Bedrock/Field/Translation/Proofs/Flatten.v
src/Bedrock/Field/Translation/Proofs/UsedVarnames.v
src/Util/Decidable/Decidable2Bool.v
src/Util/ListUtil.v
src/Util/NUtil/WithoutReferenceToZ.v
src/Util/NatUtil.v
src/Util/NumTheoryUtil.v
src/Util/Strings/String.v
src/Util/Strings/String_as_OT_old.v
src/Util/Tuple.v
src/Util/Wf.v
src/Util/ZUtil.v
src/Util/ZUtil/Shift.v

@JasonGross I think it might be ok. It's worth testing.

adapt to Coq/Coq#18164

---

src/Rewriter/Rules.v
src/Rewriter/RulesProofs.v

For https://github.com/mit-plv/fiat-crypto/pull/1609

Add prod_rect rewrite rule for saturated arithmetic

---

.github/workflows/coq-alpine.yml
.github/workflows/coq-debian.yml
.github/workflows/coq-docker.yml
.github/workflows/coq-macos.yml
.github/workflows/coq-windows.yml
.github/workflows/java.yml

Maybe we need both together?
Closes #1784 
Closes #1785

Bump actions/download-artifact and actions/upload-artifact from 3 to 4

---

.github/workflows/coq-archlinux.yml
etc/ci/describe-system-config.sh

<strike>N.B. Script for this was found with google, not sure how trustworthy it is</strike>
I didn't know GitHub actions allowed docker containers!

[CI] Add Arch Linux test

---

.github/workflows/coq-docker.yml

As per https://github.com/mit-plv/fiat-crypto/actions/runs/8482730755/job/23245208658?pr=1841#step:7:95

Update coq-docker.yml: Bump binaryen vesion

---

src/AbstractInterpretation/Proofs.v
src/Util/Equality.v
src/Util/ZUtil/Div.v
src/Util/ZUtil/Hints/ZArith.v
src/Util/ZUtil/LandLorBounds.v
src/Util/ZUtil/Pow.v

Adapt w.r.t. coq/coq#18895.

---

.github/workflows/coq-macos.yml

Might be useful for making `grep` more well-behaved.

[CI] `brew install grep` on MacOS for `ggrep`

---

.github/workflows/coq-debian.yml

cf https://github.com/mit-plv/fiat-crypto/actions/runs/8990595838/job/24703815722?pr=1891#step:6:22

Allow host libc to mismatch debian container libc when testing binary

---

fiat-zig/build.zig
inversion/zig/build.zig

Make build.zig files compatible with newly released zig 0.12

---

src/Arithmetic/BarrettReduction.v

On my machine, from 14mn to 25s.

Greatly reduce the compilation time of src/Arithmetic/BarrettReduction.v

---

src/Util/Option.v

Adapt w.r.t. coq/coq#19228.

---

fiat-html/main.js

to avoid "Error: currentWorker is undefined:"

[js] Set up workers earlier

---

.github/workflows/coq-debian.yml

[CI] [Debian] use -j1 on js-of-ocaml

---

.github/workflows/coq-debian.yml

So that the sudo make install step also works

[CI] [Debian] sudo work around broken git config

---

.github/workflows/zig.yml

Pin Zig to the current stable version instead of master

---

.github/workflows/coq-docker.yml

As per https://github.com/ocaml-wasm/wasm_of_ocaml?tab=readme-ov-file#installation, to deal with the CI failure in https://github.com/mit-plv/fiat-crypto/pull/1957 / https://github.com/mit-plv/fiat-crypto/actions/runs/10906100009/job/30271149044?pr=1957

Attempt to fix wasm_of_ocaml

---

src/Algebra/IntegralDomain.v
src/Algebra/Nsatz.v
src/Arithmetic/ModularArithmeticTheorems.v
src/Arithmetic/PrimeFieldTheorems.v
src/Compilers/MapBaseType.v
src/Compilers/MapBaseTypeWf.v
src/Compilers/Named/AListContext.v
src/Compilers/Named/FMapContext.v
src/Compilers/Named/MapCast.v
src/Compilers/Named/MapCastInterp.v
src/Compilers/Named/MapCastWf.v
src/Compilers/Named/MapType.v
src/Primitives/MxDHRepChange.v
src/Util/AdditionChainExponentiation.v
src/Util/Factorize.v
src/Util/ListUtil.v
src/Util/ListUtil/SetoidList.v
src/Util/MSetPositive/Facts.v
src/Util/Tuple.v

Adapt to https://github.com/coq/coq/pull/19530
This should be backward compatible and can be merged at your convenience, before the upstream PR.

Adapt to https://github.com/coq/coq/pull/19530

---

.github/workflows/coq-docker.yml

As per the README on https://github.com/ocaml-wasm/wasm_of_ocaml

Fix wasm_of_ocaml version, hopefully

---

.github/workflows/coq-macos.yml

Work around https://github.com/ocaml/opam-repository/pull/26891#issuecomment-2486598516

Work around issue with brew and opam

---

.github/workflows/coq-alpine.yml

[CI] [alpine-edge] coq => rocq

---

.github/workflows/zig.yml

Update the mlugg/setup-zig GitHub action

---

.github/workflows/coq-windows.yml

Maybe it works now?  cf https://github.com/JasonGross/test/actions/runs/15937922751/job/44961364304
Is https://github.com/ocaml/setup-ocaml/issues/979 fixed now?

[CI] [Windows] Upgrade setup-ocaml to v3

---

.github/workflows/zig.yml
fiat-zig/build.zig
inversion/zig/build.zig
inversion/zig/inversion.zig

Update the zig build definitions for Zig 0.15+

Update for Zig 0.15

---

src/Bedrock/End2End/Poly1305/Field1305.v
src/Bedrock/End2End/X25519/EdwardsXYZT.v
src/Bedrock/End2End/X25519/Field25519.v
src/Bedrock/End2End/X25519/GarageDoor.v
src/Bedrock/End2End/X25519/GarageDoorTop.v
src/Bedrock/End2End/X25519/MontgomeryLadder.v
src/Bedrock/End2End/X25519/MontgomeryLadderRISCV.v
src/Bedrock/Field/Interface/Compilation2.v
src/Bedrock/Field/Interface/Representation.v
src/Bedrock/Field/Synthesis/Examples/p224_64_new.v
src/Bedrock/Field/Synthesis/Generic/Bignum.v
src/Bedrock/Field/Synthesis/New/Signature.v
src/Bedrock/Field/Synthesis/New/UnsaturatedSolinas.v
src/Bedrock/Field/Synthesis/New/WordByWordMontgomery.v
src/Bedrock/Secp256k1/Addchain.v
src/Bedrock/Secp256k1/Field256k1.v
src/Bedrock/Secp256k1/JacobianCoZ.v
src/Bedrock/Secp256k1/JoyeLadder.v
src/Bedrock/Specs/Field.v

Closes https://github.com/mit-plv/fiat-crypto/pull/2154

Placeholder refactoring rebased

---

src/Language/API.v

Adapt to https://github.com/rocq-prover/rocq/pull/20816

Adapt to https://github.com/rocq-prover/rocq/pull/20816

---

src/Bedrock/End2End/X25519/EdwardsXYZT.v
src/Curves/Edwards/XYZT/Basic.v
src/Curves/Edwards/XYZT/Precomputed.v
src/Curves/Edwards/XYZT/Readdition.v

Rename, shorten, and revise some proofs and definitions in Basic.v, also add a Module to make it more clear that we're working with extended coordinates. Some of this may be personal preference.

Ed25519: Cleanup Basic.v

---

coq-fiat-crypto-with-bedrock.opam
coq-fiat-crypto-without-bedrock.opam
coq-fiat-crypto.opam

Work towards automating PRs to the opam repo on tagging a version

Add opam files, mostly from https://github.com/rocq-prover/opam
